// Code generated by ent, DO NOT EDIT.

package anthropicusage

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the anthropicusage type in the database.
	Label = "anthropic_usage"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeviceID holds the string denoting the device_id field in the database.
	FieldDeviceID = "device_id"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldAccountUUID holds the string denoting the account_uuid field in the database.
	FieldAccountUUID = "account_uuid"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldInputTokens holds the string denoting the input_tokens field in the database.
	FieldInputTokens = "input_tokens"
	// FieldCacheReadInputTokens holds the string denoting the cache_read_input_tokens field in the database.
	FieldCacheReadInputTokens = "cache_read_input_tokens"
	// FieldCacheCreationInputTokens holds the string denoting the cache_creation_input_tokens field in the database.
	FieldCacheCreationInputTokens = "cache_creation_input_tokens"
	// FieldOutputTokens holds the string denoting the output_tokens field in the database.
	FieldOutputTokens = "output_tokens"
	// FieldCacheCreationEphemeral5mInputTokens holds the string denoting the cache_creation_ephemeral_5m_input_tokens field in the database.
	FieldCacheCreationEphemeral5mInputTokens = "cache_creation_ephemeral_5m_input_tokens"
	// FieldCacheCreationEphemeral1hInputTokens holds the string denoting the cache_creation_ephemeral_1h_input_tokens field in the database.
	FieldCacheCreationEphemeral1hInputTokens = "cache_creation_ephemeral_1h_input_tokens"
	// FieldCacheHitRate holds the string denoting the cache_hit_rate field in the database.
	FieldCacheHitRate = "cache_hit_rate"
	// FieldRaw holds the string denoting the raw field in the database.
	FieldRaw = "raw"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the anthropicusage in the database.
	Table = "anthropic_usage"
)

// Columns holds all SQL columns for anthropicusage fields.
var Columns = []string{
	FieldID,
	FieldDeviceID,
	FieldSessionID,
	FieldAccountUUID,
	FieldModel,
	FieldInputTokens,
	FieldCacheReadInputTokens,
	FieldCacheCreationInputTokens,
	FieldOutputTokens,
	FieldCacheCreationEphemeral5mInputTokens,
	FieldCacheCreationEphemeral1hInputTokens,
	FieldCacheHitRate,
	FieldRaw,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultModel holds the default value on creation for the "model" field.
	DefaultModel string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the AnthropicUsage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDeviceID orders the results by the device_id field.
func ByDeviceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceID, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByAccountUUID orders the results by the account_uuid field.
func ByAccountUUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountUUID, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByInputTokens orders the results by the input_tokens field.
func ByInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputTokens, opts...).ToFunc()
}

// ByCacheReadInputTokens orders the results by the cache_read_input_tokens field.
func ByCacheReadInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheReadInputTokens, opts...).ToFunc()
}

// ByCacheCreationInputTokens orders the results by the cache_creation_input_tokens field.
func ByCacheCreationInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheCreationInputTokens, opts...).ToFunc()
}

// ByOutputTokens orders the results by the output_tokens field.
func ByOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputTokens, opts...).ToFunc()
}

// ByCacheCreationEphemeral5mInputTokens orders the results by the cache_creation_ephemeral_5m_input_tokens field.
func ByCacheCreationEphemeral5mInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheCreationEphemeral5mInputTokens, opts...).ToFunc()
}

// ByCacheCreationEphemeral1hInputTokens orders the results by the cache_creation_ephemeral_1h_input_tokens field.
func ByCacheCreationEphemeral1hInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheCreationEphemeral1hInputTokens, opts...).ToFunc()
}

// ByCacheHitRate orders the results by the cache_hit_rate field.
func ByCacheHitRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheHitRate, opts...).ToFunc()
}

// ByRaw orders the results by the raw field.
func ByRaw(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRaw, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
