// Code generated by ent, DO NOT EDIT.

package anthropicusage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/realityone/cocoq/server/database/dbrt/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLTE(FieldID, id))
}

// DeviceID applies equality check predicate on the "device_id" field. It's identical to DeviceIDEQ.
func DeviceID(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldDeviceID, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldSessionID, v))
}

// AccountUUID applies equality check predicate on the "account_uuid" field. It's identical to AccountUUIDEQ.
func AccountUUID(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldAccountUUID, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldModel, v))
}

// InputTokens applies equality check predicate on the "input_tokens" field. It's identical to InputTokensEQ.
func InputTokens(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldInputTokens, v))
}

// CacheReadInputTokens applies equality check predicate on the "cache_read_input_tokens" field. It's identical to CacheReadInputTokensEQ.
func CacheReadInputTokens(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldCacheReadInputTokens, v))
}

// CacheCreationInputTokens applies equality check predicate on the "cache_creation_input_tokens" field. It's identical to CacheCreationInputTokensEQ.
func CacheCreationInputTokens(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldCacheCreationInputTokens, v))
}

// OutputTokens applies equality check predicate on the "output_tokens" field. It's identical to OutputTokensEQ.
func OutputTokens(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldOutputTokens, v))
}

// CacheCreationEphemeral5mInputTokens applies equality check predicate on the "cache_creation_ephemeral_5m_input_tokens" field. It's identical to CacheCreationEphemeral5mInputTokensEQ.
func CacheCreationEphemeral5mInputTokens(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldCacheCreationEphemeral5mInputTokens, v))
}

// CacheCreationEphemeral1hInputTokens applies equality check predicate on the "cache_creation_ephemeral_1h_input_tokens" field. It's identical to CacheCreationEphemeral1hInputTokensEQ.
func CacheCreationEphemeral1hInputTokens(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldCacheCreationEphemeral1hInputTokens, v))
}

// CacheHitRate applies equality check predicate on the "cache_hit_rate" field. It's identical to CacheHitRateEQ.
func CacheHitRate(v float64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldCacheHitRate, v))
}

// Raw applies equality check predicate on the "raw" field. It's identical to RawEQ.
func Raw(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldRaw, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeviceIDEQ applies the EQ predicate on the "device_id" field.
func DeviceIDEQ(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldDeviceID, v))
}

// DeviceIDNEQ applies the NEQ predicate on the "device_id" field.
func DeviceIDNEQ(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNEQ(FieldDeviceID, v))
}

// DeviceIDIn applies the In predicate on the "device_id" field.
func DeviceIDIn(vs ...string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldIn(FieldDeviceID, vs...))
}

// DeviceIDNotIn applies the NotIn predicate on the "device_id" field.
func DeviceIDNotIn(vs ...string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNotIn(FieldDeviceID, vs...))
}

// DeviceIDGT applies the GT predicate on the "device_id" field.
func DeviceIDGT(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGT(FieldDeviceID, v))
}

// DeviceIDGTE applies the GTE predicate on the "device_id" field.
func DeviceIDGTE(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGTE(FieldDeviceID, v))
}

// DeviceIDLT applies the LT predicate on the "device_id" field.
func DeviceIDLT(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLT(FieldDeviceID, v))
}

// DeviceIDLTE applies the LTE predicate on the "device_id" field.
func DeviceIDLTE(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLTE(FieldDeviceID, v))
}

// DeviceIDContains applies the Contains predicate on the "device_id" field.
func DeviceIDContains(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldContains(FieldDeviceID, v))
}

// DeviceIDHasPrefix applies the HasPrefix predicate on the "device_id" field.
func DeviceIDHasPrefix(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldHasPrefix(FieldDeviceID, v))
}

// DeviceIDHasSuffix applies the HasSuffix predicate on the "device_id" field.
func DeviceIDHasSuffix(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldHasSuffix(FieldDeviceID, v))
}

// DeviceIDEqualFold applies the EqualFold predicate on the "device_id" field.
func DeviceIDEqualFold(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEqualFold(FieldDeviceID, v))
}

// DeviceIDContainsFold applies the ContainsFold predicate on the "device_id" field.
func DeviceIDContainsFold(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldContainsFold(FieldDeviceID, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldContainsFold(FieldSessionID, v))
}

// AccountUUIDEQ applies the EQ predicate on the "account_uuid" field.
func AccountUUIDEQ(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldAccountUUID, v))
}

// AccountUUIDNEQ applies the NEQ predicate on the "account_uuid" field.
func AccountUUIDNEQ(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNEQ(FieldAccountUUID, v))
}

// AccountUUIDIn applies the In predicate on the "account_uuid" field.
func AccountUUIDIn(vs ...string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldIn(FieldAccountUUID, vs...))
}

// AccountUUIDNotIn applies the NotIn predicate on the "account_uuid" field.
func AccountUUIDNotIn(vs ...string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNotIn(FieldAccountUUID, vs...))
}

// AccountUUIDGT applies the GT predicate on the "account_uuid" field.
func AccountUUIDGT(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGT(FieldAccountUUID, v))
}

// AccountUUIDGTE applies the GTE predicate on the "account_uuid" field.
func AccountUUIDGTE(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGTE(FieldAccountUUID, v))
}

// AccountUUIDLT applies the LT predicate on the "account_uuid" field.
func AccountUUIDLT(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLT(FieldAccountUUID, v))
}

// AccountUUIDLTE applies the LTE predicate on the "account_uuid" field.
func AccountUUIDLTE(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLTE(FieldAccountUUID, v))
}

// AccountUUIDContains applies the Contains predicate on the "account_uuid" field.
func AccountUUIDContains(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldContains(FieldAccountUUID, v))
}

// AccountUUIDHasPrefix applies the HasPrefix predicate on the "account_uuid" field.
func AccountUUIDHasPrefix(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldHasPrefix(FieldAccountUUID, v))
}

// AccountUUIDHasSuffix applies the HasSuffix predicate on the "account_uuid" field.
func AccountUUIDHasSuffix(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldHasSuffix(FieldAccountUUID, v))
}

// AccountUUIDEqualFold applies the EqualFold predicate on the "account_uuid" field.
func AccountUUIDEqualFold(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEqualFold(FieldAccountUUID, v))
}

// AccountUUIDContainsFold applies the ContainsFold predicate on the "account_uuid" field.
func AccountUUIDContainsFold(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldContainsFold(FieldAccountUUID, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldContainsFold(FieldModel, v))
}

// InputTokensEQ applies the EQ predicate on the "input_tokens" field.
func InputTokensEQ(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldInputTokens, v))
}

// InputTokensNEQ applies the NEQ predicate on the "input_tokens" field.
func InputTokensNEQ(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNEQ(FieldInputTokens, v))
}

// InputTokensIn applies the In predicate on the "input_tokens" field.
func InputTokensIn(vs ...int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldIn(FieldInputTokens, vs...))
}

// InputTokensNotIn applies the NotIn predicate on the "input_tokens" field.
func InputTokensNotIn(vs ...int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNotIn(FieldInputTokens, vs...))
}

// InputTokensGT applies the GT predicate on the "input_tokens" field.
func InputTokensGT(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGT(FieldInputTokens, v))
}

// InputTokensGTE applies the GTE predicate on the "input_tokens" field.
func InputTokensGTE(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGTE(FieldInputTokens, v))
}

// InputTokensLT applies the LT predicate on the "input_tokens" field.
func InputTokensLT(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLT(FieldInputTokens, v))
}

// InputTokensLTE applies the LTE predicate on the "input_tokens" field.
func InputTokensLTE(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLTE(FieldInputTokens, v))
}

// CacheReadInputTokensEQ applies the EQ predicate on the "cache_read_input_tokens" field.
func CacheReadInputTokensEQ(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldCacheReadInputTokens, v))
}

// CacheReadInputTokensNEQ applies the NEQ predicate on the "cache_read_input_tokens" field.
func CacheReadInputTokensNEQ(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNEQ(FieldCacheReadInputTokens, v))
}

// CacheReadInputTokensIn applies the In predicate on the "cache_read_input_tokens" field.
func CacheReadInputTokensIn(vs ...int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldIn(FieldCacheReadInputTokens, vs...))
}

// CacheReadInputTokensNotIn applies the NotIn predicate on the "cache_read_input_tokens" field.
func CacheReadInputTokensNotIn(vs ...int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNotIn(FieldCacheReadInputTokens, vs...))
}

// CacheReadInputTokensGT applies the GT predicate on the "cache_read_input_tokens" field.
func CacheReadInputTokensGT(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGT(FieldCacheReadInputTokens, v))
}

// CacheReadInputTokensGTE applies the GTE predicate on the "cache_read_input_tokens" field.
func CacheReadInputTokensGTE(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGTE(FieldCacheReadInputTokens, v))
}

// CacheReadInputTokensLT applies the LT predicate on the "cache_read_input_tokens" field.
func CacheReadInputTokensLT(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLT(FieldCacheReadInputTokens, v))
}

// CacheReadInputTokensLTE applies the LTE predicate on the "cache_read_input_tokens" field.
func CacheReadInputTokensLTE(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLTE(FieldCacheReadInputTokens, v))
}

// CacheCreationInputTokensEQ applies the EQ predicate on the "cache_creation_input_tokens" field.
func CacheCreationInputTokensEQ(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldCacheCreationInputTokens, v))
}

// CacheCreationInputTokensNEQ applies the NEQ predicate on the "cache_creation_input_tokens" field.
func CacheCreationInputTokensNEQ(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNEQ(FieldCacheCreationInputTokens, v))
}

// CacheCreationInputTokensIn applies the In predicate on the "cache_creation_input_tokens" field.
func CacheCreationInputTokensIn(vs ...int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldIn(FieldCacheCreationInputTokens, vs...))
}

// CacheCreationInputTokensNotIn applies the NotIn predicate on the "cache_creation_input_tokens" field.
func CacheCreationInputTokensNotIn(vs ...int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNotIn(FieldCacheCreationInputTokens, vs...))
}

// CacheCreationInputTokensGT applies the GT predicate on the "cache_creation_input_tokens" field.
func CacheCreationInputTokensGT(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGT(FieldCacheCreationInputTokens, v))
}

// CacheCreationInputTokensGTE applies the GTE predicate on the "cache_creation_input_tokens" field.
func CacheCreationInputTokensGTE(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGTE(FieldCacheCreationInputTokens, v))
}

// CacheCreationInputTokensLT applies the LT predicate on the "cache_creation_input_tokens" field.
func CacheCreationInputTokensLT(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLT(FieldCacheCreationInputTokens, v))
}

// CacheCreationInputTokensLTE applies the LTE predicate on the "cache_creation_input_tokens" field.
func CacheCreationInputTokensLTE(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLTE(FieldCacheCreationInputTokens, v))
}

// OutputTokensEQ applies the EQ predicate on the "output_tokens" field.
func OutputTokensEQ(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldOutputTokens, v))
}

// OutputTokensNEQ applies the NEQ predicate on the "output_tokens" field.
func OutputTokensNEQ(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNEQ(FieldOutputTokens, v))
}

// OutputTokensIn applies the In predicate on the "output_tokens" field.
func OutputTokensIn(vs ...int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldIn(FieldOutputTokens, vs...))
}

// OutputTokensNotIn applies the NotIn predicate on the "output_tokens" field.
func OutputTokensNotIn(vs ...int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNotIn(FieldOutputTokens, vs...))
}

// OutputTokensGT applies the GT predicate on the "output_tokens" field.
func OutputTokensGT(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGT(FieldOutputTokens, v))
}

// OutputTokensGTE applies the GTE predicate on the "output_tokens" field.
func OutputTokensGTE(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGTE(FieldOutputTokens, v))
}

// OutputTokensLT applies the LT predicate on the "output_tokens" field.
func OutputTokensLT(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLT(FieldOutputTokens, v))
}

// OutputTokensLTE applies the LTE predicate on the "output_tokens" field.
func OutputTokensLTE(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLTE(FieldOutputTokens, v))
}

// CacheCreationEphemeral5mInputTokensEQ applies the EQ predicate on the "cache_creation_ephemeral_5m_input_tokens" field.
func CacheCreationEphemeral5mInputTokensEQ(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldCacheCreationEphemeral5mInputTokens, v))
}

// CacheCreationEphemeral5mInputTokensNEQ applies the NEQ predicate on the "cache_creation_ephemeral_5m_input_tokens" field.
func CacheCreationEphemeral5mInputTokensNEQ(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNEQ(FieldCacheCreationEphemeral5mInputTokens, v))
}

// CacheCreationEphemeral5mInputTokensIn applies the In predicate on the "cache_creation_ephemeral_5m_input_tokens" field.
func CacheCreationEphemeral5mInputTokensIn(vs ...int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldIn(FieldCacheCreationEphemeral5mInputTokens, vs...))
}

// CacheCreationEphemeral5mInputTokensNotIn applies the NotIn predicate on the "cache_creation_ephemeral_5m_input_tokens" field.
func CacheCreationEphemeral5mInputTokensNotIn(vs ...int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNotIn(FieldCacheCreationEphemeral5mInputTokens, vs...))
}

// CacheCreationEphemeral5mInputTokensGT applies the GT predicate on the "cache_creation_ephemeral_5m_input_tokens" field.
func CacheCreationEphemeral5mInputTokensGT(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGT(FieldCacheCreationEphemeral5mInputTokens, v))
}

// CacheCreationEphemeral5mInputTokensGTE applies the GTE predicate on the "cache_creation_ephemeral_5m_input_tokens" field.
func CacheCreationEphemeral5mInputTokensGTE(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGTE(FieldCacheCreationEphemeral5mInputTokens, v))
}

// CacheCreationEphemeral5mInputTokensLT applies the LT predicate on the "cache_creation_ephemeral_5m_input_tokens" field.
func CacheCreationEphemeral5mInputTokensLT(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLT(FieldCacheCreationEphemeral5mInputTokens, v))
}

// CacheCreationEphemeral5mInputTokensLTE applies the LTE predicate on the "cache_creation_ephemeral_5m_input_tokens" field.
func CacheCreationEphemeral5mInputTokensLTE(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLTE(FieldCacheCreationEphemeral5mInputTokens, v))
}

// CacheCreationEphemeral1hInputTokensEQ applies the EQ predicate on the "cache_creation_ephemeral_1h_input_tokens" field.
func CacheCreationEphemeral1hInputTokensEQ(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldCacheCreationEphemeral1hInputTokens, v))
}

// CacheCreationEphemeral1hInputTokensNEQ applies the NEQ predicate on the "cache_creation_ephemeral_1h_input_tokens" field.
func CacheCreationEphemeral1hInputTokensNEQ(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNEQ(FieldCacheCreationEphemeral1hInputTokens, v))
}

// CacheCreationEphemeral1hInputTokensIn applies the In predicate on the "cache_creation_ephemeral_1h_input_tokens" field.
func CacheCreationEphemeral1hInputTokensIn(vs ...int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldIn(FieldCacheCreationEphemeral1hInputTokens, vs...))
}

// CacheCreationEphemeral1hInputTokensNotIn applies the NotIn predicate on the "cache_creation_ephemeral_1h_input_tokens" field.
func CacheCreationEphemeral1hInputTokensNotIn(vs ...int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNotIn(FieldCacheCreationEphemeral1hInputTokens, vs...))
}

// CacheCreationEphemeral1hInputTokensGT applies the GT predicate on the "cache_creation_ephemeral_1h_input_tokens" field.
func CacheCreationEphemeral1hInputTokensGT(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGT(FieldCacheCreationEphemeral1hInputTokens, v))
}

// CacheCreationEphemeral1hInputTokensGTE applies the GTE predicate on the "cache_creation_ephemeral_1h_input_tokens" field.
func CacheCreationEphemeral1hInputTokensGTE(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGTE(FieldCacheCreationEphemeral1hInputTokens, v))
}

// CacheCreationEphemeral1hInputTokensLT applies the LT predicate on the "cache_creation_ephemeral_1h_input_tokens" field.
func CacheCreationEphemeral1hInputTokensLT(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLT(FieldCacheCreationEphemeral1hInputTokens, v))
}

// CacheCreationEphemeral1hInputTokensLTE applies the LTE predicate on the "cache_creation_ephemeral_1h_input_tokens" field.
func CacheCreationEphemeral1hInputTokensLTE(v int64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLTE(FieldCacheCreationEphemeral1hInputTokens, v))
}

// CacheHitRateEQ applies the EQ predicate on the "cache_hit_rate" field.
func CacheHitRateEQ(v float64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldCacheHitRate, v))
}

// CacheHitRateNEQ applies the NEQ predicate on the "cache_hit_rate" field.
func CacheHitRateNEQ(v float64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNEQ(FieldCacheHitRate, v))
}

// CacheHitRateIn applies the In predicate on the "cache_hit_rate" field.
func CacheHitRateIn(vs ...float64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldIn(FieldCacheHitRate, vs...))
}

// CacheHitRateNotIn applies the NotIn predicate on the "cache_hit_rate" field.
func CacheHitRateNotIn(vs ...float64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNotIn(FieldCacheHitRate, vs...))
}

// CacheHitRateGT applies the GT predicate on the "cache_hit_rate" field.
func CacheHitRateGT(v float64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGT(FieldCacheHitRate, v))
}

// CacheHitRateGTE applies the GTE predicate on the "cache_hit_rate" field.
func CacheHitRateGTE(v float64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGTE(FieldCacheHitRate, v))
}

// CacheHitRateLT applies the LT predicate on the "cache_hit_rate" field.
func CacheHitRateLT(v float64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLT(FieldCacheHitRate, v))
}

// CacheHitRateLTE applies the LTE predicate on the "cache_hit_rate" field.
func CacheHitRateLTE(v float64) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLTE(FieldCacheHitRate, v))
}

// RawEQ applies the EQ predicate on the "raw" field.
func RawEQ(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldRaw, v))
}

// RawNEQ applies the NEQ predicate on the "raw" field.
func RawNEQ(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNEQ(FieldRaw, v))
}

// RawIn applies the In predicate on the "raw" field.
func RawIn(vs ...string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldIn(FieldRaw, vs...))
}

// RawNotIn applies the NotIn predicate on the "raw" field.
func RawNotIn(vs ...string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNotIn(FieldRaw, vs...))
}

// RawGT applies the GT predicate on the "raw" field.
func RawGT(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGT(FieldRaw, v))
}

// RawGTE applies the GTE predicate on the "raw" field.
func RawGTE(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGTE(FieldRaw, v))
}

// RawLT applies the LT predicate on the "raw" field.
func RawLT(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLT(FieldRaw, v))
}

// RawLTE applies the LTE predicate on the "raw" field.
func RawLTE(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLTE(FieldRaw, v))
}

// RawContains applies the Contains predicate on the "raw" field.
func RawContains(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldContains(FieldRaw, v))
}

// RawHasPrefix applies the HasPrefix predicate on the "raw" field.
func RawHasPrefix(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldHasPrefix(FieldRaw, v))
}

// RawHasSuffix applies the HasSuffix predicate on the "raw" field.
func RawHasSuffix(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldHasSuffix(FieldRaw, v))
}

// RawEqualFold applies the EqualFold predicate on the "raw" field.
func RawEqualFold(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEqualFold(FieldRaw, v))
}

// RawContainsFold applies the ContainsFold predicate on the "raw" field.
func RawContainsFold(v string) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldContainsFold(FieldRaw, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AnthropicUsage) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AnthropicUsage) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AnthropicUsage) predicate.AnthropicUsage {
	return predicate.AnthropicUsage(sql.NotPredicates(p))
}
