// Code generated by ent, DO NOT EDIT.

package usergrantedprovideraccount

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the usergrantedprovideraccount type in the database.
	Label = "user_granted_provider_account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldProviderAccountID holds the string denoting the provider_account_id field in the database.
	FieldProviderAccountID = "provider_account_id"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeProviderAccount holds the string denoting the provider_account edge name in mutations.
	EdgeProviderAccount = "provider_account"
	// Table holds the table name of the usergrantedprovideraccount in the database.
	Table = "user_granted_provider_account"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "user_granted_provider_account"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "user"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// ProviderAccountTable is the table that holds the provider_account relation/edge.
	ProviderAccountTable = "user_granted_provider_account"
	// ProviderAccountInverseTable is the table name for the ProviderAccount entity.
	// It exists in this package in order to avoid circular dependency with the "provideraccount" package.
	ProviderAccountInverseTable = "provider_account"
	// ProviderAccountColumn is the table column denoting the provider_account relation/edge.
	ProviderAccountColumn = "provider_account_id"
)

// Columns holds all SQL columns for usergrantedprovideraccount fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldProviderAccountID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the UserGrantedProviderAccount queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByProviderAccountID orders the results by the provider_account_id field.
func ByProviderAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderAccountID, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByProviderAccountField orders the results by provider_account field.
func ByProviderAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProviderAccountStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newProviderAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProviderAccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProviderAccountTable, ProviderAccountColumn),
	)
}
