// Code generated by ent, DO NOT EDIT.

package usergrantedprovideraccount

import (
	"cocoq/server/database/dbrt/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserGrantedProviderAccount {
	return predicate.UserGrantedProviderAccount(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserGrantedProviderAccount {
	return predicate.UserGrantedProviderAccount(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserGrantedProviderAccount {
	return predicate.UserGrantedProviderAccount(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserGrantedProviderAccount {
	return predicate.UserGrantedProviderAccount(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserGrantedProviderAccount {
	return predicate.UserGrantedProviderAccount(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserGrantedProviderAccount {
	return predicate.UserGrantedProviderAccount(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserGrantedProviderAccount {
	return predicate.UserGrantedProviderAccount(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserGrantedProviderAccount {
	return predicate.UserGrantedProviderAccount(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserGrantedProviderAccount {
	return predicate.UserGrantedProviderAccount(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserGrantedProviderAccount {
	return predicate.UserGrantedProviderAccount(sql.FieldEQ(FieldUserID, v))
}

// ProviderAccountID applies equality check predicate on the "provider_account_id" field. It's identical to ProviderAccountIDEQ.
func ProviderAccountID(v int64) predicate.UserGrantedProviderAccount {
	return predicate.UserGrantedProviderAccount(sql.FieldEQ(FieldProviderAccountID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserGrantedProviderAccount {
	return predicate.UserGrantedProviderAccount(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserGrantedProviderAccount {
	return predicate.UserGrantedProviderAccount(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserGrantedProviderAccount {
	return predicate.UserGrantedProviderAccount(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserGrantedProviderAccount {
	return predicate.UserGrantedProviderAccount(sql.FieldNotIn(FieldUserID, vs...))
}

// ProviderAccountIDEQ applies the EQ predicate on the "provider_account_id" field.
func ProviderAccountIDEQ(v int64) predicate.UserGrantedProviderAccount {
	return predicate.UserGrantedProviderAccount(sql.FieldEQ(FieldProviderAccountID, v))
}

// ProviderAccountIDNEQ applies the NEQ predicate on the "provider_account_id" field.
func ProviderAccountIDNEQ(v int64) predicate.UserGrantedProviderAccount {
	return predicate.UserGrantedProviderAccount(sql.FieldNEQ(FieldProviderAccountID, v))
}

// ProviderAccountIDIn applies the In predicate on the "provider_account_id" field.
func ProviderAccountIDIn(vs ...int64) predicate.UserGrantedProviderAccount {
	return predicate.UserGrantedProviderAccount(sql.FieldIn(FieldProviderAccountID, vs...))
}

// ProviderAccountIDNotIn applies the NotIn predicate on the "provider_account_id" field.
func ProviderAccountIDNotIn(vs ...int64) predicate.UserGrantedProviderAccount {
	return predicate.UserGrantedProviderAccount(sql.FieldNotIn(FieldProviderAccountID, vs...))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserGrantedProviderAccount {
	return predicate.UserGrantedProviderAccount(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserGrantedProviderAccount {
	return predicate.UserGrantedProviderAccount(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProviderAccount applies the HasEdge predicate on the "provider_account" edge.
func HasProviderAccount() predicate.UserGrantedProviderAccount {
	return predicate.UserGrantedProviderAccount(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProviderAccountTable, ProviderAccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProviderAccountWith applies the HasEdge predicate on the "provider_account" edge with a given conditions (other predicates).
func HasProviderAccountWith(preds ...predicate.ProviderAccount) predicate.UserGrantedProviderAccount {
	return predicate.UserGrantedProviderAccount(func(s *sql.Selector) {
		step := newProviderAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserGrantedProviderAccount) predicate.UserGrantedProviderAccount {
	return predicate.UserGrantedProviderAccount(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserGrantedProviderAccount) predicate.UserGrantedProviderAccount {
	return predicate.UserGrantedProviderAccount(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserGrantedProviderAccount) predicate.UserGrantedProviderAccount {
	return predicate.UserGrantedProviderAccount(sql.NotPredicates(p))
}
