// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AnthropicUsage is the predicate function for anthropicusage builders.
type AnthropicUsage func(*sql.Selector)
