// Code generated by ent, DO NOT EDIT.

package provideraccount

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the provideraccount type in the database.
	Label = "provider_account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldAccountUUID holds the string denoting the account_uuid field in the database.
	FieldAccountUUID = "account_uuid"
	// FieldAccessToken holds the string denoting the access_token field in the database.
	FieldAccessToken = "access_token"
	// FieldRefreshToken holds the string denoting the refresh_token field in the database.
	FieldRefreshToken = "refresh_token"
	// FieldCredentials holds the string denoting the credentials field in the database.
	FieldCredentials = "credentials"
	// EdgeFakeTokens holds the string denoting the fake_tokens edge name in mutations.
	EdgeFakeTokens = "fake_tokens"
	// EdgeGrantedUsers holds the string denoting the granted_users edge name in mutations.
	EdgeGrantedUsers = "granted_users"
	// Table holds the table name of the provideraccount in the database.
	Table = "provider_account"
	// FakeTokensTable is the table that holds the fake_tokens relation/edge.
	FakeTokensTable = "fake_token"
	// FakeTokensInverseTable is the table name for the FakeToken entity.
	// It exists in this package in order to avoid circular dependency with the "faketoken" package.
	FakeTokensInverseTable = "fake_token"
	// FakeTokensColumn is the table column denoting the fake_tokens relation/edge.
	FakeTokensColumn = "provider_account_id"
	// GrantedUsersTable is the table that holds the granted_users relation/edge.
	GrantedUsersTable = "user_granted_provider_account"
	// GrantedUsersInverseTable is the table name for the UserGrantedProviderAccount entity.
	// It exists in this package in order to avoid circular dependency with the "usergrantedprovideraccount" package.
	GrantedUsersInverseTable = "user_granted_provider_account"
	// GrantedUsersColumn is the table column denoting the granted_users relation/edge.
	GrantedUsersColumn = "provider_account_id"
)

// Columns holds all SQL columns for provideraccount fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldAccountUUID,
	FieldAccessToken,
	FieldRefreshToken,
	FieldCredentials,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ProviderAccount queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAccountUUID orders the results by the account_uuid field.
func ByAccountUUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountUUID, opts...).ToFunc()
}

// ByAccessToken orders the results by the access_token field.
func ByAccessToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccessToken, opts...).ToFunc()
}

// ByRefreshToken orders the results by the refresh_token field.
func ByRefreshToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefreshToken, opts...).ToFunc()
}

// ByCredentials orders the results by the credentials field.
func ByCredentials(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCredentials, opts...).ToFunc()
}

// ByFakeTokensCount orders the results by fake_tokens count.
func ByFakeTokensCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFakeTokensStep(), opts...)
	}
}

// ByFakeTokens orders the results by fake_tokens terms.
func ByFakeTokens(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFakeTokensStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByGrantedUsersCount orders the results by granted_users count.
func ByGrantedUsersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGrantedUsersStep(), opts...)
	}
}

// ByGrantedUsers orders the results by granted_users terms.
func ByGrantedUsers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGrantedUsersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newFakeTokensStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FakeTokensInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FakeTokensTable, FakeTokensColumn),
	)
}
func newGrantedUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GrantedUsersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, GrantedUsersTable, GrantedUsersColumn),
	)
}
