// Code generated by ent, DO NOT EDIT.

package faketoken

import (
	"cocoq/server/database/dbrt/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldEQ(FieldUserID, v))
}

// ProviderAccountID applies equality check predicate on the "provider_account_id" field. It's identical to ProviderAccountIDEQ.
func ProviderAccountID(v int64) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldEQ(FieldProviderAccountID, v))
}

// AccessToken applies equality check predicate on the "access_token" field. It's identical to AccessTokenEQ.
func AccessToken(v string) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldEQ(FieldAccessToken, v))
}

// RefreshToken applies equality check predicate on the "refresh_token" field. It's identical to RefreshTokenEQ.
func RefreshToken(v string) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldEQ(FieldRefreshToken, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldNotIn(FieldUserID, vs...))
}

// ProviderAccountIDEQ applies the EQ predicate on the "provider_account_id" field.
func ProviderAccountIDEQ(v int64) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldEQ(FieldProviderAccountID, v))
}

// ProviderAccountIDNEQ applies the NEQ predicate on the "provider_account_id" field.
func ProviderAccountIDNEQ(v int64) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldNEQ(FieldProviderAccountID, v))
}

// ProviderAccountIDIn applies the In predicate on the "provider_account_id" field.
func ProviderAccountIDIn(vs ...int64) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldIn(FieldProviderAccountID, vs...))
}

// ProviderAccountIDNotIn applies the NotIn predicate on the "provider_account_id" field.
func ProviderAccountIDNotIn(vs ...int64) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldNotIn(FieldProviderAccountID, vs...))
}

// AccessTokenEQ applies the EQ predicate on the "access_token" field.
func AccessTokenEQ(v string) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldEQ(FieldAccessToken, v))
}

// AccessTokenNEQ applies the NEQ predicate on the "access_token" field.
func AccessTokenNEQ(v string) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldNEQ(FieldAccessToken, v))
}

// AccessTokenIn applies the In predicate on the "access_token" field.
func AccessTokenIn(vs ...string) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldIn(FieldAccessToken, vs...))
}

// AccessTokenNotIn applies the NotIn predicate on the "access_token" field.
func AccessTokenNotIn(vs ...string) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldNotIn(FieldAccessToken, vs...))
}

// AccessTokenGT applies the GT predicate on the "access_token" field.
func AccessTokenGT(v string) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldGT(FieldAccessToken, v))
}

// AccessTokenGTE applies the GTE predicate on the "access_token" field.
func AccessTokenGTE(v string) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldGTE(FieldAccessToken, v))
}

// AccessTokenLT applies the LT predicate on the "access_token" field.
func AccessTokenLT(v string) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldLT(FieldAccessToken, v))
}

// AccessTokenLTE applies the LTE predicate on the "access_token" field.
func AccessTokenLTE(v string) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldLTE(FieldAccessToken, v))
}

// AccessTokenContains applies the Contains predicate on the "access_token" field.
func AccessTokenContains(v string) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldContains(FieldAccessToken, v))
}

// AccessTokenHasPrefix applies the HasPrefix predicate on the "access_token" field.
func AccessTokenHasPrefix(v string) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldHasPrefix(FieldAccessToken, v))
}

// AccessTokenHasSuffix applies the HasSuffix predicate on the "access_token" field.
func AccessTokenHasSuffix(v string) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldHasSuffix(FieldAccessToken, v))
}

// AccessTokenEqualFold applies the EqualFold predicate on the "access_token" field.
func AccessTokenEqualFold(v string) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldEqualFold(FieldAccessToken, v))
}

// AccessTokenContainsFold applies the ContainsFold predicate on the "access_token" field.
func AccessTokenContainsFold(v string) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldContainsFold(FieldAccessToken, v))
}

// RefreshTokenEQ applies the EQ predicate on the "refresh_token" field.
func RefreshTokenEQ(v string) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldEQ(FieldRefreshToken, v))
}

// RefreshTokenNEQ applies the NEQ predicate on the "refresh_token" field.
func RefreshTokenNEQ(v string) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldNEQ(FieldRefreshToken, v))
}

// RefreshTokenIn applies the In predicate on the "refresh_token" field.
func RefreshTokenIn(vs ...string) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldIn(FieldRefreshToken, vs...))
}

// RefreshTokenNotIn applies the NotIn predicate on the "refresh_token" field.
func RefreshTokenNotIn(vs ...string) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldNotIn(FieldRefreshToken, vs...))
}

// RefreshTokenGT applies the GT predicate on the "refresh_token" field.
func RefreshTokenGT(v string) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldGT(FieldRefreshToken, v))
}

// RefreshTokenGTE applies the GTE predicate on the "refresh_token" field.
func RefreshTokenGTE(v string) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldGTE(FieldRefreshToken, v))
}

// RefreshTokenLT applies the LT predicate on the "refresh_token" field.
func RefreshTokenLT(v string) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldLT(FieldRefreshToken, v))
}

// RefreshTokenLTE applies the LTE predicate on the "refresh_token" field.
func RefreshTokenLTE(v string) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldLTE(FieldRefreshToken, v))
}

// RefreshTokenContains applies the Contains predicate on the "refresh_token" field.
func RefreshTokenContains(v string) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldContains(FieldRefreshToken, v))
}

// RefreshTokenHasPrefix applies the HasPrefix predicate on the "refresh_token" field.
func RefreshTokenHasPrefix(v string) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldHasPrefix(FieldRefreshToken, v))
}

// RefreshTokenHasSuffix applies the HasSuffix predicate on the "refresh_token" field.
func RefreshTokenHasSuffix(v string) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldHasSuffix(FieldRefreshToken, v))
}

// RefreshTokenEqualFold applies the EqualFold predicate on the "refresh_token" field.
func RefreshTokenEqualFold(v string) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldEqualFold(FieldRefreshToken, v))
}

// RefreshTokenContainsFold applies the ContainsFold predicate on the "refresh_token" field.
func RefreshTokenContainsFold(v string) predicate.FakeToken {
	return predicate.FakeToken(sql.FieldContainsFold(FieldRefreshToken, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.FakeToken {
	return predicate.FakeToken(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.FakeToken {
	return predicate.FakeToken(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProviderAccount applies the HasEdge predicate on the "provider_account" edge.
func HasProviderAccount() predicate.FakeToken {
	return predicate.FakeToken(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProviderAccountTable, ProviderAccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProviderAccountWith applies the HasEdge predicate on the "provider_account" edge with a given conditions (other predicates).
func HasProviderAccountWith(preds ...predicate.ProviderAccount) predicate.FakeToken {
	return predicate.FakeToken(func(s *sql.Selector) {
		step := newProviderAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FakeToken) predicate.FakeToken {
	return predicate.FakeToken(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FakeToken) predicate.FakeToken {
	return predicate.FakeToken(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FakeToken) predicate.FakeToken {
	return predicate.FakeToken(sql.NotPredicates(p))
}
