// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// FakeTokenColumns holds the columns for the "fake_token" table.
	FakeTokenColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "access_token", Type: field.TypeString},
		{Name: "refresh_token", Type: field.TypeString},
		{Name: "provider_account_id", Type: field.TypeInt64},
		{Name: "user_id", Type: field.TypeInt64},
	}
	// FakeTokenTable holds the schema information for the "fake_token" table.
	FakeTokenTable = &schema.Table{
		Name:       "fake_token",
		Columns:    FakeTokenColumns,
		PrimaryKey: []*schema.Column{FakeTokenColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "fake_token_provider_account_fake_tokens",
				Columns:    []*schema.Column{FakeTokenColumns[3]},
				RefColumns: []*schema.Column{ProviderAccountColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "fake_token_user_fake_tokens",
				Columns:    []*schema.Column{FakeTokenColumns[4]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "faketoken_access_token",
				Unique:  false,
				Columns: []*schema.Column{FakeTokenColumns[1]},
			},
			{
				Name:    "faketoken_refresh_token",
				Unique:  false,
				Columns: []*schema.Column{FakeTokenColumns[2]},
			},
			{
				Name:    "faketoken_user_id_provider_account_id",
				Unique:  true,
				Columns: []*schema.Column{FakeTokenColumns[4], FakeTokenColumns[3]},
			},
		},
	}
	// ProviderAccountColumns holds the columns for the "provider_account" table.
	ProviderAccountColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "account_uuid", Type: field.TypeString, Unique: true},
		{Name: "access_token", Type: field.TypeString},
		{Name: "refresh_token", Type: field.TypeString},
		{Name: "credentials", Type: field.TypeString},
	}
	// ProviderAccountTable holds the schema information for the "provider_account" table.
	ProviderAccountTable = &schema.Table{
		Name:       "provider_account",
		Columns:    ProviderAccountColumns,
		PrimaryKey: []*schema.Column{ProviderAccountColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "provideraccount_access_token",
				Unique:  false,
				Columns: []*schema.Column{ProviderAccountColumns[4]},
			},
			{
				Name:    "provideraccount_refresh_token",
				Unique:  false,
				Columns: []*schema.Column{ProviderAccountColumns[5]},
			},
		},
	}
	// UserColumns holds the columns for the "user" table.
	UserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "oauth_state_token", Type: field.TypeString},
		{Name: "state", Type: field.TypeInt64},
	}
	// UserTable holds the schema information for the "user" table.
	UserTable = &schema.Table{
		Name:       "user",
		Columns:    UserColumns,
		PrimaryKey: []*schema.Column{UserColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_oauth_state_token",
				Unique:  false,
				Columns: []*schema.Column{UserColumns[3]},
			},
		},
	}
	// UserGrantedProviderAccountColumns holds the columns for the "user_granted_provider_account" table.
	UserGrantedProviderAccountColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "provider_account_id", Type: field.TypeInt64},
		{Name: "user_id", Type: field.TypeInt64},
	}
	// UserGrantedProviderAccountTable holds the schema information for the "user_granted_provider_account" table.
	UserGrantedProviderAccountTable = &schema.Table{
		Name:       "user_granted_provider_account",
		Columns:    UserGrantedProviderAccountColumns,
		PrimaryKey: []*schema.Column{UserGrantedProviderAccountColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_granted_provider_account_provider_account_granted_users",
				Columns:    []*schema.Column{UserGrantedProviderAccountColumns[1]},
				RefColumns: []*schema.Column{ProviderAccountColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_granted_provider_account_user_granted_provider_accounts",
				Columns:    []*schema.Column{UserGrantedProviderAccountColumns[2]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		FakeTokenTable,
		ProviderAccountTable,
		UserTable,
		UserGrantedProviderAccountTable,
	}
)

func init() {
	FakeTokenTable.ForeignKeys[0].RefTable = ProviderAccountTable
	FakeTokenTable.ForeignKeys[1].RefTable = UserTable
	FakeTokenTable.Annotation = &entsql.Annotation{
		Table: "fake_token",
	}
	ProviderAccountTable.Annotation = &entsql.Annotation{
		Table: "provider_account",
	}
	UserTable.Annotation = &entsql.Annotation{
		Table: "user",
	}
	UserGrantedProviderAccountTable.ForeignKeys[0].RefTable = ProviderAccountTable
	UserGrantedProviderAccountTable.ForeignKeys[1].RefTable = UserTable
	UserGrantedProviderAccountTable.Annotation = &entsql.Annotation{
		Table: "user_granted_provider_account",
	}
}
