// Code generated by ent, DO NOT EDIT.

package dbrt

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/realityone/cocoq/server/database/dbrt/anthropicusage"
)

// AnthropicUsageCreate is the builder for creating a AnthropicUsage entity.
type AnthropicUsageCreate struct {
	config
	mutation *AnthropicUsageMutation
	hooks    []Hook
}

// SetDeviceID sets the "device_id" field.
func (_c *AnthropicUsageCreate) SetDeviceID(v string) *AnthropicUsageCreate {
	_c.mutation.SetDeviceID(v)
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *AnthropicUsageCreate) SetSessionID(v string) *AnthropicUsageCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetAccountUUID sets the "account_uuid" field.
func (_c *AnthropicUsageCreate) SetAccountUUID(v string) *AnthropicUsageCreate {
	_c.mutation.SetAccountUUID(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *AnthropicUsageCreate) SetModel(v string) *AnthropicUsageCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *AnthropicUsageCreate) SetNillableModel(v *string) *AnthropicUsageCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetInputTokens sets the "input_tokens" field.
func (_c *AnthropicUsageCreate) SetInputTokens(v int64) *AnthropicUsageCreate {
	_c.mutation.SetInputTokens(v)
	return _c
}

// SetCacheReadInputTokens sets the "cache_read_input_tokens" field.
func (_c *AnthropicUsageCreate) SetCacheReadInputTokens(v int64) *AnthropicUsageCreate {
	_c.mutation.SetCacheReadInputTokens(v)
	return _c
}

// SetCacheCreationInputTokens sets the "cache_creation_input_tokens" field.
func (_c *AnthropicUsageCreate) SetCacheCreationInputTokens(v int64) *AnthropicUsageCreate {
	_c.mutation.SetCacheCreationInputTokens(v)
	return _c
}

// SetOutputTokens sets the "output_tokens" field.
func (_c *AnthropicUsageCreate) SetOutputTokens(v int64) *AnthropicUsageCreate {
	_c.mutation.SetOutputTokens(v)
	return _c
}

// SetCacheCreationEphemeral5mInputTokens sets the "cache_creation_ephemeral_5m_input_tokens" field.
func (_c *AnthropicUsageCreate) SetCacheCreationEphemeral5mInputTokens(v int64) *AnthropicUsageCreate {
	_c.mutation.SetCacheCreationEphemeral5mInputTokens(v)
	return _c
}

// SetCacheCreationEphemeral1hInputTokens sets the "cache_creation_ephemeral_1h_input_tokens" field.
func (_c *AnthropicUsageCreate) SetCacheCreationEphemeral1hInputTokens(v int64) *AnthropicUsageCreate {
	_c.mutation.SetCacheCreationEphemeral1hInputTokens(v)
	return _c
}

// SetCacheHitRate sets the "cache_hit_rate" field.
func (_c *AnthropicUsageCreate) SetCacheHitRate(v float64) *AnthropicUsageCreate {
	_c.mutation.SetCacheHitRate(v)
	return _c
}

// SetRaw sets the "raw" field.
func (_c *AnthropicUsageCreate) SetRaw(v string) *AnthropicUsageCreate {
	_c.mutation.SetRaw(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AnthropicUsageCreate) SetCreatedAt(v time.Time) *AnthropicUsageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AnthropicUsageCreate) SetNillableCreatedAt(v *time.Time) *AnthropicUsageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AnthropicUsageCreate) SetUpdatedAt(v time.Time) *AnthropicUsageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AnthropicUsageCreate) SetNillableUpdatedAt(v *time.Time) *AnthropicUsageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the AnthropicUsageMutation object of the builder.
func (_c *AnthropicUsageCreate) Mutation() *AnthropicUsageMutation {
	return _c.mutation
}

// Save creates the AnthropicUsage in the database.
func (_c *AnthropicUsageCreate) Save(ctx context.Context) (*AnthropicUsage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AnthropicUsageCreate) SaveX(ctx context.Context) *AnthropicUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnthropicUsageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnthropicUsageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AnthropicUsageCreate) defaults() {
	if _, ok := _c.mutation.Model(); !ok {
		v := anthropicusage.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := anthropicusage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := anthropicusage.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AnthropicUsageCreate) check() error {
	if _, ok := _c.mutation.DeviceID(); !ok {
		return &ValidationError{Name: "device_id", err: errors.New(`dbrt: missing required field "AnthropicUsage.device_id"`)}
	}
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`dbrt: missing required field "AnthropicUsage.session_id"`)}
	}
	if _, ok := _c.mutation.AccountUUID(); !ok {
		return &ValidationError{Name: "account_uuid", err: errors.New(`dbrt: missing required field "AnthropicUsage.account_uuid"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`dbrt: missing required field "AnthropicUsage.model"`)}
	}
	if _, ok := _c.mutation.InputTokens(); !ok {
		return &ValidationError{Name: "input_tokens", err: errors.New(`dbrt: missing required field "AnthropicUsage.input_tokens"`)}
	}
	if _, ok := _c.mutation.CacheReadInputTokens(); !ok {
		return &ValidationError{Name: "cache_read_input_tokens", err: errors.New(`dbrt: missing required field "AnthropicUsage.cache_read_input_tokens"`)}
	}
	if _, ok := _c.mutation.CacheCreationInputTokens(); !ok {
		return &ValidationError{Name: "cache_creation_input_tokens", err: errors.New(`dbrt: missing required field "AnthropicUsage.cache_creation_input_tokens"`)}
	}
	if _, ok := _c.mutation.OutputTokens(); !ok {
		return &ValidationError{Name: "output_tokens", err: errors.New(`dbrt: missing required field "AnthropicUsage.output_tokens"`)}
	}
	if _, ok := _c.mutation.CacheCreationEphemeral5mInputTokens(); !ok {
		return &ValidationError{Name: "cache_creation_ephemeral_5m_input_tokens", err: errors.New(`dbrt: missing required field "AnthropicUsage.cache_creation_ephemeral_5m_input_tokens"`)}
	}
	if _, ok := _c.mutation.CacheCreationEphemeral1hInputTokens(); !ok {
		return &ValidationError{Name: "cache_creation_ephemeral_1h_input_tokens", err: errors.New(`dbrt: missing required field "AnthropicUsage.cache_creation_ephemeral_1h_input_tokens"`)}
	}
	if _, ok := _c.mutation.CacheHitRate(); !ok {
		return &ValidationError{Name: "cache_hit_rate", err: errors.New(`dbrt: missing required field "AnthropicUsage.cache_hit_rate"`)}
	}
	if _, ok := _c.mutation.Raw(); !ok {
		return &ValidationError{Name: "raw", err: errors.New(`dbrt: missing required field "AnthropicUsage.raw"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`dbrt: missing required field "AnthropicUsage.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`dbrt: missing required field "AnthropicUsage.updated_at"`)}
	}
	return nil
}

func (_c *AnthropicUsageCreate) sqlSave(ctx context.Context) (*AnthropicUsage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AnthropicUsageCreate) createSpec() (*AnthropicUsage, *sqlgraph.CreateSpec) {
	var (
		_node = &AnthropicUsage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(anthropicusage.Table, sqlgraph.NewFieldSpec(anthropicusage.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.DeviceID(); ok {
		_spec.SetField(anthropicusage.FieldDeviceID, field.TypeString, value)
		_node.DeviceID = value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(anthropicusage.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.AccountUUID(); ok {
		_spec.SetField(anthropicusage.FieldAccountUUID, field.TypeString, value)
		_node.AccountUUID = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(anthropicusage.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.InputTokens(); ok {
		_spec.SetField(anthropicusage.FieldInputTokens, field.TypeInt64, value)
		_node.InputTokens = value
	}
	if value, ok := _c.mutation.CacheReadInputTokens(); ok {
		_spec.SetField(anthropicusage.FieldCacheReadInputTokens, field.TypeInt64, value)
		_node.CacheReadInputTokens = value
	}
	if value, ok := _c.mutation.CacheCreationInputTokens(); ok {
		_spec.SetField(anthropicusage.FieldCacheCreationInputTokens, field.TypeInt64, value)
		_node.CacheCreationInputTokens = value
	}
	if value, ok := _c.mutation.OutputTokens(); ok {
		_spec.SetField(anthropicusage.FieldOutputTokens, field.TypeInt64, value)
		_node.OutputTokens = value
	}
	if value, ok := _c.mutation.CacheCreationEphemeral5mInputTokens(); ok {
		_spec.SetField(anthropicusage.FieldCacheCreationEphemeral5mInputTokens, field.TypeInt64, value)
		_node.CacheCreationEphemeral5mInputTokens = value
	}
	if value, ok := _c.mutation.CacheCreationEphemeral1hInputTokens(); ok {
		_spec.SetField(anthropicusage.FieldCacheCreationEphemeral1hInputTokens, field.TypeInt64, value)
		_node.CacheCreationEphemeral1hInputTokens = value
	}
	if value, ok := _c.mutation.CacheHitRate(); ok {
		_spec.SetField(anthropicusage.FieldCacheHitRate, field.TypeFloat64, value)
		_node.CacheHitRate = value
	}
	if value, ok := _c.mutation.Raw(); ok {
		_spec.SetField(anthropicusage.FieldRaw, field.TypeString, value)
		_node.Raw = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(anthropicusage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(anthropicusage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// AnthropicUsageCreateBulk is the builder for creating many AnthropicUsage entities in bulk.
type AnthropicUsageCreateBulk struct {
	config
	err      error
	builders []*AnthropicUsageCreate
}

// Save creates the AnthropicUsage entities in the database.
func (_c *AnthropicUsageCreateBulk) Save(ctx context.Context) ([]*AnthropicUsage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AnthropicUsage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AnthropicUsageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AnthropicUsageCreateBulk) SaveX(ctx context.Context) []*AnthropicUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnthropicUsageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnthropicUsageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
