// Code generated by ent, DO NOT EDIT.

package dbrt

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/realityone/cocoq/server/database/dbrt/anthropicusage"
	"github.com/realityone/cocoq/server/database/dbrt/predicate"
)

// AnthropicUsageUpdate is the builder for updating AnthropicUsage entities.
type AnthropicUsageUpdate struct {
	config
	hooks    []Hook
	mutation *AnthropicUsageMutation
}

// Where appends a list predicates to the AnthropicUsageUpdate builder.
func (_u *AnthropicUsageUpdate) Where(ps ...predicate.AnthropicUsage) *AnthropicUsageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *AnthropicUsageUpdate) SetDeviceID(v string) *AnthropicUsageUpdate {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *AnthropicUsageUpdate) SetNillableDeviceID(v *string) *AnthropicUsageUpdate {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *AnthropicUsageUpdate) SetSessionID(v string) *AnthropicUsageUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *AnthropicUsageUpdate) SetNillableSessionID(v *string) *AnthropicUsageUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetAccountUUID sets the "account_uuid" field.
func (_u *AnthropicUsageUpdate) SetAccountUUID(v string) *AnthropicUsageUpdate {
	_u.mutation.SetAccountUUID(v)
	return _u
}

// SetNillableAccountUUID sets the "account_uuid" field if the given value is not nil.
func (_u *AnthropicUsageUpdate) SetNillableAccountUUID(v *string) *AnthropicUsageUpdate {
	if v != nil {
		_u.SetAccountUUID(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *AnthropicUsageUpdate) SetModel(v string) *AnthropicUsageUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *AnthropicUsageUpdate) SetNillableModel(v *string) *AnthropicUsageUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *AnthropicUsageUpdate) SetInputTokens(v int64) *AnthropicUsageUpdate {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *AnthropicUsageUpdate) SetNillableInputTokens(v *int64) *AnthropicUsageUpdate {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *AnthropicUsageUpdate) AddInputTokens(v int64) *AnthropicUsageUpdate {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetCacheReadInputTokens sets the "cache_read_input_tokens" field.
func (_u *AnthropicUsageUpdate) SetCacheReadInputTokens(v int64) *AnthropicUsageUpdate {
	_u.mutation.ResetCacheReadInputTokens()
	_u.mutation.SetCacheReadInputTokens(v)
	return _u
}

// SetNillableCacheReadInputTokens sets the "cache_read_input_tokens" field if the given value is not nil.
func (_u *AnthropicUsageUpdate) SetNillableCacheReadInputTokens(v *int64) *AnthropicUsageUpdate {
	if v != nil {
		_u.SetCacheReadInputTokens(*v)
	}
	return _u
}

// AddCacheReadInputTokens adds value to the "cache_read_input_tokens" field.
func (_u *AnthropicUsageUpdate) AddCacheReadInputTokens(v int64) *AnthropicUsageUpdate {
	_u.mutation.AddCacheReadInputTokens(v)
	return _u
}

// SetCacheCreationInputTokens sets the "cache_creation_input_tokens" field.
func (_u *AnthropicUsageUpdate) SetCacheCreationInputTokens(v int64) *AnthropicUsageUpdate {
	_u.mutation.ResetCacheCreationInputTokens()
	_u.mutation.SetCacheCreationInputTokens(v)
	return _u
}

// SetNillableCacheCreationInputTokens sets the "cache_creation_input_tokens" field if the given value is not nil.
func (_u *AnthropicUsageUpdate) SetNillableCacheCreationInputTokens(v *int64) *AnthropicUsageUpdate {
	if v != nil {
		_u.SetCacheCreationInputTokens(*v)
	}
	return _u
}

// AddCacheCreationInputTokens adds value to the "cache_creation_input_tokens" field.
func (_u *AnthropicUsageUpdate) AddCacheCreationInputTokens(v int64) *AnthropicUsageUpdate {
	_u.mutation.AddCacheCreationInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *AnthropicUsageUpdate) SetOutputTokens(v int64) *AnthropicUsageUpdate {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *AnthropicUsageUpdate) SetNillableOutputTokens(v *int64) *AnthropicUsageUpdate {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *AnthropicUsageUpdate) AddOutputTokens(v int64) *AnthropicUsageUpdate {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetCacheCreationEphemeral5mInputTokens sets the "cache_creation_ephemeral_5m_input_tokens" field.
func (_u *AnthropicUsageUpdate) SetCacheCreationEphemeral5mInputTokens(v int64) *AnthropicUsageUpdate {
	_u.mutation.ResetCacheCreationEphemeral5mInputTokens()
	_u.mutation.SetCacheCreationEphemeral5mInputTokens(v)
	return _u
}

// SetNillableCacheCreationEphemeral5mInputTokens sets the "cache_creation_ephemeral_5m_input_tokens" field if the given value is not nil.
func (_u *AnthropicUsageUpdate) SetNillableCacheCreationEphemeral5mInputTokens(v *int64) *AnthropicUsageUpdate {
	if v != nil {
		_u.SetCacheCreationEphemeral5mInputTokens(*v)
	}
	return _u
}

// AddCacheCreationEphemeral5mInputTokens adds value to the "cache_creation_ephemeral_5m_input_tokens" field.
func (_u *AnthropicUsageUpdate) AddCacheCreationEphemeral5mInputTokens(v int64) *AnthropicUsageUpdate {
	_u.mutation.AddCacheCreationEphemeral5mInputTokens(v)
	return _u
}

// SetCacheCreationEphemeral1hInputTokens sets the "cache_creation_ephemeral_1h_input_tokens" field.
func (_u *AnthropicUsageUpdate) SetCacheCreationEphemeral1hInputTokens(v int64) *AnthropicUsageUpdate {
	_u.mutation.ResetCacheCreationEphemeral1hInputTokens()
	_u.mutation.SetCacheCreationEphemeral1hInputTokens(v)
	return _u
}

// SetNillableCacheCreationEphemeral1hInputTokens sets the "cache_creation_ephemeral_1h_input_tokens" field if the given value is not nil.
func (_u *AnthropicUsageUpdate) SetNillableCacheCreationEphemeral1hInputTokens(v *int64) *AnthropicUsageUpdate {
	if v != nil {
		_u.SetCacheCreationEphemeral1hInputTokens(*v)
	}
	return _u
}

// AddCacheCreationEphemeral1hInputTokens adds value to the "cache_creation_ephemeral_1h_input_tokens" field.
func (_u *AnthropicUsageUpdate) AddCacheCreationEphemeral1hInputTokens(v int64) *AnthropicUsageUpdate {
	_u.mutation.AddCacheCreationEphemeral1hInputTokens(v)
	return _u
}

// SetCacheHitRate sets the "cache_hit_rate" field.
func (_u *AnthropicUsageUpdate) SetCacheHitRate(v float64) *AnthropicUsageUpdate {
	_u.mutation.ResetCacheHitRate()
	_u.mutation.SetCacheHitRate(v)
	return _u
}

// SetNillableCacheHitRate sets the "cache_hit_rate" field if the given value is not nil.
func (_u *AnthropicUsageUpdate) SetNillableCacheHitRate(v *float64) *AnthropicUsageUpdate {
	if v != nil {
		_u.SetCacheHitRate(*v)
	}
	return _u
}

// AddCacheHitRate adds value to the "cache_hit_rate" field.
func (_u *AnthropicUsageUpdate) AddCacheHitRate(v float64) *AnthropicUsageUpdate {
	_u.mutation.AddCacheHitRate(v)
	return _u
}

// SetRaw sets the "raw" field.
func (_u *AnthropicUsageUpdate) SetRaw(v string) *AnthropicUsageUpdate {
	_u.mutation.SetRaw(v)
	return _u
}

// SetNillableRaw sets the "raw" field if the given value is not nil.
func (_u *AnthropicUsageUpdate) SetNillableRaw(v *string) *AnthropicUsageUpdate {
	if v != nil {
		_u.SetRaw(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AnthropicUsageUpdate) SetUpdatedAt(v time.Time) *AnthropicUsageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AnthropicUsageMutation object of the builder.
func (_u *AnthropicUsageUpdate) Mutation() *AnthropicUsageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AnthropicUsageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnthropicUsageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AnthropicUsageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnthropicUsageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AnthropicUsageUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := anthropicusage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AnthropicUsageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(anthropicusage.Table, anthropicusage.Columns, sqlgraph.NewFieldSpec(anthropicusage.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(anthropicusage.FieldDeviceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(anthropicusage.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountUUID(); ok {
		_spec.SetField(anthropicusage.FieldAccountUUID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(anthropicusage.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(anthropicusage.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(anthropicusage.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheReadInputTokens(); ok {
		_spec.SetField(anthropicusage.FieldCacheReadInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadInputTokens(); ok {
		_spec.AddField(anthropicusage.FieldCacheReadInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheCreationInputTokens(); ok {
		_spec.SetField(anthropicusage.FieldCacheCreationInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheCreationInputTokens(); ok {
		_spec.AddField(anthropicusage.FieldCacheCreationInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(anthropicusage.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(anthropicusage.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheCreationEphemeral5mInputTokens(); ok {
		_spec.SetField(anthropicusage.FieldCacheCreationEphemeral5mInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheCreationEphemeral5mInputTokens(); ok {
		_spec.AddField(anthropicusage.FieldCacheCreationEphemeral5mInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheCreationEphemeral1hInputTokens(); ok {
		_spec.SetField(anthropicusage.FieldCacheCreationEphemeral1hInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheCreationEphemeral1hInputTokens(); ok {
		_spec.AddField(anthropicusage.FieldCacheCreationEphemeral1hInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheHitRate(); ok {
		_spec.SetField(anthropicusage.FieldCacheHitRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheHitRate(); ok {
		_spec.AddField(anthropicusage.FieldCacheHitRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Raw(); ok {
		_spec.SetField(anthropicusage.FieldRaw, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(anthropicusage.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{anthropicusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AnthropicUsageUpdateOne is the builder for updating a single AnthropicUsage entity.
type AnthropicUsageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AnthropicUsageMutation
}

// SetDeviceID sets the "device_id" field.
func (_u *AnthropicUsageUpdateOne) SetDeviceID(v string) *AnthropicUsageUpdateOne {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *AnthropicUsageUpdateOne) SetNillableDeviceID(v *string) *AnthropicUsageUpdateOne {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *AnthropicUsageUpdateOne) SetSessionID(v string) *AnthropicUsageUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *AnthropicUsageUpdateOne) SetNillableSessionID(v *string) *AnthropicUsageUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetAccountUUID sets the "account_uuid" field.
func (_u *AnthropicUsageUpdateOne) SetAccountUUID(v string) *AnthropicUsageUpdateOne {
	_u.mutation.SetAccountUUID(v)
	return _u
}

// SetNillableAccountUUID sets the "account_uuid" field if the given value is not nil.
func (_u *AnthropicUsageUpdateOne) SetNillableAccountUUID(v *string) *AnthropicUsageUpdateOne {
	if v != nil {
		_u.SetAccountUUID(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *AnthropicUsageUpdateOne) SetModel(v string) *AnthropicUsageUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *AnthropicUsageUpdateOne) SetNillableModel(v *string) *AnthropicUsageUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *AnthropicUsageUpdateOne) SetInputTokens(v int64) *AnthropicUsageUpdateOne {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *AnthropicUsageUpdateOne) SetNillableInputTokens(v *int64) *AnthropicUsageUpdateOne {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *AnthropicUsageUpdateOne) AddInputTokens(v int64) *AnthropicUsageUpdateOne {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetCacheReadInputTokens sets the "cache_read_input_tokens" field.
func (_u *AnthropicUsageUpdateOne) SetCacheReadInputTokens(v int64) *AnthropicUsageUpdateOne {
	_u.mutation.ResetCacheReadInputTokens()
	_u.mutation.SetCacheReadInputTokens(v)
	return _u
}

// SetNillableCacheReadInputTokens sets the "cache_read_input_tokens" field if the given value is not nil.
func (_u *AnthropicUsageUpdateOne) SetNillableCacheReadInputTokens(v *int64) *AnthropicUsageUpdateOne {
	if v != nil {
		_u.SetCacheReadInputTokens(*v)
	}
	return _u
}

// AddCacheReadInputTokens adds value to the "cache_read_input_tokens" field.
func (_u *AnthropicUsageUpdateOne) AddCacheReadInputTokens(v int64) *AnthropicUsageUpdateOne {
	_u.mutation.AddCacheReadInputTokens(v)
	return _u
}

// SetCacheCreationInputTokens sets the "cache_creation_input_tokens" field.
func (_u *AnthropicUsageUpdateOne) SetCacheCreationInputTokens(v int64) *AnthropicUsageUpdateOne {
	_u.mutation.ResetCacheCreationInputTokens()
	_u.mutation.SetCacheCreationInputTokens(v)
	return _u
}

// SetNillableCacheCreationInputTokens sets the "cache_creation_input_tokens" field if the given value is not nil.
func (_u *AnthropicUsageUpdateOne) SetNillableCacheCreationInputTokens(v *int64) *AnthropicUsageUpdateOne {
	if v != nil {
		_u.SetCacheCreationInputTokens(*v)
	}
	return _u
}

// AddCacheCreationInputTokens adds value to the "cache_creation_input_tokens" field.
func (_u *AnthropicUsageUpdateOne) AddCacheCreationInputTokens(v int64) *AnthropicUsageUpdateOne {
	_u.mutation.AddCacheCreationInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *AnthropicUsageUpdateOne) SetOutputTokens(v int64) *AnthropicUsageUpdateOne {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *AnthropicUsageUpdateOne) SetNillableOutputTokens(v *int64) *AnthropicUsageUpdateOne {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *AnthropicUsageUpdateOne) AddOutputTokens(v int64) *AnthropicUsageUpdateOne {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetCacheCreationEphemeral5mInputTokens sets the "cache_creation_ephemeral_5m_input_tokens" field.
func (_u *AnthropicUsageUpdateOne) SetCacheCreationEphemeral5mInputTokens(v int64) *AnthropicUsageUpdateOne {
	_u.mutation.ResetCacheCreationEphemeral5mInputTokens()
	_u.mutation.SetCacheCreationEphemeral5mInputTokens(v)
	return _u
}

// SetNillableCacheCreationEphemeral5mInputTokens sets the "cache_creation_ephemeral_5m_input_tokens" field if the given value is not nil.
func (_u *AnthropicUsageUpdateOne) SetNillableCacheCreationEphemeral5mInputTokens(v *int64) *AnthropicUsageUpdateOne {
	if v != nil {
		_u.SetCacheCreationEphemeral5mInputTokens(*v)
	}
	return _u
}

// AddCacheCreationEphemeral5mInputTokens adds value to the "cache_creation_ephemeral_5m_input_tokens" field.
func (_u *AnthropicUsageUpdateOne) AddCacheCreationEphemeral5mInputTokens(v int64) *AnthropicUsageUpdateOne {
	_u.mutation.AddCacheCreationEphemeral5mInputTokens(v)
	return _u
}

// SetCacheCreationEphemeral1hInputTokens sets the "cache_creation_ephemeral_1h_input_tokens" field.
func (_u *AnthropicUsageUpdateOne) SetCacheCreationEphemeral1hInputTokens(v int64) *AnthropicUsageUpdateOne {
	_u.mutation.ResetCacheCreationEphemeral1hInputTokens()
	_u.mutation.SetCacheCreationEphemeral1hInputTokens(v)
	return _u
}

// SetNillableCacheCreationEphemeral1hInputTokens sets the "cache_creation_ephemeral_1h_input_tokens" field if the given value is not nil.
func (_u *AnthropicUsageUpdateOne) SetNillableCacheCreationEphemeral1hInputTokens(v *int64) *AnthropicUsageUpdateOne {
	if v != nil {
		_u.SetCacheCreationEphemeral1hInputTokens(*v)
	}
	return _u
}

// AddCacheCreationEphemeral1hInputTokens adds value to the "cache_creation_ephemeral_1h_input_tokens" field.
func (_u *AnthropicUsageUpdateOne) AddCacheCreationEphemeral1hInputTokens(v int64) *AnthropicUsageUpdateOne {
	_u.mutation.AddCacheCreationEphemeral1hInputTokens(v)
	return _u
}

// SetCacheHitRate sets the "cache_hit_rate" field.
func (_u *AnthropicUsageUpdateOne) SetCacheHitRate(v float64) *AnthropicUsageUpdateOne {
	_u.mutation.ResetCacheHitRate()
	_u.mutation.SetCacheHitRate(v)
	return _u
}

// SetNillableCacheHitRate sets the "cache_hit_rate" field if the given value is not nil.
func (_u *AnthropicUsageUpdateOne) SetNillableCacheHitRate(v *float64) *AnthropicUsageUpdateOne {
	if v != nil {
		_u.SetCacheHitRate(*v)
	}
	return _u
}

// AddCacheHitRate adds value to the "cache_hit_rate" field.
func (_u *AnthropicUsageUpdateOne) AddCacheHitRate(v float64) *AnthropicUsageUpdateOne {
	_u.mutation.AddCacheHitRate(v)
	return _u
}

// SetRaw sets the "raw" field.
func (_u *AnthropicUsageUpdateOne) SetRaw(v string) *AnthropicUsageUpdateOne {
	_u.mutation.SetRaw(v)
	return _u
}

// SetNillableRaw sets the "raw" field if the given value is not nil.
func (_u *AnthropicUsageUpdateOne) SetNillableRaw(v *string) *AnthropicUsageUpdateOne {
	if v != nil {
		_u.SetRaw(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AnthropicUsageUpdateOne) SetUpdatedAt(v time.Time) *AnthropicUsageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AnthropicUsageMutation object of the builder.
func (_u *AnthropicUsageUpdateOne) Mutation() *AnthropicUsageMutation {
	return _u.mutation
}

// Where appends a list predicates to the AnthropicUsageUpdate builder.
func (_u *AnthropicUsageUpdateOne) Where(ps ...predicate.AnthropicUsage) *AnthropicUsageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AnthropicUsageUpdateOne) Select(field string, fields ...string) *AnthropicUsageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AnthropicUsage entity.
func (_u *AnthropicUsageUpdateOne) Save(ctx context.Context) (*AnthropicUsage, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnthropicUsageUpdateOne) SaveX(ctx context.Context) *AnthropicUsage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AnthropicUsageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnthropicUsageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AnthropicUsageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := anthropicusage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AnthropicUsageUpdateOne) sqlSave(ctx context.Context) (_node *AnthropicUsage, err error) {
	_spec := sqlgraph.NewUpdateSpec(anthropicusage.Table, anthropicusage.Columns, sqlgraph.NewFieldSpec(anthropicusage.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`dbrt: missing "AnthropicUsage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, anthropicusage.FieldID)
		for _, f := range fields {
			if !anthropicusage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("dbrt: invalid field %q for query", f)}
			}
			if f != anthropicusage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(anthropicusage.FieldDeviceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(anthropicusage.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountUUID(); ok {
		_spec.SetField(anthropicusage.FieldAccountUUID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(anthropicusage.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(anthropicusage.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(anthropicusage.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheReadInputTokens(); ok {
		_spec.SetField(anthropicusage.FieldCacheReadInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadInputTokens(); ok {
		_spec.AddField(anthropicusage.FieldCacheReadInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheCreationInputTokens(); ok {
		_spec.SetField(anthropicusage.FieldCacheCreationInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheCreationInputTokens(); ok {
		_spec.AddField(anthropicusage.FieldCacheCreationInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(anthropicusage.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(anthropicusage.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheCreationEphemeral5mInputTokens(); ok {
		_spec.SetField(anthropicusage.FieldCacheCreationEphemeral5mInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheCreationEphemeral5mInputTokens(); ok {
		_spec.AddField(anthropicusage.FieldCacheCreationEphemeral5mInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheCreationEphemeral1hInputTokens(); ok {
		_spec.SetField(anthropicusage.FieldCacheCreationEphemeral1hInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheCreationEphemeral1hInputTokens(); ok {
		_spec.AddField(anthropicusage.FieldCacheCreationEphemeral1hInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheHitRate(); ok {
		_spec.SetField(anthropicusage.FieldCacheHitRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheHitRate(); ok {
		_spec.AddField(anthropicusage.FieldCacheHitRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Raw(); ok {
		_spec.SetField(anthropicusage.FieldRaw, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(anthropicusage.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &AnthropicUsage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{anthropicusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
