// Code generated by ent, DO NOT EDIT.

package dbrt

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/realityone/cocoq/server/database/dbrt/anthropicusage"
)

// AnthropicUsage is the model entity for the AnthropicUsage schema.
type AnthropicUsage struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// DeviceID holds the value of the "device_id" field.
	DeviceID string `json:"device_id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID string `json:"session_id,omitempty"`
	// AccountUUID holds the value of the "account_uuid" field.
	AccountUUID string `json:"account_uuid,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// InputTokens holds the value of the "input_tokens" field.
	InputTokens int64 `json:"input_tokens,omitempty"`
	// CacheReadInputTokens holds the value of the "cache_read_input_tokens" field.
	CacheReadInputTokens int64 `json:"cache_read_input_tokens,omitempty"`
	// CacheCreationInputTokens holds the value of the "cache_creation_input_tokens" field.
	CacheCreationInputTokens int64 `json:"cache_creation_input_tokens,omitempty"`
	// OutputTokens holds the value of the "output_tokens" field.
	OutputTokens int64 `json:"output_tokens,omitempty"`
	// CacheCreationEphemeral5mInputTokens holds the value of the "cache_creation_ephemeral_5m_input_tokens" field.
	CacheCreationEphemeral5mInputTokens int64 `json:"cache_creation_ephemeral_5m_input_tokens,omitempty"`
	// CacheCreationEphemeral1hInputTokens holds the value of the "cache_creation_ephemeral_1h_input_tokens" field.
	CacheCreationEphemeral1hInputTokens int64 `json:"cache_creation_ephemeral_1h_input_tokens,omitempty"`
	// CacheHitRate holds the value of the "cache_hit_rate" field.
	CacheHitRate float64 `json:"cache_hit_rate,omitempty"`
	// Raw holds the value of the "raw" field.
	Raw string `json:"raw,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AnthropicUsage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case anthropicusage.FieldCacheHitRate:
			values[i] = new(sql.NullFloat64)
		case anthropicusage.FieldID, anthropicusage.FieldInputTokens, anthropicusage.FieldCacheReadInputTokens, anthropicusage.FieldCacheCreationInputTokens, anthropicusage.FieldOutputTokens, anthropicusage.FieldCacheCreationEphemeral5mInputTokens, anthropicusage.FieldCacheCreationEphemeral1hInputTokens:
			values[i] = new(sql.NullInt64)
		case anthropicusage.FieldDeviceID, anthropicusage.FieldSessionID, anthropicusage.FieldAccountUUID, anthropicusage.FieldModel, anthropicusage.FieldRaw:
			values[i] = new(sql.NullString)
		case anthropicusage.FieldCreatedAt, anthropicusage.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AnthropicUsage fields.
func (_m *AnthropicUsage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case anthropicusage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case anthropicusage.FieldDeviceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device_id", values[i])
			} else if value.Valid {
				_m.DeviceID = value.String
			}
		case anthropicusage.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		case anthropicusage.FieldAccountUUID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_uuid", values[i])
			} else if value.Valid {
				_m.AccountUUID = value.String
			}
		case anthropicusage.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case anthropicusage.FieldInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_tokens", values[i])
			} else if value.Valid {
				_m.InputTokens = value.Int64
			}
		case anthropicusage.FieldCacheReadInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_read_input_tokens", values[i])
			} else if value.Valid {
				_m.CacheReadInputTokens = value.Int64
			}
		case anthropicusage.FieldCacheCreationInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_creation_input_tokens", values[i])
			} else if value.Valid {
				_m.CacheCreationInputTokens = value.Int64
			}
		case anthropicusage.FieldOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_tokens", values[i])
			} else if value.Valid {
				_m.OutputTokens = value.Int64
			}
		case anthropicusage.FieldCacheCreationEphemeral5mInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_creation_ephemeral_5m_input_tokens", values[i])
			} else if value.Valid {
				_m.CacheCreationEphemeral5mInputTokens = value.Int64
			}
		case anthropicusage.FieldCacheCreationEphemeral1hInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_creation_ephemeral_1h_input_tokens", values[i])
			} else if value.Valid {
				_m.CacheCreationEphemeral1hInputTokens = value.Int64
			}
		case anthropicusage.FieldCacheHitRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_hit_rate", values[i])
			} else if value.Valid {
				_m.CacheHitRate = value.Float64
			}
		case anthropicusage.FieldRaw:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field raw", values[i])
			} else if value.Valid {
				_m.Raw = value.String
			}
		case anthropicusage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case anthropicusage.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AnthropicUsage.
// This includes values selected through modifiers, order, etc.
func (_m *AnthropicUsage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AnthropicUsage.
// Note that you need to call AnthropicUsage.Unwrap() before calling this method if this AnthropicUsage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AnthropicUsage) Update() *AnthropicUsageUpdateOne {
	return NewAnthropicUsageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AnthropicUsage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AnthropicUsage) Unwrap() *AnthropicUsage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("dbrt: AnthropicUsage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AnthropicUsage) String() string {
	var builder strings.Builder
	builder.WriteString("AnthropicUsage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("device_id=")
	builder.WriteString(_m.DeviceID)
	builder.WriteString(", ")
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteString(", ")
	builder.WriteString("account_uuid=")
	builder.WriteString(_m.AccountUUID)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_read_input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheReadInputTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_creation_input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheCreationInputTokens))
	builder.WriteString(", ")
	builder.WriteString("output_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_creation_ephemeral_5m_input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheCreationEphemeral5mInputTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_creation_ephemeral_1h_input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheCreationEphemeral1hInputTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_hit_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheHitRate))
	builder.WriteString(", ")
	builder.WriteString("raw=")
	builder.WriteString(_m.Raw)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AnthropicUsages is a parsable slice of AnthropicUsage.
type AnthropicUsages []*AnthropicUsage
