// Code generated by ent, DO NOT EDIT.

package dbrt

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/realityone/cocoq/server/database/dbrt/anthropicusage"
	"github.com/realityone/cocoq/server/database/dbrt/predicate"
)

// AnthropicUsageDelete is the builder for deleting a AnthropicUsage entity.
type AnthropicUsageDelete struct {
	config
	hooks    []Hook
	mutation *AnthropicUsageMutation
}

// Where appends a list predicates to the AnthropicUsageDelete builder.
func (_d *AnthropicUsageDelete) Where(ps ...predicate.AnthropicUsage) *AnthropicUsageDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AnthropicUsageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AnthropicUsageDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AnthropicUsageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(anthropicusage.Table, sqlgraph.NewFieldSpec(anthropicusage.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AnthropicUsageDeleteOne is the builder for deleting a single AnthropicUsage entity.
type AnthropicUsageDeleteOne struct {
	_d *AnthropicUsageDelete
}

// Where appends a list predicates to the AnthropicUsageDelete builder.
func (_d *AnthropicUsageDeleteOne) Where(ps ...predicate.AnthropicUsage) *AnthropicUsageDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AnthropicUsageDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{anthropicusage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AnthropicUsageDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
