// Code generated by ent, DO NOT EDIT.

package dbrt

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"cocoq/server/database/dbrt/migrate"

	"cocoq/server/database/dbrt/faketoken"
	"cocoq/server/database/dbrt/provideraccount"
	"cocoq/server/database/dbrt/user"
	"cocoq/server/database/dbrt/usergrantedprovideraccount"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// FakeToken is the client for interacting with the FakeToken builders.
	FakeToken *FakeTokenClient
	// ProviderAccount is the client for interacting with the ProviderAccount builders.
	ProviderAccount *ProviderAccountClient
	// User is the client for interacting with the User builders.
	User *UserClient
	// UserGrantedProviderAccount is the client for interacting with the UserGrantedProviderAccount builders.
	UserGrantedProviderAccount *UserGrantedProviderAccountClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.FakeToken = NewFakeTokenClient(c.config)
	c.ProviderAccount = NewProviderAccountClient(c.config)
	c.User = NewUserClient(c.config)
	c.UserGrantedProviderAccount = NewUserGrantedProviderAccountClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("dbrt: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("dbrt: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                        ctx,
		config:                     cfg,
		FakeToken:                  NewFakeTokenClient(cfg),
		ProviderAccount:            NewProviderAccountClient(cfg),
		User:                       NewUserClient(cfg),
		UserGrantedProviderAccount: NewUserGrantedProviderAccountClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                        ctx,
		config:                     cfg,
		FakeToken:                  NewFakeTokenClient(cfg),
		ProviderAccount:            NewProviderAccountClient(cfg),
		User:                       NewUserClient(cfg),
		UserGrantedProviderAccount: NewUserGrantedProviderAccountClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		FakeToken.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.FakeToken.Use(hooks...)
	c.ProviderAccount.Use(hooks...)
	c.User.Use(hooks...)
	c.UserGrantedProviderAccount.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.FakeToken.Intercept(interceptors...)
	c.ProviderAccount.Intercept(interceptors...)
	c.User.Intercept(interceptors...)
	c.UserGrantedProviderAccount.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *FakeTokenMutation:
		return c.FakeToken.mutate(ctx, m)
	case *ProviderAccountMutation:
		return c.ProviderAccount.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	case *UserGrantedProviderAccountMutation:
		return c.UserGrantedProviderAccount.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("dbrt: unknown mutation type %T", m)
	}
}

// FakeTokenClient is a client for the FakeToken schema.
type FakeTokenClient struct {
	config
}

// NewFakeTokenClient returns a client for the FakeToken from the given config.
func NewFakeTokenClient(c config) *FakeTokenClient {
	return &FakeTokenClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `faketoken.Hooks(f(g(h())))`.
func (c *FakeTokenClient) Use(hooks ...Hook) {
	c.hooks.FakeToken = append(c.hooks.FakeToken, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `faketoken.Intercept(f(g(h())))`.
func (c *FakeTokenClient) Intercept(interceptors ...Interceptor) {
	c.inters.FakeToken = append(c.inters.FakeToken, interceptors...)
}

// Create returns a builder for creating a FakeToken entity.
func (c *FakeTokenClient) Create() *FakeTokenCreate {
	mutation := newFakeTokenMutation(c.config, OpCreate)
	return &FakeTokenCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of FakeToken entities.
func (c *FakeTokenClient) CreateBulk(builders ...*FakeTokenCreate) *FakeTokenCreateBulk {
	return &FakeTokenCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FakeTokenClient) MapCreateBulk(slice any, setFunc func(*FakeTokenCreate, int)) *FakeTokenCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FakeTokenCreateBulk{err: fmt.Errorf("calling to FakeTokenClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FakeTokenCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FakeTokenCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for FakeToken.
func (c *FakeTokenClient) Update() *FakeTokenUpdate {
	mutation := newFakeTokenMutation(c.config, OpUpdate)
	return &FakeTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FakeTokenClient) UpdateOne(ft *FakeToken) *FakeTokenUpdateOne {
	mutation := newFakeTokenMutation(c.config, OpUpdateOne, withFakeToken(ft))
	return &FakeTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FakeTokenClient) UpdateOneID(id int64) *FakeTokenUpdateOne {
	mutation := newFakeTokenMutation(c.config, OpUpdateOne, withFakeTokenID(id))
	return &FakeTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for FakeToken.
func (c *FakeTokenClient) Delete() *FakeTokenDelete {
	mutation := newFakeTokenMutation(c.config, OpDelete)
	return &FakeTokenDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FakeTokenClient) DeleteOne(ft *FakeToken) *FakeTokenDeleteOne {
	return c.DeleteOneID(ft.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FakeTokenClient) DeleteOneID(id int64) *FakeTokenDeleteOne {
	builder := c.Delete().Where(faketoken.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FakeTokenDeleteOne{builder}
}

// Query returns a query builder for FakeToken.
func (c *FakeTokenClient) Query() *FakeTokenQuery {
	return &FakeTokenQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFakeToken},
		inters: c.Interceptors(),
	}
}

// Get returns a FakeToken entity by its id.
func (c *FakeTokenClient) Get(ctx context.Context, id int64) (*FakeToken, error) {
	return c.Query().Where(faketoken.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FakeTokenClient) GetX(ctx context.Context, id int64) *FakeToken {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a FakeToken.
func (c *FakeTokenClient) QueryUser(ft *FakeToken) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ft.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(faketoken.Table, faketoken.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, faketoken.UserTable, faketoken.UserColumn),
		)
		fromV = sqlgraph.Neighbors(ft.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryProviderAccount queries the provider_account edge of a FakeToken.
func (c *FakeTokenClient) QueryProviderAccount(ft *FakeToken) *ProviderAccountQuery {
	query := (&ProviderAccountClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ft.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(faketoken.Table, faketoken.FieldID, id),
			sqlgraph.To(provideraccount.Table, provideraccount.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, faketoken.ProviderAccountTable, faketoken.ProviderAccountColumn),
		)
		fromV = sqlgraph.Neighbors(ft.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *FakeTokenClient) Hooks() []Hook {
	return c.hooks.FakeToken
}

// Interceptors returns the client interceptors.
func (c *FakeTokenClient) Interceptors() []Interceptor {
	return c.inters.FakeToken
}

func (c *FakeTokenClient) mutate(ctx context.Context, m *FakeTokenMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FakeTokenCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FakeTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FakeTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FakeTokenDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("dbrt: unknown FakeToken mutation op: %q", m.Op())
	}
}

// ProviderAccountClient is a client for the ProviderAccount schema.
type ProviderAccountClient struct {
	config
}

// NewProviderAccountClient returns a client for the ProviderAccount from the given config.
func NewProviderAccountClient(c config) *ProviderAccountClient {
	return &ProviderAccountClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `provideraccount.Hooks(f(g(h())))`.
func (c *ProviderAccountClient) Use(hooks ...Hook) {
	c.hooks.ProviderAccount = append(c.hooks.ProviderAccount, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `provideraccount.Intercept(f(g(h())))`.
func (c *ProviderAccountClient) Intercept(interceptors ...Interceptor) {
	c.inters.ProviderAccount = append(c.inters.ProviderAccount, interceptors...)
}

// Create returns a builder for creating a ProviderAccount entity.
func (c *ProviderAccountClient) Create() *ProviderAccountCreate {
	mutation := newProviderAccountMutation(c.config, OpCreate)
	return &ProviderAccountCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ProviderAccount entities.
func (c *ProviderAccountClient) CreateBulk(builders ...*ProviderAccountCreate) *ProviderAccountCreateBulk {
	return &ProviderAccountCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ProviderAccountClient) MapCreateBulk(slice any, setFunc func(*ProviderAccountCreate, int)) *ProviderAccountCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ProviderAccountCreateBulk{err: fmt.Errorf("calling to ProviderAccountClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ProviderAccountCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ProviderAccountCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ProviderAccount.
func (c *ProviderAccountClient) Update() *ProviderAccountUpdate {
	mutation := newProviderAccountMutation(c.config, OpUpdate)
	return &ProviderAccountUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ProviderAccountClient) UpdateOne(pa *ProviderAccount) *ProviderAccountUpdateOne {
	mutation := newProviderAccountMutation(c.config, OpUpdateOne, withProviderAccount(pa))
	return &ProviderAccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ProviderAccountClient) UpdateOneID(id int64) *ProviderAccountUpdateOne {
	mutation := newProviderAccountMutation(c.config, OpUpdateOne, withProviderAccountID(id))
	return &ProviderAccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ProviderAccount.
func (c *ProviderAccountClient) Delete() *ProviderAccountDelete {
	mutation := newProviderAccountMutation(c.config, OpDelete)
	return &ProviderAccountDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ProviderAccountClient) DeleteOne(pa *ProviderAccount) *ProviderAccountDeleteOne {
	return c.DeleteOneID(pa.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ProviderAccountClient) DeleteOneID(id int64) *ProviderAccountDeleteOne {
	builder := c.Delete().Where(provideraccount.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ProviderAccountDeleteOne{builder}
}

// Query returns a query builder for ProviderAccount.
func (c *ProviderAccountClient) Query() *ProviderAccountQuery {
	return &ProviderAccountQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeProviderAccount},
		inters: c.Interceptors(),
	}
}

// Get returns a ProviderAccount entity by its id.
func (c *ProviderAccountClient) Get(ctx context.Context, id int64) (*ProviderAccount, error) {
	return c.Query().Where(provideraccount.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ProviderAccountClient) GetX(ctx context.Context, id int64) *ProviderAccount {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryFakeTokens queries the fake_tokens edge of a ProviderAccount.
func (c *ProviderAccountClient) QueryFakeTokens(pa *ProviderAccount) *FakeTokenQuery {
	query := (&FakeTokenClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := pa.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(provideraccount.Table, provideraccount.FieldID, id),
			sqlgraph.To(faketoken.Table, faketoken.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, provideraccount.FakeTokensTable, provideraccount.FakeTokensColumn),
		)
		fromV = sqlgraph.Neighbors(pa.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryGrantedUsers queries the granted_users edge of a ProviderAccount.
func (c *ProviderAccountClient) QueryGrantedUsers(pa *ProviderAccount) *UserGrantedProviderAccountQuery {
	query := (&UserGrantedProviderAccountClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := pa.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(provideraccount.Table, provideraccount.FieldID, id),
			sqlgraph.To(usergrantedprovideraccount.Table, usergrantedprovideraccount.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, provideraccount.GrantedUsersTable, provideraccount.GrantedUsersColumn),
		)
		fromV = sqlgraph.Neighbors(pa.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ProviderAccountClient) Hooks() []Hook {
	return c.hooks.ProviderAccount
}

// Interceptors returns the client interceptors.
func (c *ProviderAccountClient) Interceptors() []Interceptor {
	return c.inters.ProviderAccount
}

func (c *ProviderAccountClient) mutate(ctx context.Context, m *ProviderAccountMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ProviderAccountCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ProviderAccountUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ProviderAccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ProviderAccountDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("dbrt: unknown ProviderAccount mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(u *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(u))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int64) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(u *User) *UserDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int64) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int64) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int64) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryFakeTokens queries the fake_tokens edge of a User.
func (c *UserClient) QueryFakeTokens(u *User) *FakeTokenQuery {
	query := (&FakeTokenClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(faketoken.Table, faketoken.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.FakeTokensTable, user.FakeTokensColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryGrantedProviderAccounts queries the granted_provider_accounts edge of a User.
func (c *UserClient) QueryGrantedProviderAccounts(u *User) *UserGrantedProviderAccountQuery {
	query := (&UserGrantedProviderAccountClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(usergrantedprovideraccount.Table, usergrantedprovideraccount.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.GrantedProviderAccountsTable, user.GrantedProviderAccountsColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("dbrt: unknown User mutation op: %q", m.Op())
	}
}

// UserGrantedProviderAccountClient is a client for the UserGrantedProviderAccount schema.
type UserGrantedProviderAccountClient struct {
	config
}

// NewUserGrantedProviderAccountClient returns a client for the UserGrantedProviderAccount from the given config.
func NewUserGrantedProviderAccountClient(c config) *UserGrantedProviderAccountClient {
	return &UserGrantedProviderAccountClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `usergrantedprovideraccount.Hooks(f(g(h())))`.
func (c *UserGrantedProviderAccountClient) Use(hooks ...Hook) {
	c.hooks.UserGrantedProviderAccount = append(c.hooks.UserGrantedProviderAccount, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `usergrantedprovideraccount.Intercept(f(g(h())))`.
func (c *UserGrantedProviderAccountClient) Intercept(interceptors ...Interceptor) {
	c.inters.UserGrantedProviderAccount = append(c.inters.UserGrantedProviderAccount, interceptors...)
}

// Create returns a builder for creating a UserGrantedProviderAccount entity.
func (c *UserGrantedProviderAccountClient) Create() *UserGrantedProviderAccountCreate {
	mutation := newUserGrantedProviderAccountMutation(c.config, OpCreate)
	return &UserGrantedProviderAccountCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UserGrantedProviderAccount entities.
func (c *UserGrantedProviderAccountClient) CreateBulk(builders ...*UserGrantedProviderAccountCreate) *UserGrantedProviderAccountCreateBulk {
	return &UserGrantedProviderAccountCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserGrantedProviderAccountClient) MapCreateBulk(slice any, setFunc func(*UserGrantedProviderAccountCreate, int)) *UserGrantedProviderAccountCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserGrantedProviderAccountCreateBulk{err: fmt.Errorf("calling to UserGrantedProviderAccountClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserGrantedProviderAccountCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserGrantedProviderAccountCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UserGrantedProviderAccount.
func (c *UserGrantedProviderAccountClient) Update() *UserGrantedProviderAccountUpdate {
	mutation := newUserGrantedProviderAccountMutation(c.config, OpUpdate)
	return &UserGrantedProviderAccountUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserGrantedProviderAccountClient) UpdateOne(ugpa *UserGrantedProviderAccount) *UserGrantedProviderAccountUpdateOne {
	mutation := newUserGrantedProviderAccountMutation(c.config, OpUpdateOne, withUserGrantedProviderAccount(ugpa))
	return &UserGrantedProviderAccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserGrantedProviderAccountClient) UpdateOneID(id int64) *UserGrantedProviderAccountUpdateOne {
	mutation := newUserGrantedProviderAccountMutation(c.config, OpUpdateOne, withUserGrantedProviderAccountID(id))
	return &UserGrantedProviderAccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UserGrantedProviderAccount.
func (c *UserGrantedProviderAccountClient) Delete() *UserGrantedProviderAccountDelete {
	mutation := newUserGrantedProviderAccountMutation(c.config, OpDelete)
	return &UserGrantedProviderAccountDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserGrantedProviderAccountClient) DeleteOne(ugpa *UserGrantedProviderAccount) *UserGrantedProviderAccountDeleteOne {
	return c.DeleteOneID(ugpa.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserGrantedProviderAccountClient) DeleteOneID(id int64) *UserGrantedProviderAccountDeleteOne {
	builder := c.Delete().Where(usergrantedprovideraccount.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserGrantedProviderAccountDeleteOne{builder}
}

// Query returns a query builder for UserGrantedProviderAccount.
func (c *UserGrantedProviderAccountClient) Query() *UserGrantedProviderAccountQuery {
	return &UserGrantedProviderAccountQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUserGrantedProviderAccount},
		inters: c.Interceptors(),
	}
}

// Get returns a UserGrantedProviderAccount entity by its id.
func (c *UserGrantedProviderAccountClient) Get(ctx context.Context, id int64) (*UserGrantedProviderAccount, error) {
	return c.Query().Where(usergrantedprovideraccount.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserGrantedProviderAccountClient) GetX(ctx context.Context, id int64) *UserGrantedProviderAccount {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a UserGrantedProviderAccount.
func (c *UserGrantedProviderAccountClient) QueryUser(ugpa *UserGrantedProviderAccount) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ugpa.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(usergrantedprovideraccount.Table, usergrantedprovideraccount.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, usergrantedprovideraccount.UserTable, usergrantedprovideraccount.UserColumn),
		)
		fromV = sqlgraph.Neighbors(ugpa.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryProviderAccount queries the provider_account edge of a UserGrantedProviderAccount.
func (c *UserGrantedProviderAccountClient) QueryProviderAccount(ugpa *UserGrantedProviderAccount) *ProviderAccountQuery {
	query := (&ProviderAccountClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ugpa.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(usergrantedprovideraccount.Table, usergrantedprovideraccount.FieldID, id),
			sqlgraph.To(provideraccount.Table, provideraccount.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, usergrantedprovideraccount.ProviderAccountTable, usergrantedprovideraccount.ProviderAccountColumn),
		)
		fromV = sqlgraph.Neighbors(ugpa.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserGrantedProviderAccountClient) Hooks() []Hook {
	return c.hooks.UserGrantedProviderAccount
}

// Interceptors returns the client interceptors.
func (c *UserGrantedProviderAccountClient) Interceptors() []Interceptor {
	return c.inters.UserGrantedProviderAccount
}

func (c *UserGrantedProviderAccountClient) mutate(ctx context.Context, m *UserGrantedProviderAccountMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserGrantedProviderAccountCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserGrantedProviderAccountUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserGrantedProviderAccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserGrantedProviderAccountDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("dbrt: unknown UserGrantedProviderAccount mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		FakeToken, ProviderAccount, User, UserGrantedProviderAccount []ent.Hook
	}
	inters struct {
		FakeToken, ProviderAccount, User, UserGrantedProviderAccount []ent.Interceptor
	}
)
