// Code generated by ent, DO NOT EDIT.

package dbrt

import (
	"cocoq/server/database/dbrt/faketoken"
	"cocoq/server/database/dbrt/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FakeTokenDelete is the builder for deleting a FakeToken entity.
type FakeTokenDelete struct {
	config
	hooks    []Hook
	mutation *FakeTokenMutation
}

// Where appends a list predicates to the FakeTokenDelete builder.
func (ftd *FakeTokenDelete) Where(ps ...predicate.FakeToken) *FakeTokenDelete {
	ftd.mutation.Where(ps...)
	return ftd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ftd *FakeTokenDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ftd.sqlExec, ftd.mutation, ftd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ftd *FakeTokenDelete) ExecX(ctx context.Context) int {
	n, err := ftd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ftd *FakeTokenDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(faketoken.Table, sqlgraph.NewFieldSpec(faketoken.FieldID, field.TypeInt64))
	if ps := ftd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ftd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ftd.mutation.done = true
	return affected, err
}

// FakeTokenDeleteOne is the builder for deleting a single FakeToken entity.
type FakeTokenDeleteOne struct {
	ftd *FakeTokenDelete
}

// Where appends a list predicates to the FakeTokenDelete builder.
func (ftdo *FakeTokenDeleteOne) Where(ps ...predicate.FakeToken) *FakeTokenDeleteOne {
	ftdo.ftd.mutation.Where(ps...)
	return ftdo
}

// Exec executes the deletion query.
func (ftdo *FakeTokenDeleteOne) Exec(ctx context.Context) error {
	n, err := ftdo.ftd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{faketoken.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ftdo *FakeTokenDeleteOne) ExecX(ctx context.Context) {
	if err := ftdo.Exec(ctx); err != nil {
		panic(err)
	}
}
