// Code generated by ent, DO NOT EDIT.

package dbrt

import (
	"cocoq/server/database/dbrt/faketoken"
	"cocoq/server/database/dbrt/provideraccount"
	"cocoq/server/database/dbrt/user"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// FakeToken is the model entity for the FakeToken schema.
type FakeToken struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// ProviderAccountID holds the value of the "provider_account_id" field.
	ProviderAccountID int64 `json:"provider_account_id,omitempty"`
	// AccessToken holds the value of the "access_token" field.
	AccessToken string `json:"access_token,omitempty"`
	// RefreshToken holds the value of the "refresh_token" field.
	RefreshToken string `json:"refresh_token,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FakeTokenQuery when eager-loading is set.
	Edges        FakeTokenEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FakeTokenEdges holds the relations/edges for other nodes in the graph.
type FakeTokenEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// ProviderAccount holds the value of the provider_account edge.
	ProviderAccount *ProviderAccount `json:"provider_account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FakeTokenEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ProviderAccountOrErr returns the ProviderAccount value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FakeTokenEdges) ProviderAccountOrErr() (*ProviderAccount, error) {
	if e.ProviderAccount != nil {
		return e.ProviderAccount, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: provideraccount.Label}
	}
	return nil, &NotLoadedError{edge: "provider_account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FakeToken) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case faketoken.FieldID, faketoken.FieldUserID, faketoken.FieldProviderAccountID:
			values[i] = new(sql.NullInt64)
		case faketoken.FieldAccessToken, faketoken.FieldRefreshToken:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FakeToken fields.
func (ft *FakeToken) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case faketoken.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ft.ID = int64(value.Int64)
		case faketoken.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				ft.UserID = value.Int64
			}
		case faketoken.FieldProviderAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field provider_account_id", values[i])
			} else if value.Valid {
				ft.ProviderAccountID = value.Int64
			}
		case faketoken.FieldAccessToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_token", values[i])
			} else if value.Valid {
				ft.AccessToken = value.String
			}
		case faketoken.FieldRefreshToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_token", values[i])
			} else if value.Valid {
				ft.RefreshToken = value.String
			}
		default:
			ft.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FakeToken.
// This includes values selected through modifiers, order, etc.
func (ft *FakeToken) Value(name string) (ent.Value, error) {
	return ft.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the FakeToken entity.
func (ft *FakeToken) QueryUser() *UserQuery {
	return NewFakeTokenClient(ft.config).QueryUser(ft)
}

// QueryProviderAccount queries the "provider_account" edge of the FakeToken entity.
func (ft *FakeToken) QueryProviderAccount() *ProviderAccountQuery {
	return NewFakeTokenClient(ft.config).QueryProviderAccount(ft)
}

// Update returns a builder for updating this FakeToken.
// Note that you need to call FakeToken.Unwrap() before calling this method if this FakeToken
// was returned from a transaction, and the transaction was committed or rolled back.
func (ft *FakeToken) Update() *FakeTokenUpdateOne {
	return NewFakeTokenClient(ft.config).UpdateOne(ft)
}

// Unwrap unwraps the FakeToken entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ft *FakeToken) Unwrap() *FakeToken {
	_tx, ok := ft.config.driver.(*txDriver)
	if !ok {
		panic("dbrt: FakeToken is not a transactional entity")
	}
	ft.config.driver = _tx.drv
	return ft
}

// String implements the fmt.Stringer.
func (ft *FakeToken) String() string {
	var builder strings.Builder
	builder.WriteString("FakeToken(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ft.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", ft.UserID))
	builder.WriteString(", ")
	builder.WriteString("provider_account_id=")
	builder.WriteString(fmt.Sprintf("%v", ft.ProviderAccountID))
	builder.WriteString(", ")
	builder.WriteString("access_token=")
	builder.WriteString(ft.AccessToken)
	builder.WriteString(", ")
	builder.WriteString("refresh_token=")
	builder.WriteString(ft.RefreshToken)
	builder.WriteByte(')')
	return builder.String()
}

// FakeTokens is a parsable slice of FakeToken.
type FakeTokens []*FakeToken
