// Code generated by ent, DO NOT EDIT.

package dbrt

import (
	"cocoq/server/database/dbrt/faketoken"
	"cocoq/server/database/dbrt/predicate"
	"cocoq/server/database/dbrt/provideraccount"
	"cocoq/server/database/dbrt/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FakeTokenUpdate is the builder for updating FakeToken entities.
type FakeTokenUpdate struct {
	config
	hooks    []Hook
	mutation *FakeTokenMutation
}

// Where appends a list predicates to the FakeTokenUpdate builder.
func (ftu *FakeTokenUpdate) Where(ps ...predicate.FakeToken) *FakeTokenUpdate {
	ftu.mutation.Where(ps...)
	return ftu
}

// SetUserID sets the "user_id" field.
func (ftu *FakeTokenUpdate) SetUserID(i int64) *FakeTokenUpdate {
	ftu.mutation.SetUserID(i)
	return ftu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (ftu *FakeTokenUpdate) SetNillableUserID(i *int64) *FakeTokenUpdate {
	if i != nil {
		ftu.SetUserID(*i)
	}
	return ftu
}

// SetProviderAccountID sets the "provider_account_id" field.
func (ftu *FakeTokenUpdate) SetProviderAccountID(i int64) *FakeTokenUpdate {
	ftu.mutation.SetProviderAccountID(i)
	return ftu
}

// SetNillableProviderAccountID sets the "provider_account_id" field if the given value is not nil.
func (ftu *FakeTokenUpdate) SetNillableProviderAccountID(i *int64) *FakeTokenUpdate {
	if i != nil {
		ftu.SetProviderAccountID(*i)
	}
	return ftu
}

// SetAccessToken sets the "access_token" field.
func (ftu *FakeTokenUpdate) SetAccessToken(s string) *FakeTokenUpdate {
	ftu.mutation.SetAccessToken(s)
	return ftu
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (ftu *FakeTokenUpdate) SetNillableAccessToken(s *string) *FakeTokenUpdate {
	if s != nil {
		ftu.SetAccessToken(*s)
	}
	return ftu
}

// SetRefreshToken sets the "refresh_token" field.
func (ftu *FakeTokenUpdate) SetRefreshToken(s string) *FakeTokenUpdate {
	ftu.mutation.SetRefreshToken(s)
	return ftu
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (ftu *FakeTokenUpdate) SetNillableRefreshToken(s *string) *FakeTokenUpdate {
	if s != nil {
		ftu.SetRefreshToken(*s)
	}
	return ftu
}

// SetUser sets the "user" edge to the User entity.
func (ftu *FakeTokenUpdate) SetUser(u *User) *FakeTokenUpdate {
	return ftu.SetUserID(u.ID)
}

// SetProviderAccount sets the "provider_account" edge to the ProviderAccount entity.
func (ftu *FakeTokenUpdate) SetProviderAccount(p *ProviderAccount) *FakeTokenUpdate {
	return ftu.SetProviderAccountID(p.ID)
}

// Mutation returns the FakeTokenMutation object of the builder.
func (ftu *FakeTokenUpdate) Mutation() *FakeTokenMutation {
	return ftu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (ftu *FakeTokenUpdate) ClearUser() *FakeTokenUpdate {
	ftu.mutation.ClearUser()
	return ftu
}

// ClearProviderAccount clears the "provider_account" edge to the ProviderAccount entity.
func (ftu *FakeTokenUpdate) ClearProviderAccount() *FakeTokenUpdate {
	ftu.mutation.ClearProviderAccount()
	return ftu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ftu *FakeTokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ftu.sqlSave, ftu.mutation, ftu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ftu *FakeTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := ftu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ftu *FakeTokenUpdate) Exec(ctx context.Context) error {
	_, err := ftu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ftu *FakeTokenUpdate) ExecX(ctx context.Context) {
	if err := ftu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ftu *FakeTokenUpdate) check() error {
	if ftu.mutation.UserCleared() && len(ftu.mutation.UserIDs()) > 0 {
		return errors.New(`dbrt: clearing a required unique edge "FakeToken.user"`)
	}
	if ftu.mutation.ProviderAccountCleared() && len(ftu.mutation.ProviderAccountIDs()) > 0 {
		return errors.New(`dbrt: clearing a required unique edge "FakeToken.provider_account"`)
	}
	return nil
}

func (ftu *FakeTokenUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ftu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(faketoken.Table, faketoken.Columns, sqlgraph.NewFieldSpec(faketoken.FieldID, field.TypeInt64))
	if ps := ftu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ftu.mutation.AccessToken(); ok {
		_spec.SetField(faketoken.FieldAccessToken, field.TypeString, value)
	}
	if value, ok := ftu.mutation.RefreshToken(); ok {
		_spec.SetField(faketoken.FieldRefreshToken, field.TypeString, value)
	}
	if ftu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   faketoken.UserTable,
			Columns: []string{faketoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ftu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   faketoken.UserTable,
			Columns: []string{faketoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ftu.mutation.ProviderAccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   faketoken.ProviderAccountTable,
			Columns: []string{faketoken.ProviderAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provideraccount.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ftu.mutation.ProviderAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   faketoken.ProviderAccountTable,
			Columns: []string{faketoken.ProviderAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provideraccount.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ftu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{faketoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ftu.mutation.done = true
	return n, nil
}

// FakeTokenUpdateOne is the builder for updating a single FakeToken entity.
type FakeTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FakeTokenMutation
}

// SetUserID sets the "user_id" field.
func (ftuo *FakeTokenUpdateOne) SetUserID(i int64) *FakeTokenUpdateOne {
	ftuo.mutation.SetUserID(i)
	return ftuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (ftuo *FakeTokenUpdateOne) SetNillableUserID(i *int64) *FakeTokenUpdateOne {
	if i != nil {
		ftuo.SetUserID(*i)
	}
	return ftuo
}

// SetProviderAccountID sets the "provider_account_id" field.
func (ftuo *FakeTokenUpdateOne) SetProviderAccountID(i int64) *FakeTokenUpdateOne {
	ftuo.mutation.SetProviderAccountID(i)
	return ftuo
}

// SetNillableProviderAccountID sets the "provider_account_id" field if the given value is not nil.
func (ftuo *FakeTokenUpdateOne) SetNillableProviderAccountID(i *int64) *FakeTokenUpdateOne {
	if i != nil {
		ftuo.SetProviderAccountID(*i)
	}
	return ftuo
}

// SetAccessToken sets the "access_token" field.
func (ftuo *FakeTokenUpdateOne) SetAccessToken(s string) *FakeTokenUpdateOne {
	ftuo.mutation.SetAccessToken(s)
	return ftuo
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (ftuo *FakeTokenUpdateOne) SetNillableAccessToken(s *string) *FakeTokenUpdateOne {
	if s != nil {
		ftuo.SetAccessToken(*s)
	}
	return ftuo
}

// SetRefreshToken sets the "refresh_token" field.
func (ftuo *FakeTokenUpdateOne) SetRefreshToken(s string) *FakeTokenUpdateOne {
	ftuo.mutation.SetRefreshToken(s)
	return ftuo
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (ftuo *FakeTokenUpdateOne) SetNillableRefreshToken(s *string) *FakeTokenUpdateOne {
	if s != nil {
		ftuo.SetRefreshToken(*s)
	}
	return ftuo
}

// SetUser sets the "user" edge to the User entity.
func (ftuo *FakeTokenUpdateOne) SetUser(u *User) *FakeTokenUpdateOne {
	return ftuo.SetUserID(u.ID)
}

// SetProviderAccount sets the "provider_account" edge to the ProviderAccount entity.
func (ftuo *FakeTokenUpdateOne) SetProviderAccount(p *ProviderAccount) *FakeTokenUpdateOne {
	return ftuo.SetProviderAccountID(p.ID)
}

// Mutation returns the FakeTokenMutation object of the builder.
func (ftuo *FakeTokenUpdateOne) Mutation() *FakeTokenMutation {
	return ftuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (ftuo *FakeTokenUpdateOne) ClearUser() *FakeTokenUpdateOne {
	ftuo.mutation.ClearUser()
	return ftuo
}

// ClearProviderAccount clears the "provider_account" edge to the ProviderAccount entity.
func (ftuo *FakeTokenUpdateOne) ClearProviderAccount() *FakeTokenUpdateOne {
	ftuo.mutation.ClearProviderAccount()
	return ftuo
}

// Where appends a list predicates to the FakeTokenUpdate builder.
func (ftuo *FakeTokenUpdateOne) Where(ps ...predicate.FakeToken) *FakeTokenUpdateOne {
	ftuo.mutation.Where(ps...)
	return ftuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ftuo *FakeTokenUpdateOne) Select(field string, fields ...string) *FakeTokenUpdateOne {
	ftuo.fields = append([]string{field}, fields...)
	return ftuo
}

// Save executes the query and returns the updated FakeToken entity.
func (ftuo *FakeTokenUpdateOne) Save(ctx context.Context) (*FakeToken, error) {
	return withHooks(ctx, ftuo.sqlSave, ftuo.mutation, ftuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ftuo *FakeTokenUpdateOne) SaveX(ctx context.Context) *FakeToken {
	node, err := ftuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ftuo *FakeTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := ftuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ftuo *FakeTokenUpdateOne) ExecX(ctx context.Context) {
	if err := ftuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ftuo *FakeTokenUpdateOne) check() error {
	if ftuo.mutation.UserCleared() && len(ftuo.mutation.UserIDs()) > 0 {
		return errors.New(`dbrt: clearing a required unique edge "FakeToken.user"`)
	}
	if ftuo.mutation.ProviderAccountCleared() && len(ftuo.mutation.ProviderAccountIDs()) > 0 {
		return errors.New(`dbrt: clearing a required unique edge "FakeToken.provider_account"`)
	}
	return nil
}

func (ftuo *FakeTokenUpdateOne) sqlSave(ctx context.Context) (_node *FakeToken, err error) {
	if err := ftuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(faketoken.Table, faketoken.Columns, sqlgraph.NewFieldSpec(faketoken.FieldID, field.TypeInt64))
	id, ok := ftuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`dbrt: missing "FakeToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ftuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, faketoken.FieldID)
		for _, f := range fields {
			if !faketoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("dbrt: invalid field %q for query", f)}
			}
			if f != faketoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ftuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ftuo.mutation.AccessToken(); ok {
		_spec.SetField(faketoken.FieldAccessToken, field.TypeString, value)
	}
	if value, ok := ftuo.mutation.RefreshToken(); ok {
		_spec.SetField(faketoken.FieldRefreshToken, field.TypeString, value)
	}
	if ftuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   faketoken.UserTable,
			Columns: []string{faketoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ftuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   faketoken.UserTable,
			Columns: []string{faketoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ftuo.mutation.ProviderAccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   faketoken.ProviderAccountTable,
			Columns: []string{faketoken.ProviderAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provideraccount.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ftuo.mutation.ProviderAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   faketoken.ProviderAccountTable,
			Columns: []string{faketoken.ProviderAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provideraccount.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &FakeToken{config: ftuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ftuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{faketoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ftuo.mutation.done = true
	return _node, nil
}
