// Code generated by ent, DO NOT EDIT.

package dbrt

import (
	"cocoq/server/database/dbrt/faketoken"
	"cocoq/server/database/dbrt/predicate"
	"cocoq/server/database/dbrt/provideraccount"
	"cocoq/server/database/dbrt/user"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FakeTokenQuery is the builder for querying FakeToken entities.
type FakeTokenQuery struct {
	config
	ctx                 *QueryContext
	order               []faketoken.OrderOption
	inters              []Interceptor
	predicates          []predicate.FakeToken
	withUser            *UserQuery
	withProviderAccount *ProviderAccountQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FakeTokenQuery builder.
func (ftq *FakeTokenQuery) Where(ps ...predicate.FakeToken) *FakeTokenQuery {
	ftq.predicates = append(ftq.predicates, ps...)
	return ftq
}

// Limit the number of records to be returned by this query.
func (ftq *FakeTokenQuery) Limit(limit int) *FakeTokenQuery {
	ftq.ctx.Limit = &limit
	return ftq
}

// Offset to start from.
func (ftq *FakeTokenQuery) Offset(offset int) *FakeTokenQuery {
	ftq.ctx.Offset = &offset
	return ftq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ftq *FakeTokenQuery) Unique(unique bool) *FakeTokenQuery {
	ftq.ctx.Unique = &unique
	return ftq
}

// Order specifies how the records should be ordered.
func (ftq *FakeTokenQuery) Order(o ...faketoken.OrderOption) *FakeTokenQuery {
	ftq.order = append(ftq.order, o...)
	return ftq
}

// QueryUser chains the current query on the "user" edge.
func (ftq *FakeTokenQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: ftq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ftq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ftq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(faketoken.Table, faketoken.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, faketoken.UserTable, faketoken.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(ftq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProviderAccount chains the current query on the "provider_account" edge.
func (ftq *FakeTokenQuery) QueryProviderAccount() *ProviderAccountQuery {
	query := (&ProviderAccountClient{config: ftq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ftq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ftq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(faketoken.Table, faketoken.FieldID, selector),
			sqlgraph.To(provideraccount.Table, provideraccount.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, faketoken.ProviderAccountTable, faketoken.ProviderAccountColumn),
		)
		fromU = sqlgraph.SetNeighbors(ftq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first FakeToken entity from the query.
// Returns a *NotFoundError when no FakeToken was found.
func (ftq *FakeTokenQuery) First(ctx context.Context) (*FakeToken, error) {
	nodes, err := ftq.Limit(1).All(setContextOp(ctx, ftq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{faketoken.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ftq *FakeTokenQuery) FirstX(ctx context.Context) *FakeToken {
	node, err := ftq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FakeToken ID from the query.
// Returns a *NotFoundError when no FakeToken ID was found.
func (ftq *FakeTokenQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = ftq.Limit(1).IDs(setContextOp(ctx, ftq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{faketoken.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ftq *FakeTokenQuery) FirstIDX(ctx context.Context) int64 {
	id, err := ftq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FakeToken entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FakeToken entity is found.
// Returns a *NotFoundError when no FakeToken entities are found.
func (ftq *FakeTokenQuery) Only(ctx context.Context) (*FakeToken, error) {
	nodes, err := ftq.Limit(2).All(setContextOp(ctx, ftq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{faketoken.Label}
	default:
		return nil, &NotSingularError{faketoken.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ftq *FakeTokenQuery) OnlyX(ctx context.Context) *FakeToken {
	node, err := ftq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FakeToken ID in the query.
// Returns a *NotSingularError when more than one FakeToken ID is found.
// Returns a *NotFoundError when no entities are found.
func (ftq *FakeTokenQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = ftq.Limit(2).IDs(setContextOp(ctx, ftq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{faketoken.Label}
	default:
		err = &NotSingularError{faketoken.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ftq *FakeTokenQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := ftq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FakeTokens.
func (ftq *FakeTokenQuery) All(ctx context.Context) ([]*FakeToken, error) {
	ctx = setContextOp(ctx, ftq.ctx, ent.OpQueryAll)
	if err := ftq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FakeToken, *FakeTokenQuery]()
	return withInterceptors[[]*FakeToken](ctx, ftq, qr, ftq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ftq *FakeTokenQuery) AllX(ctx context.Context) []*FakeToken {
	nodes, err := ftq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FakeToken IDs.
func (ftq *FakeTokenQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if ftq.ctx.Unique == nil && ftq.path != nil {
		ftq.Unique(true)
	}
	ctx = setContextOp(ctx, ftq.ctx, ent.OpQueryIDs)
	if err = ftq.Select(faketoken.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ftq *FakeTokenQuery) IDsX(ctx context.Context) []int64 {
	ids, err := ftq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ftq *FakeTokenQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ftq.ctx, ent.OpQueryCount)
	if err := ftq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ftq, querierCount[*FakeTokenQuery](), ftq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ftq *FakeTokenQuery) CountX(ctx context.Context) int {
	count, err := ftq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ftq *FakeTokenQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ftq.ctx, ent.OpQueryExist)
	switch _, err := ftq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("dbrt: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ftq *FakeTokenQuery) ExistX(ctx context.Context) bool {
	exist, err := ftq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FakeTokenQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ftq *FakeTokenQuery) Clone() *FakeTokenQuery {
	if ftq == nil {
		return nil
	}
	return &FakeTokenQuery{
		config:              ftq.config,
		ctx:                 ftq.ctx.Clone(),
		order:               append([]faketoken.OrderOption{}, ftq.order...),
		inters:              append([]Interceptor{}, ftq.inters...),
		predicates:          append([]predicate.FakeToken{}, ftq.predicates...),
		withUser:            ftq.withUser.Clone(),
		withProviderAccount: ftq.withProviderAccount.Clone(),
		// clone intermediate query.
		sql:  ftq.sql.Clone(),
		path: ftq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (ftq *FakeTokenQuery) WithUser(opts ...func(*UserQuery)) *FakeTokenQuery {
	query := (&UserClient{config: ftq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ftq.withUser = query
	return ftq
}

// WithProviderAccount tells the query-builder to eager-load the nodes that are connected to
// the "provider_account" edge. The optional arguments are used to configure the query builder of the edge.
func (ftq *FakeTokenQuery) WithProviderAccount(opts ...func(*ProviderAccountQuery)) *FakeTokenQuery {
	query := (&ProviderAccountClient{config: ftq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ftq.withProviderAccount = query
	return ftq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int64 `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FakeToken.Query().
//		GroupBy(faketoken.FieldUserID).
//		Aggregate(dbrt.Count()).
//		Scan(ctx, &v)
func (ftq *FakeTokenQuery) GroupBy(field string, fields ...string) *FakeTokenGroupBy {
	ftq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FakeTokenGroupBy{build: ftq}
	grbuild.flds = &ftq.ctx.Fields
	grbuild.label = faketoken.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int64 `json:"user_id,omitempty"`
//	}
//
//	client.FakeToken.Query().
//		Select(faketoken.FieldUserID).
//		Scan(ctx, &v)
func (ftq *FakeTokenQuery) Select(fields ...string) *FakeTokenSelect {
	ftq.ctx.Fields = append(ftq.ctx.Fields, fields...)
	sbuild := &FakeTokenSelect{FakeTokenQuery: ftq}
	sbuild.label = faketoken.Label
	sbuild.flds, sbuild.scan = &ftq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FakeTokenSelect configured with the given aggregations.
func (ftq *FakeTokenQuery) Aggregate(fns ...AggregateFunc) *FakeTokenSelect {
	return ftq.Select().Aggregate(fns...)
}

func (ftq *FakeTokenQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ftq.inters {
		if inter == nil {
			return fmt.Errorf("dbrt: uninitialized interceptor (forgotten import dbrt/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ftq); err != nil {
				return err
			}
		}
	}
	for _, f := range ftq.ctx.Fields {
		if !faketoken.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("dbrt: invalid field %q for query", f)}
		}
	}
	if ftq.path != nil {
		prev, err := ftq.path(ctx)
		if err != nil {
			return err
		}
		ftq.sql = prev
	}
	return nil
}

func (ftq *FakeTokenQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FakeToken, error) {
	var (
		nodes       = []*FakeToken{}
		_spec       = ftq.querySpec()
		loadedTypes = [2]bool{
			ftq.withUser != nil,
			ftq.withProviderAccount != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FakeToken).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FakeToken{config: ftq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ftq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ftq.withUser; query != nil {
		if err := ftq.loadUser(ctx, query, nodes, nil,
			func(n *FakeToken, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := ftq.withProviderAccount; query != nil {
		if err := ftq.loadProviderAccount(ctx, query, nodes, nil,
			func(n *FakeToken, e *ProviderAccount) { n.Edges.ProviderAccount = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ftq *FakeTokenQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*FakeToken, init func(*FakeToken), assign func(*FakeToken, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*FakeToken)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (ftq *FakeTokenQuery) loadProviderAccount(ctx context.Context, query *ProviderAccountQuery, nodes []*FakeToken, init func(*FakeToken), assign func(*FakeToken, *ProviderAccount)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*FakeToken)
	for i := range nodes {
		fk := nodes[i].ProviderAccountID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(provideraccount.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "provider_account_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ftq *FakeTokenQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ftq.querySpec()
	_spec.Node.Columns = ftq.ctx.Fields
	if len(ftq.ctx.Fields) > 0 {
		_spec.Unique = ftq.ctx.Unique != nil && *ftq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ftq.driver, _spec)
}

func (ftq *FakeTokenQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(faketoken.Table, faketoken.Columns, sqlgraph.NewFieldSpec(faketoken.FieldID, field.TypeInt64))
	_spec.From = ftq.sql
	if unique := ftq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ftq.path != nil {
		_spec.Unique = true
	}
	if fields := ftq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, faketoken.FieldID)
		for i := range fields {
			if fields[i] != faketoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if ftq.withUser != nil {
			_spec.Node.AddColumnOnce(faketoken.FieldUserID)
		}
		if ftq.withProviderAccount != nil {
			_spec.Node.AddColumnOnce(faketoken.FieldProviderAccountID)
		}
	}
	if ps := ftq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ftq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ftq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ftq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ftq *FakeTokenQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ftq.driver.Dialect())
	t1 := builder.Table(faketoken.Table)
	columns := ftq.ctx.Fields
	if len(columns) == 0 {
		columns = faketoken.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ftq.sql != nil {
		selector = ftq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ftq.ctx.Unique != nil && *ftq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ftq.predicates {
		p(selector)
	}
	for _, p := range ftq.order {
		p(selector)
	}
	if offset := ftq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ftq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FakeTokenGroupBy is the group-by builder for FakeToken entities.
type FakeTokenGroupBy struct {
	selector
	build *FakeTokenQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ftgb *FakeTokenGroupBy) Aggregate(fns ...AggregateFunc) *FakeTokenGroupBy {
	ftgb.fns = append(ftgb.fns, fns...)
	return ftgb
}

// Scan applies the selector query and scans the result into the given value.
func (ftgb *FakeTokenGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ftgb.build.ctx, ent.OpQueryGroupBy)
	if err := ftgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FakeTokenQuery, *FakeTokenGroupBy](ctx, ftgb.build, ftgb, ftgb.build.inters, v)
}

func (ftgb *FakeTokenGroupBy) sqlScan(ctx context.Context, root *FakeTokenQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ftgb.fns))
	for _, fn := range ftgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ftgb.flds)+len(ftgb.fns))
		for _, f := range *ftgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ftgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ftgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FakeTokenSelect is the builder for selecting fields of FakeToken entities.
type FakeTokenSelect struct {
	*FakeTokenQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fts *FakeTokenSelect) Aggregate(fns ...AggregateFunc) *FakeTokenSelect {
	fts.fns = append(fts.fns, fns...)
	return fts
}

// Scan applies the selector query and scans the result into the given value.
func (fts *FakeTokenSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fts.ctx, ent.OpQuerySelect)
	if err := fts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FakeTokenQuery, *FakeTokenSelect](ctx, fts.FakeTokenQuery, fts, fts.inters, v)
}

func (fts *FakeTokenSelect) sqlScan(ctx context.Context, root *FakeTokenQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fts.fns))
	for _, fn := range fts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
