// Code generated by ent, DO NOT EDIT.

package dbrt

import (
	"cocoq/server/database/dbrt/faketoken"
	"cocoq/server/database/dbrt/predicate"
	"cocoq/server/database/dbrt/provideraccount"
	"cocoq/server/database/dbrt/user"
	"cocoq/server/database/dbrt/usergrantedprovideraccount"
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeFakeToken                  = "FakeToken"
	TypeProviderAccount            = "ProviderAccount"
	TypeUser                       = "User"
	TypeUserGrantedProviderAccount = "UserGrantedProviderAccount"
)

// FakeTokenMutation represents an operation that mutates the FakeToken nodes in the graph.
type FakeTokenMutation struct {
	config
	op                      Op
	typ                     string
	id                      *int64
	access_token            *string
	refresh_token           *string
	clearedFields           map[string]struct{}
	user                    *int64
	cleareduser             bool
	provider_account        *int64
	clearedprovider_account bool
	done                    bool
	oldValue                func(context.Context) (*FakeToken, error)
	predicates              []predicate.FakeToken
}

var _ ent.Mutation = (*FakeTokenMutation)(nil)

// faketokenOption allows management of the mutation configuration using functional options.
type faketokenOption func(*FakeTokenMutation)

// newFakeTokenMutation creates new mutation for the FakeToken entity.
func newFakeTokenMutation(c config, op Op, opts ...faketokenOption) *FakeTokenMutation {
	m := &FakeTokenMutation{
		config:        c,
		op:            op,
		typ:           TypeFakeToken,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withFakeTokenID sets the ID field of the mutation.
func withFakeTokenID(id int64) faketokenOption {
	return func(m *FakeTokenMutation) {
		var (
			err   error
			once  sync.Once
			value *FakeToken
		)
		m.oldValue = func(ctx context.Context) (*FakeToken, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().FakeToken.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withFakeToken sets the old FakeToken of the mutation.
func withFakeToken(node *FakeToken) faketokenOption {
	return func(m *FakeTokenMutation) {
		m.oldValue = func(context.Context) (*FakeToken, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m FakeTokenMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m FakeTokenMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("dbrt: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of FakeToken entities.
func (m *FakeTokenMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *FakeTokenMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *FakeTokenMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().FakeToken.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUserID sets the "user_id" field.
func (m *FakeTokenMutation) SetUserID(i int64) {
	m.user = &i
}

// UserID returns the value of the "user_id" field in the mutation.
func (m *FakeTokenMutation) UserID() (r int64, exists bool) {
	v := m.user
	if v == nil {
		return
	}
	return *v, true
}

// OldUserID returns the old "user_id" field's value of the FakeToken entity.
// If the FakeToken object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FakeTokenMutation) OldUserID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserID: %w", err)
	}
	return oldValue.UserID, nil
}

// ResetUserID resets all changes to the "user_id" field.
func (m *FakeTokenMutation) ResetUserID() {
	m.user = nil
}

// SetProviderAccountID sets the "provider_account_id" field.
func (m *FakeTokenMutation) SetProviderAccountID(i int64) {
	m.provider_account = &i
}

// ProviderAccountID returns the value of the "provider_account_id" field in the mutation.
func (m *FakeTokenMutation) ProviderAccountID() (r int64, exists bool) {
	v := m.provider_account
	if v == nil {
		return
	}
	return *v, true
}

// OldProviderAccountID returns the old "provider_account_id" field's value of the FakeToken entity.
// If the FakeToken object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FakeTokenMutation) OldProviderAccountID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProviderAccountID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProviderAccountID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProviderAccountID: %w", err)
	}
	return oldValue.ProviderAccountID, nil
}

// ResetProviderAccountID resets all changes to the "provider_account_id" field.
func (m *FakeTokenMutation) ResetProviderAccountID() {
	m.provider_account = nil
}

// SetAccessToken sets the "access_token" field.
func (m *FakeTokenMutation) SetAccessToken(s string) {
	m.access_token = &s
}

// AccessToken returns the value of the "access_token" field in the mutation.
func (m *FakeTokenMutation) AccessToken() (r string, exists bool) {
	v := m.access_token
	if v == nil {
		return
	}
	return *v, true
}

// OldAccessToken returns the old "access_token" field's value of the FakeToken entity.
// If the FakeToken object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FakeTokenMutation) OldAccessToken(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAccessToken is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAccessToken requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAccessToken: %w", err)
	}
	return oldValue.AccessToken, nil
}

// ResetAccessToken resets all changes to the "access_token" field.
func (m *FakeTokenMutation) ResetAccessToken() {
	m.access_token = nil
}

// SetRefreshToken sets the "refresh_token" field.
func (m *FakeTokenMutation) SetRefreshToken(s string) {
	m.refresh_token = &s
}

// RefreshToken returns the value of the "refresh_token" field in the mutation.
func (m *FakeTokenMutation) RefreshToken() (r string, exists bool) {
	v := m.refresh_token
	if v == nil {
		return
	}
	return *v, true
}

// OldRefreshToken returns the old "refresh_token" field's value of the FakeToken entity.
// If the FakeToken object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FakeTokenMutation) OldRefreshToken(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRefreshToken is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRefreshToken requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRefreshToken: %w", err)
	}
	return oldValue.RefreshToken, nil
}

// ResetRefreshToken resets all changes to the "refresh_token" field.
func (m *FakeTokenMutation) ResetRefreshToken() {
	m.refresh_token = nil
}

// ClearUser clears the "user" edge to the User entity.
func (m *FakeTokenMutation) ClearUser() {
	m.cleareduser = true
	m.clearedFields[faketoken.FieldUserID] = struct{}{}
}

// UserCleared reports if the "user" edge to the User entity was cleared.
func (m *FakeTokenMutation) UserCleared() bool {
	return m.cleareduser
}

// UserIDs returns the "user" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// UserID instead. It exists only for internal usage by the builders.
func (m *FakeTokenMutation) UserIDs() (ids []int64) {
	if id := m.user; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetUser resets all changes to the "user" edge.
func (m *FakeTokenMutation) ResetUser() {
	m.user = nil
	m.cleareduser = false
}

// ClearProviderAccount clears the "provider_account" edge to the ProviderAccount entity.
func (m *FakeTokenMutation) ClearProviderAccount() {
	m.clearedprovider_account = true
	m.clearedFields[faketoken.FieldProviderAccountID] = struct{}{}
}

// ProviderAccountCleared reports if the "provider_account" edge to the ProviderAccount entity was cleared.
func (m *FakeTokenMutation) ProviderAccountCleared() bool {
	return m.clearedprovider_account
}

// ProviderAccountIDs returns the "provider_account" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// ProviderAccountID instead. It exists only for internal usage by the builders.
func (m *FakeTokenMutation) ProviderAccountIDs() (ids []int64) {
	if id := m.provider_account; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetProviderAccount resets all changes to the "provider_account" edge.
func (m *FakeTokenMutation) ResetProviderAccount() {
	m.provider_account = nil
	m.clearedprovider_account = false
}

// Where appends a list predicates to the FakeTokenMutation builder.
func (m *FakeTokenMutation) Where(ps ...predicate.FakeToken) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the FakeTokenMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *FakeTokenMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.FakeToken, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *FakeTokenMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *FakeTokenMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (FakeToken).
func (m *FakeTokenMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *FakeTokenMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.user != nil {
		fields = append(fields, faketoken.FieldUserID)
	}
	if m.provider_account != nil {
		fields = append(fields, faketoken.FieldProviderAccountID)
	}
	if m.access_token != nil {
		fields = append(fields, faketoken.FieldAccessToken)
	}
	if m.refresh_token != nil {
		fields = append(fields, faketoken.FieldRefreshToken)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *FakeTokenMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case faketoken.FieldUserID:
		return m.UserID()
	case faketoken.FieldProviderAccountID:
		return m.ProviderAccountID()
	case faketoken.FieldAccessToken:
		return m.AccessToken()
	case faketoken.FieldRefreshToken:
		return m.RefreshToken()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *FakeTokenMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case faketoken.FieldUserID:
		return m.OldUserID(ctx)
	case faketoken.FieldProviderAccountID:
		return m.OldProviderAccountID(ctx)
	case faketoken.FieldAccessToken:
		return m.OldAccessToken(ctx)
	case faketoken.FieldRefreshToken:
		return m.OldRefreshToken(ctx)
	}
	return nil, fmt.Errorf("unknown FakeToken field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *FakeTokenMutation) SetField(name string, value ent.Value) error {
	switch name {
	case faketoken.FieldUserID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserID(v)
		return nil
	case faketoken.FieldProviderAccountID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProviderAccountID(v)
		return nil
	case faketoken.FieldAccessToken:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAccessToken(v)
		return nil
	case faketoken.FieldRefreshToken:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRefreshToken(v)
		return nil
	}
	return fmt.Errorf("unknown FakeToken field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *FakeTokenMutation) AddedFields() []string {
	var fields []string
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *FakeTokenMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *FakeTokenMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown FakeToken numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *FakeTokenMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *FakeTokenMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *FakeTokenMutation) ClearField(name string) error {
	return fmt.Errorf("unknown FakeToken nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *FakeTokenMutation) ResetField(name string) error {
	switch name {
	case faketoken.FieldUserID:
		m.ResetUserID()
		return nil
	case faketoken.FieldProviderAccountID:
		m.ResetProviderAccountID()
		return nil
	case faketoken.FieldAccessToken:
		m.ResetAccessToken()
		return nil
	case faketoken.FieldRefreshToken:
		m.ResetRefreshToken()
		return nil
	}
	return fmt.Errorf("unknown FakeToken field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *FakeTokenMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.user != nil {
		edges = append(edges, faketoken.EdgeUser)
	}
	if m.provider_account != nil {
		edges = append(edges, faketoken.EdgeProviderAccount)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *FakeTokenMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case faketoken.EdgeUser:
		if id := m.user; id != nil {
			return []ent.Value{*id}
		}
	case faketoken.EdgeProviderAccount:
		if id := m.provider_account; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *FakeTokenMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *FakeTokenMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *FakeTokenMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.cleareduser {
		edges = append(edges, faketoken.EdgeUser)
	}
	if m.clearedprovider_account {
		edges = append(edges, faketoken.EdgeProviderAccount)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *FakeTokenMutation) EdgeCleared(name string) bool {
	switch name {
	case faketoken.EdgeUser:
		return m.cleareduser
	case faketoken.EdgeProviderAccount:
		return m.clearedprovider_account
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *FakeTokenMutation) ClearEdge(name string) error {
	switch name {
	case faketoken.EdgeUser:
		m.ClearUser()
		return nil
	case faketoken.EdgeProviderAccount:
		m.ClearProviderAccount()
		return nil
	}
	return fmt.Errorf("unknown FakeToken unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *FakeTokenMutation) ResetEdge(name string) error {
	switch name {
	case faketoken.EdgeUser:
		m.ResetUser()
		return nil
	case faketoken.EdgeProviderAccount:
		m.ResetProviderAccount()
		return nil
	}
	return fmt.Errorf("unknown FakeToken edge %s", name)
}

// ProviderAccountMutation represents an operation that mutates the ProviderAccount nodes in the graph.
type ProviderAccountMutation struct {
	config
	op                   Op
	typ                  string
	id                   *int64
	created_at           *time.Time
	updated_at           *time.Time
	account_uuid         *string
	access_token         *string
	refresh_token        *string
	credentials          *string
	clearedFields        map[string]struct{}
	fake_tokens          map[int64]struct{}
	removedfake_tokens   map[int64]struct{}
	clearedfake_tokens   bool
	granted_users        map[int64]struct{}
	removedgranted_users map[int64]struct{}
	clearedgranted_users bool
	done                 bool
	oldValue             func(context.Context) (*ProviderAccount, error)
	predicates           []predicate.ProviderAccount
}

var _ ent.Mutation = (*ProviderAccountMutation)(nil)

// provideraccountOption allows management of the mutation configuration using functional options.
type provideraccountOption func(*ProviderAccountMutation)

// newProviderAccountMutation creates new mutation for the ProviderAccount entity.
func newProviderAccountMutation(c config, op Op, opts ...provideraccountOption) *ProviderAccountMutation {
	m := &ProviderAccountMutation{
		config:        c,
		op:            op,
		typ:           TypeProviderAccount,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withProviderAccountID sets the ID field of the mutation.
func withProviderAccountID(id int64) provideraccountOption {
	return func(m *ProviderAccountMutation) {
		var (
			err   error
			once  sync.Once
			value *ProviderAccount
		)
		m.oldValue = func(ctx context.Context) (*ProviderAccount, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().ProviderAccount.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withProviderAccount sets the old ProviderAccount of the mutation.
func withProviderAccount(node *ProviderAccount) provideraccountOption {
	return func(m *ProviderAccountMutation) {
		m.oldValue = func(context.Context) (*ProviderAccount, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ProviderAccountMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ProviderAccountMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("dbrt: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of ProviderAccount entities.
func (m *ProviderAccountMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ProviderAccountMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ProviderAccountMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().ProviderAccount.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *ProviderAccountMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *ProviderAccountMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the ProviderAccount entity.
// If the ProviderAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProviderAccountMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *ProviderAccountMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *ProviderAccountMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *ProviderAccountMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the ProviderAccount entity.
// If the ProviderAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProviderAccountMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *ProviderAccountMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetAccountUUID sets the "account_uuid" field.
func (m *ProviderAccountMutation) SetAccountUUID(s string) {
	m.account_uuid = &s
}

// AccountUUID returns the value of the "account_uuid" field in the mutation.
func (m *ProviderAccountMutation) AccountUUID() (r string, exists bool) {
	v := m.account_uuid
	if v == nil {
		return
	}
	return *v, true
}

// OldAccountUUID returns the old "account_uuid" field's value of the ProviderAccount entity.
// If the ProviderAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProviderAccountMutation) OldAccountUUID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAccountUUID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAccountUUID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAccountUUID: %w", err)
	}
	return oldValue.AccountUUID, nil
}

// ResetAccountUUID resets all changes to the "account_uuid" field.
func (m *ProviderAccountMutation) ResetAccountUUID() {
	m.account_uuid = nil
}

// SetAccessToken sets the "access_token" field.
func (m *ProviderAccountMutation) SetAccessToken(s string) {
	m.access_token = &s
}

// AccessToken returns the value of the "access_token" field in the mutation.
func (m *ProviderAccountMutation) AccessToken() (r string, exists bool) {
	v := m.access_token
	if v == nil {
		return
	}
	return *v, true
}

// OldAccessToken returns the old "access_token" field's value of the ProviderAccount entity.
// If the ProviderAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProviderAccountMutation) OldAccessToken(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAccessToken is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAccessToken requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAccessToken: %w", err)
	}
	return oldValue.AccessToken, nil
}

// ResetAccessToken resets all changes to the "access_token" field.
func (m *ProviderAccountMutation) ResetAccessToken() {
	m.access_token = nil
}

// SetRefreshToken sets the "refresh_token" field.
func (m *ProviderAccountMutation) SetRefreshToken(s string) {
	m.refresh_token = &s
}

// RefreshToken returns the value of the "refresh_token" field in the mutation.
func (m *ProviderAccountMutation) RefreshToken() (r string, exists bool) {
	v := m.refresh_token
	if v == nil {
		return
	}
	return *v, true
}

// OldRefreshToken returns the old "refresh_token" field's value of the ProviderAccount entity.
// If the ProviderAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProviderAccountMutation) OldRefreshToken(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRefreshToken is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRefreshToken requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRefreshToken: %w", err)
	}
	return oldValue.RefreshToken, nil
}

// ResetRefreshToken resets all changes to the "refresh_token" field.
func (m *ProviderAccountMutation) ResetRefreshToken() {
	m.refresh_token = nil
}

// SetCredentials sets the "credentials" field.
func (m *ProviderAccountMutation) SetCredentials(s string) {
	m.credentials = &s
}

// Credentials returns the value of the "credentials" field in the mutation.
func (m *ProviderAccountMutation) Credentials() (r string, exists bool) {
	v := m.credentials
	if v == nil {
		return
	}
	return *v, true
}

// OldCredentials returns the old "credentials" field's value of the ProviderAccount entity.
// If the ProviderAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProviderAccountMutation) OldCredentials(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCredentials is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCredentials requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCredentials: %w", err)
	}
	return oldValue.Credentials, nil
}

// ResetCredentials resets all changes to the "credentials" field.
func (m *ProviderAccountMutation) ResetCredentials() {
	m.credentials = nil
}

// AddFakeTokenIDs adds the "fake_tokens" edge to the FakeToken entity by ids.
func (m *ProviderAccountMutation) AddFakeTokenIDs(ids ...int64) {
	if m.fake_tokens == nil {
		m.fake_tokens = make(map[int64]struct{})
	}
	for i := range ids {
		m.fake_tokens[ids[i]] = struct{}{}
	}
}

// ClearFakeTokens clears the "fake_tokens" edge to the FakeToken entity.
func (m *ProviderAccountMutation) ClearFakeTokens() {
	m.clearedfake_tokens = true
}

// FakeTokensCleared reports if the "fake_tokens" edge to the FakeToken entity was cleared.
func (m *ProviderAccountMutation) FakeTokensCleared() bool {
	return m.clearedfake_tokens
}

// RemoveFakeTokenIDs removes the "fake_tokens" edge to the FakeToken entity by IDs.
func (m *ProviderAccountMutation) RemoveFakeTokenIDs(ids ...int64) {
	if m.removedfake_tokens == nil {
		m.removedfake_tokens = make(map[int64]struct{})
	}
	for i := range ids {
		delete(m.fake_tokens, ids[i])
		m.removedfake_tokens[ids[i]] = struct{}{}
	}
}

// RemovedFakeTokens returns the removed IDs of the "fake_tokens" edge to the FakeToken entity.
func (m *ProviderAccountMutation) RemovedFakeTokensIDs() (ids []int64) {
	for id := range m.removedfake_tokens {
		ids = append(ids, id)
	}
	return
}

// FakeTokensIDs returns the "fake_tokens" edge IDs in the mutation.
func (m *ProviderAccountMutation) FakeTokensIDs() (ids []int64) {
	for id := range m.fake_tokens {
		ids = append(ids, id)
	}
	return
}

// ResetFakeTokens resets all changes to the "fake_tokens" edge.
func (m *ProviderAccountMutation) ResetFakeTokens() {
	m.fake_tokens = nil
	m.clearedfake_tokens = false
	m.removedfake_tokens = nil
}

// AddGrantedUserIDs adds the "granted_users" edge to the UserGrantedProviderAccount entity by ids.
func (m *ProviderAccountMutation) AddGrantedUserIDs(ids ...int64) {
	if m.granted_users == nil {
		m.granted_users = make(map[int64]struct{})
	}
	for i := range ids {
		m.granted_users[ids[i]] = struct{}{}
	}
}

// ClearGrantedUsers clears the "granted_users" edge to the UserGrantedProviderAccount entity.
func (m *ProviderAccountMutation) ClearGrantedUsers() {
	m.clearedgranted_users = true
}

// GrantedUsersCleared reports if the "granted_users" edge to the UserGrantedProviderAccount entity was cleared.
func (m *ProviderAccountMutation) GrantedUsersCleared() bool {
	return m.clearedgranted_users
}

// RemoveGrantedUserIDs removes the "granted_users" edge to the UserGrantedProviderAccount entity by IDs.
func (m *ProviderAccountMutation) RemoveGrantedUserIDs(ids ...int64) {
	if m.removedgranted_users == nil {
		m.removedgranted_users = make(map[int64]struct{})
	}
	for i := range ids {
		delete(m.granted_users, ids[i])
		m.removedgranted_users[ids[i]] = struct{}{}
	}
}

// RemovedGrantedUsers returns the removed IDs of the "granted_users" edge to the UserGrantedProviderAccount entity.
func (m *ProviderAccountMutation) RemovedGrantedUsersIDs() (ids []int64) {
	for id := range m.removedgranted_users {
		ids = append(ids, id)
	}
	return
}

// GrantedUsersIDs returns the "granted_users" edge IDs in the mutation.
func (m *ProviderAccountMutation) GrantedUsersIDs() (ids []int64) {
	for id := range m.granted_users {
		ids = append(ids, id)
	}
	return
}

// ResetGrantedUsers resets all changes to the "granted_users" edge.
func (m *ProviderAccountMutation) ResetGrantedUsers() {
	m.granted_users = nil
	m.clearedgranted_users = false
	m.removedgranted_users = nil
}

// Where appends a list predicates to the ProviderAccountMutation builder.
func (m *ProviderAccountMutation) Where(ps ...predicate.ProviderAccount) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ProviderAccountMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ProviderAccountMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.ProviderAccount, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ProviderAccountMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ProviderAccountMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (ProviderAccount).
func (m *ProviderAccountMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ProviderAccountMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.created_at != nil {
		fields = append(fields, provideraccount.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, provideraccount.FieldUpdatedAt)
	}
	if m.account_uuid != nil {
		fields = append(fields, provideraccount.FieldAccountUUID)
	}
	if m.access_token != nil {
		fields = append(fields, provideraccount.FieldAccessToken)
	}
	if m.refresh_token != nil {
		fields = append(fields, provideraccount.FieldRefreshToken)
	}
	if m.credentials != nil {
		fields = append(fields, provideraccount.FieldCredentials)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ProviderAccountMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case provideraccount.FieldCreatedAt:
		return m.CreatedAt()
	case provideraccount.FieldUpdatedAt:
		return m.UpdatedAt()
	case provideraccount.FieldAccountUUID:
		return m.AccountUUID()
	case provideraccount.FieldAccessToken:
		return m.AccessToken()
	case provideraccount.FieldRefreshToken:
		return m.RefreshToken()
	case provideraccount.FieldCredentials:
		return m.Credentials()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ProviderAccountMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case provideraccount.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case provideraccount.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case provideraccount.FieldAccountUUID:
		return m.OldAccountUUID(ctx)
	case provideraccount.FieldAccessToken:
		return m.OldAccessToken(ctx)
	case provideraccount.FieldRefreshToken:
		return m.OldRefreshToken(ctx)
	case provideraccount.FieldCredentials:
		return m.OldCredentials(ctx)
	}
	return nil, fmt.Errorf("unknown ProviderAccount field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ProviderAccountMutation) SetField(name string, value ent.Value) error {
	switch name {
	case provideraccount.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case provideraccount.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case provideraccount.FieldAccountUUID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAccountUUID(v)
		return nil
	case provideraccount.FieldAccessToken:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAccessToken(v)
		return nil
	case provideraccount.FieldRefreshToken:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRefreshToken(v)
		return nil
	case provideraccount.FieldCredentials:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCredentials(v)
		return nil
	}
	return fmt.Errorf("unknown ProviderAccount field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ProviderAccountMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ProviderAccountMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ProviderAccountMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown ProviderAccount numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ProviderAccountMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ProviderAccountMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ProviderAccountMutation) ClearField(name string) error {
	return fmt.Errorf("unknown ProviderAccount nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ProviderAccountMutation) ResetField(name string) error {
	switch name {
	case provideraccount.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case provideraccount.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case provideraccount.FieldAccountUUID:
		m.ResetAccountUUID()
		return nil
	case provideraccount.FieldAccessToken:
		m.ResetAccessToken()
		return nil
	case provideraccount.FieldRefreshToken:
		m.ResetRefreshToken()
		return nil
	case provideraccount.FieldCredentials:
		m.ResetCredentials()
		return nil
	}
	return fmt.Errorf("unknown ProviderAccount field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ProviderAccountMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.fake_tokens != nil {
		edges = append(edges, provideraccount.EdgeFakeTokens)
	}
	if m.granted_users != nil {
		edges = append(edges, provideraccount.EdgeGrantedUsers)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ProviderAccountMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case provideraccount.EdgeFakeTokens:
		ids := make([]ent.Value, 0, len(m.fake_tokens))
		for id := range m.fake_tokens {
			ids = append(ids, id)
		}
		return ids
	case provideraccount.EdgeGrantedUsers:
		ids := make([]ent.Value, 0, len(m.granted_users))
		for id := range m.granted_users {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ProviderAccountMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedfake_tokens != nil {
		edges = append(edges, provideraccount.EdgeFakeTokens)
	}
	if m.removedgranted_users != nil {
		edges = append(edges, provideraccount.EdgeGrantedUsers)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ProviderAccountMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case provideraccount.EdgeFakeTokens:
		ids := make([]ent.Value, 0, len(m.removedfake_tokens))
		for id := range m.removedfake_tokens {
			ids = append(ids, id)
		}
		return ids
	case provideraccount.EdgeGrantedUsers:
		ids := make([]ent.Value, 0, len(m.removedgranted_users))
		for id := range m.removedgranted_users {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ProviderAccountMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedfake_tokens {
		edges = append(edges, provideraccount.EdgeFakeTokens)
	}
	if m.clearedgranted_users {
		edges = append(edges, provideraccount.EdgeGrantedUsers)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ProviderAccountMutation) EdgeCleared(name string) bool {
	switch name {
	case provideraccount.EdgeFakeTokens:
		return m.clearedfake_tokens
	case provideraccount.EdgeGrantedUsers:
		return m.clearedgranted_users
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ProviderAccountMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown ProviderAccount unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ProviderAccountMutation) ResetEdge(name string) error {
	switch name {
	case provideraccount.EdgeFakeTokens:
		m.ResetFakeTokens()
		return nil
	case provideraccount.EdgeGrantedUsers:
		m.ResetGrantedUsers()
		return nil
	}
	return fmt.Errorf("unknown ProviderAccount edge %s", name)
}

// UserMutation represents an operation that mutates the User nodes in the graph.
type UserMutation struct {
	config
	op                               Op
	typ                              string
	id                               *int64
	created_at                       *time.Time
	updated_at                       *time.Time
	oauth_state_token                *string
	state                            *int64
	addstate                         *int64
	clearedFields                    map[string]struct{}
	fake_tokens                      map[int64]struct{}
	removedfake_tokens               map[int64]struct{}
	clearedfake_tokens               bool
	granted_provider_accounts        map[int64]struct{}
	removedgranted_provider_accounts map[int64]struct{}
	clearedgranted_provider_accounts bool
	done                             bool
	oldValue                         func(context.Context) (*User, error)
	predicates                       []predicate.User
}

var _ ent.Mutation = (*UserMutation)(nil)

// userOption allows management of the mutation configuration using functional options.
type userOption func(*UserMutation)

// newUserMutation creates new mutation for the User entity.
func newUserMutation(c config, op Op, opts ...userOption) *UserMutation {
	m := &UserMutation{
		config:        c,
		op:            op,
		typ:           TypeUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserID sets the ID field of the mutation.
func withUserID(id int64) userOption {
	return func(m *UserMutation) {
		var (
			err   error
			once  sync.Once
			value *User
		)
		m.oldValue = func(ctx context.Context) (*User, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().User.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUser sets the old User of the mutation.
func withUser(node *User) userOption {
	return func(m *UserMutation) {
		m.oldValue = func(context.Context) (*User, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("dbrt: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of User entities.
func (m *UserMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UserMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UserMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().User.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *UserMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *UserMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *UserMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *UserMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *UserMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *UserMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetOauthStateToken sets the "oauth_state_token" field.
func (m *UserMutation) SetOauthStateToken(s string) {
	m.oauth_state_token = &s
}

// OauthStateToken returns the value of the "oauth_state_token" field in the mutation.
func (m *UserMutation) OauthStateToken() (r string, exists bool) {
	v := m.oauth_state_token
	if v == nil {
		return
	}
	return *v, true
}

// OldOauthStateToken returns the old "oauth_state_token" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldOauthStateToken(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOauthStateToken is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOauthStateToken requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOauthStateToken: %w", err)
	}
	return oldValue.OauthStateToken, nil
}

// ResetOauthStateToken resets all changes to the "oauth_state_token" field.
func (m *UserMutation) ResetOauthStateToken() {
	m.oauth_state_token = nil
}

// SetState sets the "state" field.
func (m *UserMutation) SetState(i int64) {
	m.state = &i
	m.addstate = nil
}

// State returns the value of the "state" field in the mutation.
func (m *UserMutation) State() (r int64, exists bool) {
	v := m.state
	if v == nil {
		return
	}
	return *v, true
}

// OldState returns the old "state" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldState(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldState is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldState requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldState: %w", err)
	}
	return oldValue.State, nil
}

// AddState adds i to the "state" field.
func (m *UserMutation) AddState(i int64) {
	if m.addstate != nil {
		*m.addstate += i
	} else {
		m.addstate = &i
	}
}

// AddedState returns the value that was added to the "state" field in this mutation.
func (m *UserMutation) AddedState() (r int64, exists bool) {
	v := m.addstate
	if v == nil {
		return
	}
	return *v, true
}

// ResetState resets all changes to the "state" field.
func (m *UserMutation) ResetState() {
	m.state = nil
	m.addstate = nil
}

// AddFakeTokenIDs adds the "fake_tokens" edge to the FakeToken entity by ids.
func (m *UserMutation) AddFakeTokenIDs(ids ...int64) {
	if m.fake_tokens == nil {
		m.fake_tokens = make(map[int64]struct{})
	}
	for i := range ids {
		m.fake_tokens[ids[i]] = struct{}{}
	}
}

// ClearFakeTokens clears the "fake_tokens" edge to the FakeToken entity.
func (m *UserMutation) ClearFakeTokens() {
	m.clearedfake_tokens = true
}

// FakeTokensCleared reports if the "fake_tokens" edge to the FakeToken entity was cleared.
func (m *UserMutation) FakeTokensCleared() bool {
	return m.clearedfake_tokens
}

// RemoveFakeTokenIDs removes the "fake_tokens" edge to the FakeToken entity by IDs.
func (m *UserMutation) RemoveFakeTokenIDs(ids ...int64) {
	if m.removedfake_tokens == nil {
		m.removedfake_tokens = make(map[int64]struct{})
	}
	for i := range ids {
		delete(m.fake_tokens, ids[i])
		m.removedfake_tokens[ids[i]] = struct{}{}
	}
}

// RemovedFakeTokens returns the removed IDs of the "fake_tokens" edge to the FakeToken entity.
func (m *UserMutation) RemovedFakeTokensIDs() (ids []int64) {
	for id := range m.removedfake_tokens {
		ids = append(ids, id)
	}
	return
}

// FakeTokensIDs returns the "fake_tokens" edge IDs in the mutation.
func (m *UserMutation) FakeTokensIDs() (ids []int64) {
	for id := range m.fake_tokens {
		ids = append(ids, id)
	}
	return
}

// ResetFakeTokens resets all changes to the "fake_tokens" edge.
func (m *UserMutation) ResetFakeTokens() {
	m.fake_tokens = nil
	m.clearedfake_tokens = false
	m.removedfake_tokens = nil
}

// AddGrantedProviderAccountIDs adds the "granted_provider_accounts" edge to the UserGrantedProviderAccount entity by ids.
func (m *UserMutation) AddGrantedProviderAccountIDs(ids ...int64) {
	if m.granted_provider_accounts == nil {
		m.granted_provider_accounts = make(map[int64]struct{})
	}
	for i := range ids {
		m.granted_provider_accounts[ids[i]] = struct{}{}
	}
}

// ClearGrantedProviderAccounts clears the "granted_provider_accounts" edge to the UserGrantedProviderAccount entity.
func (m *UserMutation) ClearGrantedProviderAccounts() {
	m.clearedgranted_provider_accounts = true
}

// GrantedProviderAccountsCleared reports if the "granted_provider_accounts" edge to the UserGrantedProviderAccount entity was cleared.
func (m *UserMutation) GrantedProviderAccountsCleared() bool {
	return m.clearedgranted_provider_accounts
}

// RemoveGrantedProviderAccountIDs removes the "granted_provider_accounts" edge to the UserGrantedProviderAccount entity by IDs.
func (m *UserMutation) RemoveGrantedProviderAccountIDs(ids ...int64) {
	if m.removedgranted_provider_accounts == nil {
		m.removedgranted_provider_accounts = make(map[int64]struct{})
	}
	for i := range ids {
		delete(m.granted_provider_accounts, ids[i])
		m.removedgranted_provider_accounts[ids[i]] = struct{}{}
	}
}

// RemovedGrantedProviderAccounts returns the removed IDs of the "granted_provider_accounts" edge to the UserGrantedProviderAccount entity.
func (m *UserMutation) RemovedGrantedProviderAccountsIDs() (ids []int64) {
	for id := range m.removedgranted_provider_accounts {
		ids = append(ids, id)
	}
	return
}

// GrantedProviderAccountsIDs returns the "granted_provider_accounts" edge IDs in the mutation.
func (m *UserMutation) GrantedProviderAccountsIDs() (ids []int64) {
	for id := range m.granted_provider_accounts {
		ids = append(ids, id)
	}
	return
}

// ResetGrantedProviderAccounts resets all changes to the "granted_provider_accounts" edge.
func (m *UserMutation) ResetGrantedProviderAccounts() {
	m.granted_provider_accounts = nil
	m.clearedgranted_provider_accounts = false
	m.removedgranted_provider_accounts = nil
}

// Where appends a list predicates to the UserMutation builder.
func (m *UserMutation) Where(ps ...predicate.User) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the UserMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *UserMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.User, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *UserMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UserMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (User).
func (m *UserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.created_at != nil {
		fields = append(fields, user.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, user.FieldUpdatedAt)
	}
	if m.oauth_state_token != nil {
		fields = append(fields, user.FieldOauthStateToken)
	}
	if m.state != nil {
		fields = append(fields, user.FieldState)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case user.FieldCreatedAt:
		return m.CreatedAt()
	case user.FieldUpdatedAt:
		return m.UpdatedAt()
	case user.FieldOauthStateToken:
		return m.OauthStateToken()
	case user.FieldState:
		return m.State()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case user.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case user.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case user.FieldOauthStateToken:
		return m.OldOauthStateToken(ctx)
	case user.FieldState:
		return m.OldState(ctx)
	}
	return nil, fmt.Errorf("unknown User field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case user.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case user.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case user.FieldOauthStateToken:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOauthStateToken(v)
		return nil
	case user.FieldState:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetState(v)
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserMutation) AddedFields() []string {
	var fields []string
	if m.addstate != nil {
		fields = append(fields, user.FieldState)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case user.FieldState:
		return m.AddedState()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) AddField(name string, value ent.Value) error {
	switch name {
	case user.FieldState:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddState(v)
		return nil
	}
	return fmt.Errorf("unknown User numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserMutation) ClearField(name string) error {
	return fmt.Errorf("unknown User nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserMutation) ResetField(name string) error {
	switch name {
	case user.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case user.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case user.FieldOauthStateToken:
		m.ResetOauthStateToken()
		return nil
	case user.FieldState:
		m.ResetState()
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.fake_tokens != nil {
		edges = append(edges, user.EdgeFakeTokens)
	}
	if m.granted_provider_accounts != nil {
		edges = append(edges, user.EdgeGrantedProviderAccounts)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeFakeTokens:
		ids := make([]ent.Value, 0, len(m.fake_tokens))
		for id := range m.fake_tokens {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeGrantedProviderAccounts:
		ids := make([]ent.Value, 0, len(m.granted_provider_accounts))
		for id := range m.granted_provider_accounts {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedfake_tokens != nil {
		edges = append(edges, user.EdgeFakeTokens)
	}
	if m.removedgranted_provider_accounts != nil {
		edges = append(edges, user.EdgeGrantedProviderAccounts)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeFakeTokens:
		ids := make([]ent.Value, 0, len(m.removedfake_tokens))
		for id := range m.removedfake_tokens {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeGrantedProviderAccounts:
		ids := make([]ent.Value, 0, len(m.removedgranted_provider_accounts))
		for id := range m.removedgranted_provider_accounts {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedfake_tokens {
		edges = append(edges, user.EdgeFakeTokens)
	}
	if m.clearedgranted_provider_accounts {
		edges = append(edges, user.EdgeGrantedProviderAccounts)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserMutation) EdgeCleared(name string) bool {
	switch name {
	case user.EdgeFakeTokens:
		return m.clearedfake_tokens
	case user.EdgeGrantedProviderAccounts:
		return m.clearedgranted_provider_accounts
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown User unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserMutation) ResetEdge(name string) error {
	switch name {
	case user.EdgeFakeTokens:
		m.ResetFakeTokens()
		return nil
	case user.EdgeGrantedProviderAccounts:
		m.ResetGrantedProviderAccounts()
		return nil
	}
	return fmt.Errorf("unknown User edge %s", name)
}

// UserGrantedProviderAccountMutation represents an operation that mutates the UserGrantedProviderAccount nodes in the graph.
type UserGrantedProviderAccountMutation struct {
	config
	op                      Op
	typ                     string
	id                      *int64
	clearedFields           map[string]struct{}
	user                    *int64
	cleareduser             bool
	provider_account        *int64
	clearedprovider_account bool
	done                    bool
	oldValue                func(context.Context) (*UserGrantedProviderAccount, error)
	predicates              []predicate.UserGrantedProviderAccount
}

var _ ent.Mutation = (*UserGrantedProviderAccountMutation)(nil)

// usergrantedprovideraccountOption allows management of the mutation configuration using functional options.
type usergrantedprovideraccountOption func(*UserGrantedProviderAccountMutation)

// newUserGrantedProviderAccountMutation creates new mutation for the UserGrantedProviderAccount entity.
func newUserGrantedProviderAccountMutation(c config, op Op, opts ...usergrantedprovideraccountOption) *UserGrantedProviderAccountMutation {
	m := &UserGrantedProviderAccountMutation{
		config:        c,
		op:            op,
		typ:           TypeUserGrantedProviderAccount,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserGrantedProviderAccountID sets the ID field of the mutation.
func withUserGrantedProviderAccountID(id int64) usergrantedprovideraccountOption {
	return func(m *UserGrantedProviderAccountMutation) {
		var (
			err   error
			once  sync.Once
			value *UserGrantedProviderAccount
		)
		m.oldValue = func(ctx context.Context) (*UserGrantedProviderAccount, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().UserGrantedProviderAccount.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUserGrantedProviderAccount sets the old UserGrantedProviderAccount of the mutation.
func withUserGrantedProviderAccount(node *UserGrantedProviderAccount) usergrantedprovideraccountOption {
	return func(m *UserGrantedProviderAccountMutation) {
		m.oldValue = func(context.Context) (*UserGrantedProviderAccount, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserGrantedProviderAccountMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserGrantedProviderAccountMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("dbrt: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of UserGrantedProviderAccount entities.
func (m *UserGrantedProviderAccountMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UserGrantedProviderAccountMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UserGrantedProviderAccountMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().UserGrantedProviderAccount.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUserID sets the "user_id" field.
func (m *UserGrantedProviderAccountMutation) SetUserID(i int64) {
	m.user = &i
}

// UserID returns the value of the "user_id" field in the mutation.
func (m *UserGrantedProviderAccountMutation) UserID() (r int64, exists bool) {
	v := m.user
	if v == nil {
		return
	}
	return *v, true
}

// OldUserID returns the old "user_id" field's value of the UserGrantedProviderAccount entity.
// If the UserGrantedProviderAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserGrantedProviderAccountMutation) OldUserID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserID: %w", err)
	}
	return oldValue.UserID, nil
}

// ResetUserID resets all changes to the "user_id" field.
func (m *UserGrantedProviderAccountMutation) ResetUserID() {
	m.user = nil
}

// SetProviderAccountID sets the "provider_account_id" field.
func (m *UserGrantedProviderAccountMutation) SetProviderAccountID(i int64) {
	m.provider_account = &i
}

// ProviderAccountID returns the value of the "provider_account_id" field in the mutation.
func (m *UserGrantedProviderAccountMutation) ProviderAccountID() (r int64, exists bool) {
	v := m.provider_account
	if v == nil {
		return
	}
	return *v, true
}

// OldProviderAccountID returns the old "provider_account_id" field's value of the UserGrantedProviderAccount entity.
// If the UserGrantedProviderAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserGrantedProviderAccountMutation) OldProviderAccountID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProviderAccountID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProviderAccountID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProviderAccountID: %w", err)
	}
	return oldValue.ProviderAccountID, nil
}

// ResetProviderAccountID resets all changes to the "provider_account_id" field.
func (m *UserGrantedProviderAccountMutation) ResetProviderAccountID() {
	m.provider_account = nil
}

// ClearUser clears the "user" edge to the User entity.
func (m *UserGrantedProviderAccountMutation) ClearUser() {
	m.cleareduser = true
	m.clearedFields[usergrantedprovideraccount.FieldUserID] = struct{}{}
}

// UserCleared reports if the "user" edge to the User entity was cleared.
func (m *UserGrantedProviderAccountMutation) UserCleared() bool {
	return m.cleareduser
}

// UserIDs returns the "user" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// UserID instead. It exists only for internal usage by the builders.
func (m *UserGrantedProviderAccountMutation) UserIDs() (ids []int64) {
	if id := m.user; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetUser resets all changes to the "user" edge.
func (m *UserGrantedProviderAccountMutation) ResetUser() {
	m.user = nil
	m.cleareduser = false
}

// ClearProviderAccount clears the "provider_account" edge to the ProviderAccount entity.
func (m *UserGrantedProviderAccountMutation) ClearProviderAccount() {
	m.clearedprovider_account = true
	m.clearedFields[usergrantedprovideraccount.FieldProviderAccountID] = struct{}{}
}

// ProviderAccountCleared reports if the "provider_account" edge to the ProviderAccount entity was cleared.
func (m *UserGrantedProviderAccountMutation) ProviderAccountCleared() bool {
	return m.clearedprovider_account
}

// ProviderAccountIDs returns the "provider_account" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// ProviderAccountID instead. It exists only for internal usage by the builders.
func (m *UserGrantedProviderAccountMutation) ProviderAccountIDs() (ids []int64) {
	if id := m.provider_account; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetProviderAccount resets all changes to the "provider_account" edge.
func (m *UserGrantedProviderAccountMutation) ResetProviderAccount() {
	m.provider_account = nil
	m.clearedprovider_account = false
}

// Where appends a list predicates to the UserGrantedProviderAccountMutation builder.
func (m *UserGrantedProviderAccountMutation) Where(ps ...predicate.UserGrantedProviderAccount) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the UserGrantedProviderAccountMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *UserGrantedProviderAccountMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.UserGrantedProviderAccount, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *UserGrantedProviderAccountMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UserGrantedProviderAccountMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (UserGrantedProviderAccount).
func (m *UserGrantedProviderAccountMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserGrantedProviderAccountMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.user != nil {
		fields = append(fields, usergrantedprovideraccount.FieldUserID)
	}
	if m.provider_account != nil {
		fields = append(fields, usergrantedprovideraccount.FieldProviderAccountID)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserGrantedProviderAccountMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case usergrantedprovideraccount.FieldUserID:
		return m.UserID()
	case usergrantedprovideraccount.FieldProviderAccountID:
		return m.ProviderAccountID()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserGrantedProviderAccountMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case usergrantedprovideraccount.FieldUserID:
		return m.OldUserID(ctx)
	case usergrantedprovideraccount.FieldProviderAccountID:
		return m.OldProviderAccountID(ctx)
	}
	return nil, fmt.Errorf("unknown UserGrantedProviderAccount field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserGrantedProviderAccountMutation) SetField(name string, value ent.Value) error {
	switch name {
	case usergrantedprovideraccount.FieldUserID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserID(v)
		return nil
	case usergrantedprovideraccount.FieldProviderAccountID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProviderAccountID(v)
		return nil
	}
	return fmt.Errorf("unknown UserGrantedProviderAccount field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserGrantedProviderAccountMutation) AddedFields() []string {
	var fields []string
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserGrantedProviderAccountMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserGrantedProviderAccountMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown UserGrantedProviderAccount numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserGrantedProviderAccountMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserGrantedProviderAccountMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserGrantedProviderAccountMutation) ClearField(name string) error {
	return fmt.Errorf("unknown UserGrantedProviderAccount nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserGrantedProviderAccountMutation) ResetField(name string) error {
	switch name {
	case usergrantedprovideraccount.FieldUserID:
		m.ResetUserID()
		return nil
	case usergrantedprovideraccount.FieldProviderAccountID:
		m.ResetProviderAccountID()
		return nil
	}
	return fmt.Errorf("unknown UserGrantedProviderAccount field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserGrantedProviderAccountMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.user != nil {
		edges = append(edges, usergrantedprovideraccount.EdgeUser)
	}
	if m.provider_account != nil {
		edges = append(edges, usergrantedprovideraccount.EdgeProviderAccount)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserGrantedProviderAccountMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case usergrantedprovideraccount.EdgeUser:
		if id := m.user; id != nil {
			return []ent.Value{*id}
		}
	case usergrantedprovideraccount.EdgeProviderAccount:
		if id := m.provider_account; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserGrantedProviderAccountMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserGrantedProviderAccountMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserGrantedProviderAccountMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.cleareduser {
		edges = append(edges, usergrantedprovideraccount.EdgeUser)
	}
	if m.clearedprovider_account {
		edges = append(edges, usergrantedprovideraccount.EdgeProviderAccount)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserGrantedProviderAccountMutation) EdgeCleared(name string) bool {
	switch name {
	case usergrantedprovideraccount.EdgeUser:
		return m.cleareduser
	case usergrantedprovideraccount.EdgeProviderAccount:
		return m.clearedprovider_account
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserGrantedProviderAccountMutation) ClearEdge(name string) error {
	switch name {
	case usergrantedprovideraccount.EdgeUser:
		m.ClearUser()
		return nil
	case usergrantedprovideraccount.EdgeProviderAccount:
		m.ClearProviderAccount()
		return nil
	}
	return fmt.Errorf("unknown UserGrantedProviderAccount unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserGrantedProviderAccountMutation) ResetEdge(name string) error {
	switch name {
	case usergrantedprovideraccount.EdgeUser:
		m.ResetUser()
		return nil
	case usergrantedprovideraccount.EdgeProviderAccount:
		m.ResetProviderAccount()
		return nil
	}
	return fmt.Errorf("unknown UserGrantedProviderAccount edge %s", name)
}
