// Code generated by ent, DO NOT EDIT.

package dbrt

import (
	"cocoq/server/database/dbrt/faketoken"
	"cocoq/server/database/dbrt/predicate"
	"cocoq/server/database/dbrt/provideraccount"
	"cocoq/server/database/dbrt/usergrantedprovideraccount"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProviderAccountQuery is the builder for querying ProviderAccount entities.
type ProviderAccountQuery struct {
	config
	ctx              *QueryContext
	order            []provideraccount.OrderOption
	inters           []Interceptor
	predicates       []predicate.ProviderAccount
	withFakeTokens   *FakeTokenQuery
	withGrantedUsers *UserGrantedProviderAccountQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProviderAccountQuery builder.
func (paq *ProviderAccountQuery) Where(ps ...predicate.ProviderAccount) *ProviderAccountQuery {
	paq.predicates = append(paq.predicates, ps...)
	return paq
}

// Limit the number of records to be returned by this query.
func (paq *ProviderAccountQuery) Limit(limit int) *ProviderAccountQuery {
	paq.ctx.Limit = &limit
	return paq
}

// Offset to start from.
func (paq *ProviderAccountQuery) Offset(offset int) *ProviderAccountQuery {
	paq.ctx.Offset = &offset
	return paq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (paq *ProviderAccountQuery) Unique(unique bool) *ProviderAccountQuery {
	paq.ctx.Unique = &unique
	return paq
}

// Order specifies how the records should be ordered.
func (paq *ProviderAccountQuery) Order(o ...provideraccount.OrderOption) *ProviderAccountQuery {
	paq.order = append(paq.order, o...)
	return paq
}

// QueryFakeTokens chains the current query on the "fake_tokens" edge.
func (paq *ProviderAccountQuery) QueryFakeTokens() *FakeTokenQuery {
	query := (&FakeTokenClient{config: paq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := paq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := paq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(provideraccount.Table, provideraccount.FieldID, selector),
			sqlgraph.To(faketoken.Table, faketoken.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, provideraccount.FakeTokensTable, provideraccount.FakeTokensColumn),
		)
		fromU = sqlgraph.SetNeighbors(paq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGrantedUsers chains the current query on the "granted_users" edge.
func (paq *ProviderAccountQuery) QueryGrantedUsers() *UserGrantedProviderAccountQuery {
	query := (&UserGrantedProviderAccountClient{config: paq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := paq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := paq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(provideraccount.Table, provideraccount.FieldID, selector),
			sqlgraph.To(usergrantedprovideraccount.Table, usergrantedprovideraccount.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, provideraccount.GrantedUsersTable, provideraccount.GrantedUsersColumn),
		)
		fromU = sqlgraph.SetNeighbors(paq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProviderAccount entity from the query.
// Returns a *NotFoundError when no ProviderAccount was found.
func (paq *ProviderAccountQuery) First(ctx context.Context) (*ProviderAccount, error) {
	nodes, err := paq.Limit(1).All(setContextOp(ctx, paq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{provideraccount.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (paq *ProviderAccountQuery) FirstX(ctx context.Context) *ProviderAccount {
	node, err := paq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProviderAccount ID from the query.
// Returns a *NotFoundError when no ProviderAccount ID was found.
func (paq *ProviderAccountQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = paq.Limit(1).IDs(setContextOp(ctx, paq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{provideraccount.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (paq *ProviderAccountQuery) FirstIDX(ctx context.Context) int64 {
	id, err := paq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProviderAccount entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProviderAccount entity is found.
// Returns a *NotFoundError when no ProviderAccount entities are found.
func (paq *ProviderAccountQuery) Only(ctx context.Context) (*ProviderAccount, error) {
	nodes, err := paq.Limit(2).All(setContextOp(ctx, paq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{provideraccount.Label}
	default:
		return nil, &NotSingularError{provideraccount.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (paq *ProviderAccountQuery) OnlyX(ctx context.Context) *ProviderAccount {
	node, err := paq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProviderAccount ID in the query.
// Returns a *NotSingularError when more than one ProviderAccount ID is found.
// Returns a *NotFoundError when no entities are found.
func (paq *ProviderAccountQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = paq.Limit(2).IDs(setContextOp(ctx, paq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{provideraccount.Label}
	default:
		err = &NotSingularError{provideraccount.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (paq *ProviderAccountQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := paq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProviderAccounts.
func (paq *ProviderAccountQuery) All(ctx context.Context) ([]*ProviderAccount, error) {
	ctx = setContextOp(ctx, paq.ctx, ent.OpQueryAll)
	if err := paq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProviderAccount, *ProviderAccountQuery]()
	return withInterceptors[[]*ProviderAccount](ctx, paq, qr, paq.inters)
}

// AllX is like All, but panics if an error occurs.
func (paq *ProviderAccountQuery) AllX(ctx context.Context) []*ProviderAccount {
	nodes, err := paq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProviderAccount IDs.
func (paq *ProviderAccountQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if paq.ctx.Unique == nil && paq.path != nil {
		paq.Unique(true)
	}
	ctx = setContextOp(ctx, paq.ctx, ent.OpQueryIDs)
	if err = paq.Select(provideraccount.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (paq *ProviderAccountQuery) IDsX(ctx context.Context) []int64 {
	ids, err := paq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (paq *ProviderAccountQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, paq.ctx, ent.OpQueryCount)
	if err := paq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, paq, querierCount[*ProviderAccountQuery](), paq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (paq *ProviderAccountQuery) CountX(ctx context.Context) int {
	count, err := paq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (paq *ProviderAccountQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, paq.ctx, ent.OpQueryExist)
	switch _, err := paq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("dbrt: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (paq *ProviderAccountQuery) ExistX(ctx context.Context) bool {
	exist, err := paq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProviderAccountQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (paq *ProviderAccountQuery) Clone() *ProviderAccountQuery {
	if paq == nil {
		return nil
	}
	return &ProviderAccountQuery{
		config:           paq.config,
		ctx:              paq.ctx.Clone(),
		order:            append([]provideraccount.OrderOption{}, paq.order...),
		inters:           append([]Interceptor{}, paq.inters...),
		predicates:       append([]predicate.ProviderAccount{}, paq.predicates...),
		withFakeTokens:   paq.withFakeTokens.Clone(),
		withGrantedUsers: paq.withGrantedUsers.Clone(),
		// clone intermediate query.
		sql:  paq.sql.Clone(),
		path: paq.path,
	}
}

// WithFakeTokens tells the query-builder to eager-load the nodes that are connected to
// the "fake_tokens" edge. The optional arguments are used to configure the query builder of the edge.
func (paq *ProviderAccountQuery) WithFakeTokens(opts ...func(*FakeTokenQuery)) *ProviderAccountQuery {
	query := (&FakeTokenClient{config: paq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	paq.withFakeTokens = query
	return paq
}

// WithGrantedUsers tells the query-builder to eager-load the nodes that are connected to
// the "granted_users" edge. The optional arguments are used to configure the query builder of the edge.
func (paq *ProviderAccountQuery) WithGrantedUsers(opts ...func(*UserGrantedProviderAccountQuery)) *ProviderAccountQuery {
	query := (&UserGrantedProviderAccountClient{config: paq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	paq.withGrantedUsers = query
	return paq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProviderAccount.Query().
//		GroupBy(provideraccount.FieldCreatedAt).
//		Aggregate(dbrt.Count()).
//		Scan(ctx, &v)
func (paq *ProviderAccountQuery) GroupBy(field string, fields ...string) *ProviderAccountGroupBy {
	paq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProviderAccountGroupBy{build: paq}
	grbuild.flds = &paq.ctx.Fields
	grbuild.label = provideraccount.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ProviderAccount.Query().
//		Select(provideraccount.FieldCreatedAt).
//		Scan(ctx, &v)
func (paq *ProviderAccountQuery) Select(fields ...string) *ProviderAccountSelect {
	paq.ctx.Fields = append(paq.ctx.Fields, fields...)
	sbuild := &ProviderAccountSelect{ProviderAccountQuery: paq}
	sbuild.label = provideraccount.Label
	sbuild.flds, sbuild.scan = &paq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProviderAccountSelect configured with the given aggregations.
func (paq *ProviderAccountQuery) Aggregate(fns ...AggregateFunc) *ProviderAccountSelect {
	return paq.Select().Aggregate(fns...)
}

func (paq *ProviderAccountQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range paq.inters {
		if inter == nil {
			return fmt.Errorf("dbrt: uninitialized interceptor (forgotten import dbrt/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, paq); err != nil {
				return err
			}
		}
	}
	for _, f := range paq.ctx.Fields {
		if !provideraccount.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("dbrt: invalid field %q for query", f)}
		}
	}
	if paq.path != nil {
		prev, err := paq.path(ctx)
		if err != nil {
			return err
		}
		paq.sql = prev
	}
	return nil
}

func (paq *ProviderAccountQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProviderAccount, error) {
	var (
		nodes       = []*ProviderAccount{}
		_spec       = paq.querySpec()
		loadedTypes = [2]bool{
			paq.withFakeTokens != nil,
			paq.withGrantedUsers != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProviderAccount).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProviderAccount{config: paq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, paq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := paq.withFakeTokens; query != nil {
		if err := paq.loadFakeTokens(ctx, query, nodes,
			func(n *ProviderAccount) { n.Edges.FakeTokens = []*FakeToken{} },
			func(n *ProviderAccount, e *FakeToken) { n.Edges.FakeTokens = append(n.Edges.FakeTokens, e) }); err != nil {
			return nil, err
		}
	}
	if query := paq.withGrantedUsers; query != nil {
		if err := paq.loadGrantedUsers(ctx, query, nodes,
			func(n *ProviderAccount) { n.Edges.GrantedUsers = []*UserGrantedProviderAccount{} },
			func(n *ProviderAccount, e *UserGrantedProviderAccount) {
				n.Edges.GrantedUsers = append(n.Edges.GrantedUsers, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (paq *ProviderAccountQuery) loadFakeTokens(ctx context.Context, query *FakeTokenQuery, nodes []*ProviderAccount, init func(*ProviderAccount), assign func(*ProviderAccount, *FakeToken)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*ProviderAccount)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(faketoken.FieldProviderAccountID)
	}
	query.Where(predicate.FakeToken(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(provideraccount.FakeTokensColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ProviderAccountID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "provider_account_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (paq *ProviderAccountQuery) loadGrantedUsers(ctx context.Context, query *UserGrantedProviderAccountQuery, nodes []*ProviderAccount, init func(*ProviderAccount), assign func(*ProviderAccount, *UserGrantedProviderAccount)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*ProviderAccount)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(usergrantedprovideraccount.FieldProviderAccountID)
	}
	query.Where(predicate.UserGrantedProviderAccount(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(provideraccount.GrantedUsersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ProviderAccountID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "provider_account_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (paq *ProviderAccountQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := paq.querySpec()
	_spec.Node.Columns = paq.ctx.Fields
	if len(paq.ctx.Fields) > 0 {
		_spec.Unique = paq.ctx.Unique != nil && *paq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, paq.driver, _spec)
}

func (paq *ProviderAccountQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(provideraccount.Table, provideraccount.Columns, sqlgraph.NewFieldSpec(provideraccount.FieldID, field.TypeInt64))
	_spec.From = paq.sql
	if unique := paq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if paq.path != nil {
		_spec.Unique = true
	}
	if fields := paq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, provideraccount.FieldID)
		for i := range fields {
			if fields[i] != provideraccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := paq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := paq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := paq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := paq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (paq *ProviderAccountQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(paq.driver.Dialect())
	t1 := builder.Table(provideraccount.Table)
	columns := paq.ctx.Fields
	if len(columns) == 0 {
		columns = provideraccount.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if paq.sql != nil {
		selector = paq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if paq.ctx.Unique != nil && *paq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range paq.predicates {
		p(selector)
	}
	for _, p := range paq.order {
		p(selector)
	}
	if offset := paq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := paq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProviderAccountGroupBy is the group-by builder for ProviderAccount entities.
type ProviderAccountGroupBy struct {
	selector
	build *ProviderAccountQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pagb *ProviderAccountGroupBy) Aggregate(fns ...AggregateFunc) *ProviderAccountGroupBy {
	pagb.fns = append(pagb.fns, fns...)
	return pagb
}

// Scan applies the selector query and scans the result into the given value.
func (pagb *ProviderAccountGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pagb.build.ctx, ent.OpQueryGroupBy)
	if err := pagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProviderAccountQuery, *ProviderAccountGroupBy](ctx, pagb.build, pagb, pagb.build.inters, v)
}

func (pagb *ProviderAccountGroupBy) sqlScan(ctx context.Context, root *ProviderAccountQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pagb.fns))
	for _, fn := range pagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pagb.flds)+len(pagb.fns))
		for _, f := range *pagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProviderAccountSelect is the builder for selecting fields of ProviderAccount entities.
type ProviderAccountSelect struct {
	*ProviderAccountQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pas *ProviderAccountSelect) Aggregate(fns ...AggregateFunc) *ProviderAccountSelect {
	pas.fns = append(pas.fns, fns...)
	return pas
}

// Scan applies the selector query and scans the result into the given value.
func (pas *ProviderAccountSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pas.ctx, ent.OpQuerySelect)
	if err := pas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProviderAccountQuery, *ProviderAccountSelect](ctx, pas.ProviderAccountQuery, pas, pas.inters, v)
}

func (pas *ProviderAccountSelect) sqlScan(ctx context.Context, root *ProviderAccountQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pas.fns))
	for _, fn := range pas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
