// Code generated by ent, DO NOT EDIT.

package dbrt

import (
	"cocoq/server/database/dbrt/provideraccount"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ProviderAccount is the model entity for the ProviderAccount schema.
type ProviderAccount struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// AccountUUID holds the value of the "account_uuid" field.
	AccountUUID string `json:"account_uuid,omitempty"`
	// AccessToken holds the value of the "access_token" field.
	AccessToken string `json:"access_token,omitempty"`
	// RefreshToken holds the value of the "refresh_token" field.
	RefreshToken string `json:"refresh_token,omitempty"`
	// Credentials holds the value of the "credentials" field.
	Credentials string `json:"credentials,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProviderAccountQuery when eager-loading is set.
	Edges        ProviderAccountEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProviderAccountEdges holds the relations/edges for other nodes in the graph.
type ProviderAccountEdges struct {
	// FakeTokens holds the value of the fake_tokens edge.
	FakeTokens []*FakeToken `json:"fake_tokens,omitempty"`
	// GrantedUsers holds the value of the granted_users edge.
	GrantedUsers []*UserGrantedProviderAccount `json:"granted_users,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// FakeTokensOrErr returns the FakeTokens value or an error if the edge
// was not loaded in eager-loading.
func (e ProviderAccountEdges) FakeTokensOrErr() ([]*FakeToken, error) {
	if e.loadedTypes[0] {
		return e.FakeTokens, nil
	}
	return nil, &NotLoadedError{edge: "fake_tokens"}
}

// GrantedUsersOrErr returns the GrantedUsers value or an error if the edge
// was not loaded in eager-loading.
func (e ProviderAccountEdges) GrantedUsersOrErr() ([]*UserGrantedProviderAccount, error) {
	if e.loadedTypes[1] {
		return e.GrantedUsers, nil
	}
	return nil, &NotLoadedError{edge: "granted_users"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProviderAccount) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case provideraccount.FieldID:
			values[i] = new(sql.NullInt64)
		case provideraccount.FieldAccountUUID, provideraccount.FieldAccessToken, provideraccount.FieldRefreshToken, provideraccount.FieldCredentials:
			values[i] = new(sql.NullString)
		case provideraccount.FieldCreatedAt, provideraccount.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProviderAccount fields.
func (pa *ProviderAccount) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case provideraccount.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pa.ID = int64(value.Int64)
		case provideraccount.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				pa.CreatedAt = value.Time
			}
		case provideraccount.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				pa.UpdatedAt = value.Time
			}
		case provideraccount.FieldAccountUUID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_uuid", values[i])
			} else if value.Valid {
				pa.AccountUUID = value.String
			}
		case provideraccount.FieldAccessToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_token", values[i])
			} else if value.Valid {
				pa.AccessToken = value.String
			}
		case provideraccount.FieldRefreshToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_token", values[i])
			} else if value.Valid {
				pa.RefreshToken = value.String
			}
		case provideraccount.FieldCredentials:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field credentials", values[i])
			} else if value.Valid {
				pa.Credentials = value.String
			}
		default:
			pa.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProviderAccount.
// This includes values selected through modifiers, order, etc.
func (pa *ProviderAccount) Value(name string) (ent.Value, error) {
	return pa.selectValues.Get(name)
}

// QueryFakeTokens queries the "fake_tokens" edge of the ProviderAccount entity.
func (pa *ProviderAccount) QueryFakeTokens() *FakeTokenQuery {
	return NewProviderAccountClient(pa.config).QueryFakeTokens(pa)
}

// QueryGrantedUsers queries the "granted_users" edge of the ProviderAccount entity.
func (pa *ProviderAccount) QueryGrantedUsers() *UserGrantedProviderAccountQuery {
	return NewProviderAccountClient(pa.config).QueryGrantedUsers(pa)
}

// Update returns a builder for updating this ProviderAccount.
// Note that you need to call ProviderAccount.Unwrap() before calling this method if this ProviderAccount
// was returned from a transaction, and the transaction was committed or rolled back.
func (pa *ProviderAccount) Update() *ProviderAccountUpdateOne {
	return NewProviderAccountClient(pa.config).UpdateOne(pa)
}

// Unwrap unwraps the ProviderAccount entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pa *ProviderAccount) Unwrap() *ProviderAccount {
	_tx, ok := pa.config.driver.(*txDriver)
	if !ok {
		panic("dbrt: ProviderAccount is not a transactional entity")
	}
	pa.config.driver = _tx.drv
	return pa
}

// String implements the fmt.Stringer.
func (pa *ProviderAccount) String() string {
	var builder strings.Builder
	builder.WriteString("ProviderAccount(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pa.ID))
	builder.WriteString("created_at=")
	builder.WriteString(pa.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(pa.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("account_uuid=")
	builder.WriteString(pa.AccountUUID)
	builder.WriteString(", ")
	builder.WriteString("access_token=")
	builder.WriteString(pa.AccessToken)
	builder.WriteString(", ")
	builder.WriteString("refresh_token=")
	builder.WriteString(pa.RefreshToken)
	builder.WriteString(", ")
	builder.WriteString("credentials=")
	builder.WriteString(pa.Credentials)
	builder.WriteByte(')')
	return builder.String()
}

// ProviderAccounts is a parsable slice of ProviderAccount.
type ProviderAccounts []*ProviderAccount
