// Code generated by ent, DO NOT EDIT.

package dbrt

import (
	"cocoq/server/database/dbrt/faketoken"
	"cocoq/server/database/dbrt/provideraccount"
	"cocoq/server/database/dbrt/usergrantedprovideraccount"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProviderAccountCreate is the builder for creating a ProviderAccount entity.
type ProviderAccountCreate struct {
	config
	mutation *ProviderAccountMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (pac *ProviderAccountCreate) SetCreatedAt(t time.Time) *ProviderAccountCreate {
	pac.mutation.SetCreatedAt(t)
	return pac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pac *ProviderAccountCreate) SetNillableCreatedAt(t *time.Time) *ProviderAccountCreate {
	if t != nil {
		pac.SetCreatedAt(*t)
	}
	return pac
}

// SetUpdatedAt sets the "updated_at" field.
func (pac *ProviderAccountCreate) SetUpdatedAt(t time.Time) *ProviderAccountCreate {
	pac.mutation.SetUpdatedAt(t)
	return pac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pac *ProviderAccountCreate) SetNillableUpdatedAt(t *time.Time) *ProviderAccountCreate {
	if t != nil {
		pac.SetUpdatedAt(*t)
	}
	return pac
}

// SetAccountUUID sets the "account_uuid" field.
func (pac *ProviderAccountCreate) SetAccountUUID(s string) *ProviderAccountCreate {
	pac.mutation.SetAccountUUID(s)
	return pac
}

// SetAccessToken sets the "access_token" field.
func (pac *ProviderAccountCreate) SetAccessToken(s string) *ProviderAccountCreate {
	pac.mutation.SetAccessToken(s)
	return pac
}

// SetRefreshToken sets the "refresh_token" field.
func (pac *ProviderAccountCreate) SetRefreshToken(s string) *ProviderAccountCreate {
	pac.mutation.SetRefreshToken(s)
	return pac
}

// SetCredentials sets the "credentials" field.
func (pac *ProviderAccountCreate) SetCredentials(s string) *ProviderAccountCreate {
	pac.mutation.SetCredentials(s)
	return pac
}

// SetID sets the "id" field.
func (pac *ProviderAccountCreate) SetID(i int64) *ProviderAccountCreate {
	pac.mutation.SetID(i)
	return pac
}

// AddFakeTokenIDs adds the "fake_tokens" edge to the FakeToken entity by IDs.
func (pac *ProviderAccountCreate) AddFakeTokenIDs(ids ...int64) *ProviderAccountCreate {
	pac.mutation.AddFakeTokenIDs(ids...)
	return pac
}

// AddFakeTokens adds the "fake_tokens" edges to the FakeToken entity.
func (pac *ProviderAccountCreate) AddFakeTokens(f ...*FakeToken) *ProviderAccountCreate {
	ids := make([]int64, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return pac.AddFakeTokenIDs(ids...)
}

// AddGrantedUserIDs adds the "granted_users" edge to the UserGrantedProviderAccount entity by IDs.
func (pac *ProviderAccountCreate) AddGrantedUserIDs(ids ...int64) *ProviderAccountCreate {
	pac.mutation.AddGrantedUserIDs(ids...)
	return pac
}

// AddGrantedUsers adds the "granted_users" edges to the UserGrantedProviderAccount entity.
func (pac *ProviderAccountCreate) AddGrantedUsers(u ...*UserGrantedProviderAccount) *ProviderAccountCreate {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return pac.AddGrantedUserIDs(ids...)
}

// Mutation returns the ProviderAccountMutation object of the builder.
func (pac *ProviderAccountCreate) Mutation() *ProviderAccountMutation {
	return pac.mutation
}

// Save creates the ProviderAccount in the database.
func (pac *ProviderAccountCreate) Save(ctx context.Context) (*ProviderAccount, error) {
	pac.defaults()
	return withHooks(ctx, pac.sqlSave, pac.mutation, pac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pac *ProviderAccountCreate) SaveX(ctx context.Context) *ProviderAccount {
	v, err := pac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pac *ProviderAccountCreate) Exec(ctx context.Context) error {
	_, err := pac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pac *ProviderAccountCreate) ExecX(ctx context.Context) {
	if err := pac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pac *ProviderAccountCreate) defaults() {
	if _, ok := pac.mutation.CreatedAt(); !ok {
		v := provideraccount.DefaultCreatedAt()
		pac.mutation.SetCreatedAt(v)
	}
	if _, ok := pac.mutation.UpdatedAt(); !ok {
		v := provideraccount.DefaultUpdatedAt()
		pac.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pac *ProviderAccountCreate) check() error {
	if _, ok := pac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`dbrt: missing required field "ProviderAccount.created_at"`)}
	}
	if _, ok := pac.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`dbrt: missing required field "ProviderAccount.updated_at"`)}
	}
	if _, ok := pac.mutation.AccountUUID(); !ok {
		return &ValidationError{Name: "account_uuid", err: errors.New(`dbrt: missing required field "ProviderAccount.account_uuid"`)}
	}
	if _, ok := pac.mutation.AccessToken(); !ok {
		return &ValidationError{Name: "access_token", err: errors.New(`dbrt: missing required field "ProviderAccount.access_token"`)}
	}
	if _, ok := pac.mutation.RefreshToken(); !ok {
		return &ValidationError{Name: "refresh_token", err: errors.New(`dbrt: missing required field "ProviderAccount.refresh_token"`)}
	}
	if _, ok := pac.mutation.Credentials(); !ok {
		return &ValidationError{Name: "credentials", err: errors.New(`dbrt: missing required field "ProviderAccount.credentials"`)}
	}
	return nil
}

func (pac *ProviderAccountCreate) sqlSave(ctx context.Context) (*ProviderAccount, error) {
	if err := pac.check(); err != nil {
		return nil, err
	}
	_node, _spec := pac.createSpec()
	if err := sqlgraph.CreateNode(ctx, pac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	pac.mutation.id = &_node.ID
	pac.mutation.done = true
	return _node, nil
}

func (pac *ProviderAccountCreate) createSpec() (*ProviderAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &ProviderAccount{config: pac.config}
		_spec = sqlgraph.NewCreateSpec(provideraccount.Table, sqlgraph.NewFieldSpec(provideraccount.FieldID, field.TypeInt64))
	)
	if id, ok := pac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := pac.mutation.CreatedAt(); ok {
		_spec.SetField(provideraccount.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := pac.mutation.UpdatedAt(); ok {
		_spec.SetField(provideraccount.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := pac.mutation.AccountUUID(); ok {
		_spec.SetField(provideraccount.FieldAccountUUID, field.TypeString, value)
		_node.AccountUUID = value
	}
	if value, ok := pac.mutation.AccessToken(); ok {
		_spec.SetField(provideraccount.FieldAccessToken, field.TypeString, value)
		_node.AccessToken = value
	}
	if value, ok := pac.mutation.RefreshToken(); ok {
		_spec.SetField(provideraccount.FieldRefreshToken, field.TypeString, value)
		_node.RefreshToken = value
	}
	if value, ok := pac.mutation.Credentials(); ok {
		_spec.SetField(provideraccount.FieldCredentials, field.TypeString, value)
		_node.Credentials = value
	}
	if nodes := pac.mutation.FakeTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   provideraccount.FakeTokensTable,
			Columns: []string{provideraccount.FakeTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(faketoken.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pac.mutation.GrantedUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   provideraccount.GrantedUsersTable,
			Columns: []string{provideraccount.GrantedUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usergrantedprovideraccount.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProviderAccountCreateBulk is the builder for creating many ProviderAccount entities in bulk.
type ProviderAccountCreateBulk struct {
	config
	err      error
	builders []*ProviderAccountCreate
}

// Save creates the ProviderAccount entities in the database.
func (pacb *ProviderAccountCreateBulk) Save(ctx context.Context) ([]*ProviderAccount, error) {
	if pacb.err != nil {
		return nil, pacb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pacb.builders))
	nodes := make([]*ProviderAccount, len(pacb.builders))
	mutators := make([]Mutator, len(pacb.builders))
	for i := range pacb.builders {
		func(i int, root context.Context) {
			builder := pacb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProviderAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pacb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pacb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pacb *ProviderAccountCreateBulk) SaveX(ctx context.Context) []*ProviderAccount {
	v, err := pacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pacb *ProviderAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := pacb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pacb *ProviderAccountCreateBulk) ExecX(ctx context.Context) {
	if err := pacb.Exec(ctx); err != nil {
		panic(err)
	}
}
