// Code generated by ent, DO NOT EDIT.

package dbrt

import (
	"cocoq/server/database/dbrt/predicate"
	"cocoq/server/database/dbrt/provideraccount"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProviderAccountDelete is the builder for deleting a ProviderAccount entity.
type ProviderAccountDelete struct {
	config
	hooks    []Hook
	mutation *ProviderAccountMutation
}

// Where appends a list predicates to the ProviderAccountDelete builder.
func (pad *ProviderAccountDelete) Where(ps ...predicate.ProviderAccount) *ProviderAccountDelete {
	pad.mutation.Where(ps...)
	return pad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pad *ProviderAccountDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pad.sqlExec, pad.mutation, pad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pad *ProviderAccountDelete) ExecX(ctx context.Context) int {
	n, err := pad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pad *ProviderAccountDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(provideraccount.Table, sqlgraph.NewFieldSpec(provideraccount.FieldID, field.TypeInt64))
	if ps := pad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pad.mutation.done = true
	return affected, err
}

// ProviderAccountDeleteOne is the builder for deleting a single ProviderAccount entity.
type ProviderAccountDeleteOne struct {
	pad *ProviderAccountDelete
}

// Where appends a list predicates to the ProviderAccountDelete builder.
func (pado *ProviderAccountDeleteOne) Where(ps ...predicate.ProviderAccount) *ProviderAccountDeleteOne {
	pado.pad.mutation.Where(ps...)
	return pado
}

// Exec executes the deletion query.
func (pado *ProviderAccountDeleteOne) Exec(ctx context.Context) error {
	n, err := pado.pad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{provideraccount.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pado *ProviderAccountDeleteOne) ExecX(ctx context.Context) {
	if err := pado.Exec(ctx); err != nil {
		panic(err)
	}
}
