// Code generated by ent, DO NOT EDIT.

package dbrt

import (
	"time"

	"github.com/realityone/cocoq/server/database/dbrt/anthropicusage"
	"github.com/realityone/cocoq/server/database/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	anthropicusageFields := schema.AnthropicUsage{}.Fields()
	_ = anthropicusageFields
	// anthropicusageDescCreatedAt is the schema descriptor for created_at field.
	anthropicusageDescCreatedAt := anthropicusageFields[11].Descriptor()
	// anthropicusage.DefaultCreatedAt holds the default value on creation for the created_at field.
	anthropicusage.DefaultCreatedAt = anthropicusageDescCreatedAt.Default.(func() time.Time)
	// anthropicusageDescUpdatedAt is the schema descriptor for updated_at field.
	anthropicusageDescUpdatedAt := anthropicusageFields[12].Descriptor()
	// anthropicusage.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	anthropicusage.DefaultUpdatedAt = anthropicusageDescUpdatedAt.Default.(func() time.Time)
	// anthropicusage.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	anthropicusage.UpdateDefaultUpdatedAt = anthropicusageDescUpdatedAt.UpdateDefault.(func() time.Time)
}
