// Code generated by ent, DO NOT EDIT.

package dbrt

import (
	"cocoq/server/database/dbrt/provideraccount"
	"cocoq/server/database/dbrt/user"
	"cocoq/server/database/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	provideraccountMixin := schema.ProviderAccount{}.Mixin()
	provideraccountMixinFields0 := provideraccountMixin[0].Fields()
	_ = provideraccountMixinFields0
	provideraccountFields := schema.ProviderAccount{}.Fields()
	_ = provideraccountFields
	// provideraccountDescCreatedAt is the schema descriptor for created_at field.
	provideraccountDescCreatedAt := provideraccountMixinFields0[0].Descriptor()
	// provideraccount.DefaultCreatedAt holds the default value on creation for the created_at field.
	provideraccount.DefaultCreatedAt = provideraccountDescCreatedAt.Default.(func() time.Time)
	// provideraccountDescUpdatedAt is the schema descriptor for updated_at field.
	provideraccountDescUpdatedAt := provideraccountMixinFields0[1].Descriptor()
	// provideraccount.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	provideraccount.DefaultUpdatedAt = provideraccountDescUpdatedAt.Default.(func() time.Time)
	// provideraccount.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	provideraccount.UpdateDefaultUpdatedAt = provideraccountDescUpdatedAt.UpdateDefault.(func() time.Time)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
