// Code generated by ent, DO NOT EDIT.

package dbrt

import (
	"cocoq/server/database/dbrt/provideraccount"
	"cocoq/server/database/dbrt/user"
	"cocoq/server/database/dbrt/usergrantedprovideraccount"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UserGrantedProviderAccount is the model entity for the UserGrantedProviderAccount schema.
type UserGrantedProviderAccount struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// ProviderAccountID holds the value of the "provider_account_id" field.
	ProviderAccountID int64 `json:"provider_account_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserGrantedProviderAccountQuery when eager-loading is set.
	Edges        UserGrantedProviderAccountEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserGrantedProviderAccountEdges holds the relations/edges for other nodes in the graph.
type UserGrantedProviderAccountEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// ProviderAccount holds the value of the provider_account edge.
	ProviderAccount *ProviderAccount `json:"provider_account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserGrantedProviderAccountEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ProviderAccountOrErr returns the ProviderAccount value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserGrantedProviderAccountEdges) ProviderAccountOrErr() (*ProviderAccount, error) {
	if e.ProviderAccount != nil {
		return e.ProviderAccount, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: provideraccount.Label}
	}
	return nil, &NotLoadedError{edge: "provider_account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserGrantedProviderAccount) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usergrantedprovideraccount.FieldID, usergrantedprovideraccount.FieldUserID, usergrantedprovideraccount.FieldProviderAccountID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserGrantedProviderAccount fields.
func (ugpa *UserGrantedProviderAccount) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usergrantedprovideraccount.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ugpa.ID = int64(value.Int64)
		case usergrantedprovideraccount.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				ugpa.UserID = value.Int64
			}
		case usergrantedprovideraccount.FieldProviderAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field provider_account_id", values[i])
			} else if value.Valid {
				ugpa.ProviderAccountID = value.Int64
			}
		default:
			ugpa.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserGrantedProviderAccount.
// This includes values selected through modifiers, order, etc.
func (ugpa *UserGrantedProviderAccount) Value(name string) (ent.Value, error) {
	return ugpa.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserGrantedProviderAccount entity.
func (ugpa *UserGrantedProviderAccount) QueryUser() *UserQuery {
	return NewUserGrantedProviderAccountClient(ugpa.config).QueryUser(ugpa)
}

// QueryProviderAccount queries the "provider_account" edge of the UserGrantedProviderAccount entity.
func (ugpa *UserGrantedProviderAccount) QueryProviderAccount() *ProviderAccountQuery {
	return NewUserGrantedProviderAccountClient(ugpa.config).QueryProviderAccount(ugpa)
}

// Update returns a builder for updating this UserGrantedProviderAccount.
// Note that you need to call UserGrantedProviderAccount.Unwrap() before calling this method if this UserGrantedProviderAccount
// was returned from a transaction, and the transaction was committed or rolled back.
func (ugpa *UserGrantedProviderAccount) Update() *UserGrantedProviderAccountUpdateOne {
	return NewUserGrantedProviderAccountClient(ugpa.config).UpdateOne(ugpa)
}

// Unwrap unwraps the UserGrantedProviderAccount entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ugpa *UserGrantedProviderAccount) Unwrap() *UserGrantedProviderAccount {
	_tx, ok := ugpa.config.driver.(*txDriver)
	if !ok {
		panic("dbrt: UserGrantedProviderAccount is not a transactional entity")
	}
	ugpa.config.driver = _tx.drv
	return ugpa
}

// String implements the fmt.Stringer.
func (ugpa *UserGrantedProviderAccount) String() string {
	var builder strings.Builder
	builder.WriteString("UserGrantedProviderAccount(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ugpa.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", ugpa.UserID))
	builder.WriteString(", ")
	builder.WriteString("provider_account_id=")
	builder.WriteString(fmt.Sprintf("%v", ugpa.ProviderAccountID))
	builder.WriteByte(')')
	return builder.String()
}

// UserGrantedProviderAccounts is a parsable slice of UserGrantedProviderAccount.
type UserGrantedProviderAccounts []*UserGrantedProviderAccount
