// Code generated by ent, DO NOT EDIT.

package dbrt

import (
	"cocoq/server/database/dbrt/predicate"
	"cocoq/server/database/dbrt/usergrantedprovideraccount"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserGrantedProviderAccountDelete is the builder for deleting a UserGrantedProviderAccount entity.
type UserGrantedProviderAccountDelete struct {
	config
	hooks    []Hook
	mutation *UserGrantedProviderAccountMutation
}

// Where appends a list predicates to the UserGrantedProviderAccountDelete builder.
func (ugpad *UserGrantedProviderAccountDelete) Where(ps ...predicate.UserGrantedProviderAccount) *UserGrantedProviderAccountDelete {
	ugpad.mutation.Where(ps...)
	return ugpad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ugpad *UserGrantedProviderAccountDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ugpad.sqlExec, ugpad.mutation, ugpad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ugpad *UserGrantedProviderAccountDelete) ExecX(ctx context.Context) int {
	n, err := ugpad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ugpad *UserGrantedProviderAccountDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(usergrantedprovideraccount.Table, sqlgraph.NewFieldSpec(usergrantedprovideraccount.FieldID, field.TypeInt64))
	if ps := ugpad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ugpad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ugpad.mutation.done = true
	return affected, err
}

// UserGrantedProviderAccountDeleteOne is the builder for deleting a single UserGrantedProviderAccount entity.
type UserGrantedProviderAccountDeleteOne struct {
	ugpad *UserGrantedProviderAccountDelete
}

// Where appends a list predicates to the UserGrantedProviderAccountDelete builder.
func (ugpado *UserGrantedProviderAccountDeleteOne) Where(ps ...predicate.UserGrantedProviderAccount) *UserGrantedProviderAccountDeleteOne {
	ugpado.ugpad.mutation.Where(ps...)
	return ugpado
}

// Exec executes the deletion query.
func (ugpado *UserGrantedProviderAccountDeleteOne) Exec(ctx context.Context) error {
	n, err := ugpado.ugpad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usergrantedprovideraccount.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ugpado *UserGrantedProviderAccountDeleteOne) ExecX(ctx context.Context) {
	if err := ugpado.Exec(ctx); err != nil {
		panic(err)
	}
}
