// Code generated by ent, DO NOT EDIT.

package dbrt

import (
	"cocoq/server/database/dbrt/faketoken"
	"cocoq/server/database/dbrt/predicate"
	"cocoq/server/database/dbrt/user"
	"cocoq/server/database/dbrt/usergrantedprovideraccount"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (uu *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	uu.mutation.Where(ps...)
	return uu
}

// SetUpdatedAt sets the "updated_at" field.
func (uu *UserUpdate) SetUpdatedAt(t time.Time) *UserUpdate {
	uu.mutation.SetUpdatedAt(t)
	return uu
}

// SetOauthStateToken sets the "oauth_state_token" field.
func (uu *UserUpdate) SetOauthStateToken(s string) *UserUpdate {
	uu.mutation.SetOauthStateToken(s)
	return uu
}

// SetNillableOauthStateToken sets the "oauth_state_token" field if the given value is not nil.
func (uu *UserUpdate) SetNillableOauthStateToken(s *string) *UserUpdate {
	if s != nil {
		uu.SetOauthStateToken(*s)
	}
	return uu
}

// SetState sets the "state" field.
func (uu *UserUpdate) SetState(i int64) *UserUpdate {
	uu.mutation.ResetState()
	uu.mutation.SetState(i)
	return uu
}

// SetNillableState sets the "state" field if the given value is not nil.
func (uu *UserUpdate) SetNillableState(i *int64) *UserUpdate {
	if i != nil {
		uu.SetState(*i)
	}
	return uu
}

// AddState adds i to the "state" field.
func (uu *UserUpdate) AddState(i int64) *UserUpdate {
	uu.mutation.AddState(i)
	return uu
}

// AddFakeTokenIDs adds the "fake_tokens" edge to the FakeToken entity by IDs.
func (uu *UserUpdate) AddFakeTokenIDs(ids ...int64) *UserUpdate {
	uu.mutation.AddFakeTokenIDs(ids...)
	return uu
}

// AddFakeTokens adds the "fake_tokens" edges to the FakeToken entity.
func (uu *UserUpdate) AddFakeTokens(f ...*FakeToken) *UserUpdate {
	ids := make([]int64, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return uu.AddFakeTokenIDs(ids...)
}

// AddGrantedProviderAccountIDs adds the "granted_provider_accounts" edge to the UserGrantedProviderAccount entity by IDs.
func (uu *UserUpdate) AddGrantedProviderAccountIDs(ids ...int64) *UserUpdate {
	uu.mutation.AddGrantedProviderAccountIDs(ids...)
	return uu
}

// AddGrantedProviderAccounts adds the "granted_provider_accounts" edges to the UserGrantedProviderAccount entity.
func (uu *UserUpdate) AddGrantedProviderAccounts(u ...*UserGrantedProviderAccount) *UserUpdate {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uu.AddGrantedProviderAccountIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (uu *UserUpdate) Mutation() *UserMutation {
	return uu.mutation
}

// ClearFakeTokens clears all "fake_tokens" edges to the FakeToken entity.
func (uu *UserUpdate) ClearFakeTokens() *UserUpdate {
	uu.mutation.ClearFakeTokens()
	return uu
}

// RemoveFakeTokenIDs removes the "fake_tokens" edge to FakeToken entities by IDs.
func (uu *UserUpdate) RemoveFakeTokenIDs(ids ...int64) *UserUpdate {
	uu.mutation.RemoveFakeTokenIDs(ids...)
	return uu
}

// RemoveFakeTokens removes "fake_tokens" edges to FakeToken entities.
func (uu *UserUpdate) RemoveFakeTokens(f ...*FakeToken) *UserUpdate {
	ids := make([]int64, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return uu.RemoveFakeTokenIDs(ids...)
}

// ClearGrantedProviderAccounts clears all "granted_provider_accounts" edges to the UserGrantedProviderAccount entity.
func (uu *UserUpdate) ClearGrantedProviderAccounts() *UserUpdate {
	uu.mutation.ClearGrantedProviderAccounts()
	return uu
}

// RemoveGrantedProviderAccountIDs removes the "granted_provider_accounts" edge to UserGrantedProviderAccount entities by IDs.
func (uu *UserUpdate) RemoveGrantedProviderAccountIDs(ids ...int64) *UserUpdate {
	uu.mutation.RemoveGrantedProviderAccountIDs(ids...)
	return uu
}

// RemoveGrantedProviderAccounts removes "granted_provider_accounts" edges to UserGrantedProviderAccount entities.
func (uu *UserUpdate) RemoveGrantedProviderAccounts(u ...*UserGrantedProviderAccount) *UserUpdate {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uu.RemoveGrantedProviderAccountIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uu *UserUpdate) Save(ctx context.Context) (int, error) {
	uu.defaults()
	return withHooks(ctx, uu.sqlSave, uu.mutation, uu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uu *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *UserUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *UserUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uu *UserUpdate) defaults() {
	if _, ok := uu.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		uu.mutation.SetUpdatedAt(v)
	}
}

func (uu *UserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64))
	if ps := uu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uu.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := uu.mutation.OauthStateToken(); ok {
		_spec.SetField(user.FieldOauthStateToken, field.TypeString, value)
	}
	if value, ok := uu.mutation.State(); ok {
		_spec.SetField(user.FieldState, field.TypeInt64, value)
	}
	if value, ok := uu.mutation.AddedState(); ok {
		_spec.AddField(user.FieldState, field.TypeInt64, value)
	}
	if uu.mutation.FakeTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.FakeTokensTable,
			Columns: []string{user.FakeTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(faketoken.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedFakeTokensIDs(); len(nodes) > 0 && !uu.mutation.FakeTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.FakeTokensTable,
			Columns: []string{user.FakeTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(faketoken.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.FakeTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.FakeTokensTable,
			Columns: []string{user.FakeTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(faketoken.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.GrantedProviderAccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.GrantedProviderAccountsTable,
			Columns: []string{user.GrantedProviderAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usergrantedprovideraccount.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedGrantedProviderAccountsIDs(); len(nodes) > 0 && !uu.mutation.GrantedProviderAccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.GrantedProviderAccountsTable,
			Columns: []string{user.GrantedProviderAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usergrantedprovideraccount.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.GrantedProviderAccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.GrantedProviderAccountsTable,
			Columns: []string{user.GrantedProviderAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usergrantedprovideraccount.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uu.mutation.done = true
	return n, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (uuo *UserUpdateOne) SetUpdatedAt(t time.Time) *UserUpdateOne {
	uuo.mutation.SetUpdatedAt(t)
	return uuo
}

// SetOauthStateToken sets the "oauth_state_token" field.
func (uuo *UserUpdateOne) SetOauthStateToken(s string) *UserUpdateOne {
	uuo.mutation.SetOauthStateToken(s)
	return uuo
}

// SetNillableOauthStateToken sets the "oauth_state_token" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableOauthStateToken(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetOauthStateToken(*s)
	}
	return uuo
}

// SetState sets the "state" field.
func (uuo *UserUpdateOne) SetState(i int64) *UserUpdateOne {
	uuo.mutation.ResetState()
	uuo.mutation.SetState(i)
	return uuo
}

// SetNillableState sets the "state" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableState(i *int64) *UserUpdateOne {
	if i != nil {
		uuo.SetState(*i)
	}
	return uuo
}

// AddState adds i to the "state" field.
func (uuo *UserUpdateOne) AddState(i int64) *UserUpdateOne {
	uuo.mutation.AddState(i)
	return uuo
}

// AddFakeTokenIDs adds the "fake_tokens" edge to the FakeToken entity by IDs.
func (uuo *UserUpdateOne) AddFakeTokenIDs(ids ...int64) *UserUpdateOne {
	uuo.mutation.AddFakeTokenIDs(ids...)
	return uuo
}

// AddFakeTokens adds the "fake_tokens" edges to the FakeToken entity.
func (uuo *UserUpdateOne) AddFakeTokens(f ...*FakeToken) *UserUpdateOne {
	ids := make([]int64, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return uuo.AddFakeTokenIDs(ids...)
}

// AddGrantedProviderAccountIDs adds the "granted_provider_accounts" edge to the UserGrantedProviderAccount entity by IDs.
func (uuo *UserUpdateOne) AddGrantedProviderAccountIDs(ids ...int64) *UserUpdateOne {
	uuo.mutation.AddGrantedProviderAccountIDs(ids...)
	return uuo
}

// AddGrantedProviderAccounts adds the "granted_provider_accounts" edges to the UserGrantedProviderAccount entity.
func (uuo *UserUpdateOne) AddGrantedProviderAccounts(u ...*UserGrantedProviderAccount) *UserUpdateOne {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uuo.AddGrantedProviderAccountIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (uuo *UserUpdateOne) Mutation() *UserMutation {
	return uuo.mutation
}

// ClearFakeTokens clears all "fake_tokens" edges to the FakeToken entity.
func (uuo *UserUpdateOne) ClearFakeTokens() *UserUpdateOne {
	uuo.mutation.ClearFakeTokens()
	return uuo
}

// RemoveFakeTokenIDs removes the "fake_tokens" edge to FakeToken entities by IDs.
func (uuo *UserUpdateOne) RemoveFakeTokenIDs(ids ...int64) *UserUpdateOne {
	uuo.mutation.RemoveFakeTokenIDs(ids...)
	return uuo
}

// RemoveFakeTokens removes "fake_tokens" edges to FakeToken entities.
func (uuo *UserUpdateOne) RemoveFakeTokens(f ...*FakeToken) *UserUpdateOne {
	ids := make([]int64, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return uuo.RemoveFakeTokenIDs(ids...)
}

// ClearGrantedProviderAccounts clears all "granted_provider_accounts" edges to the UserGrantedProviderAccount entity.
func (uuo *UserUpdateOne) ClearGrantedProviderAccounts() *UserUpdateOne {
	uuo.mutation.ClearGrantedProviderAccounts()
	return uuo
}

// RemoveGrantedProviderAccountIDs removes the "granted_provider_accounts" edge to UserGrantedProviderAccount entities by IDs.
func (uuo *UserUpdateOne) RemoveGrantedProviderAccountIDs(ids ...int64) *UserUpdateOne {
	uuo.mutation.RemoveGrantedProviderAccountIDs(ids...)
	return uuo
}

// RemoveGrantedProviderAccounts removes "granted_provider_accounts" edges to UserGrantedProviderAccount entities.
func (uuo *UserUpdateOne) RemoveGrantedProviderAccounts(u ...*UserGrantedProviderAccount) *UserUpdateOne {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uuo.RemoveGrantedProviderAccountIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (uuo *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	uuo.mutation.Where(ps...)
	return uuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uuo *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	uuo.fields = append([]string{field}, fields...)
	return uuo
}

// Save executes the query and returns the updated User entity.
func (uuo *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	uuo.defaults()
	return withHooks(ctx, uuo.sqlSave, uuo.mutation, uuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uuo *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *UserUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uuo *UserUpdateOne) defaults() {
	if _, ok := uuo.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		uuo.mutation.SetUpdatedAt(v)
	}
}

func (uuo *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64))
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`dbrt: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("dbrt: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uuo.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := uuo.mutation.OauthStateToken(); ok {
		_spec.SetField(user.FieldOauthStateToken, field.TypeString, value)
	}
	if value, ok := uuo.mutation.State(); ok {
		_spec.SetField(user.FieldState, field.TypeInt64, value)
	}
	if value, ok := uuo.mutation.AddedState(); ok {
		_spec.AddField(user.FieldState, field.TypeInt64, value)
	}
	if uuo.mutation.FakeTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.FakeTokensTable,
			Columns: []string{user.FakeTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(faketoken.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedFakeTokensIDs(); len(nodes) > 0 && !uuo.mutation.FakeTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.FakeTokensTable,
			Columns: []string{user.FakeTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(faketoken.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.FakeTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.FakeTokensTable,
			Columns: []string{user.FakeTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(faketoken.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.GrantedProviderAccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.GrantedProviderAccountsTable,
			Columns: []string{user.GrantedProviderAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usergrantedprovideraccount.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedGrantedProviderAccountsIDs(); len(nodes) > 0 && !uuo.mutation.GrantedProviderAccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.GrantedProviderAccountsTable,
			Columns: []string{user.GrantedProviderAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usergrantedprovideraccount.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.GrantedProviderAccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.GrantedProviderAccountsTable,
			Columns: []string{user.GrantedProviderAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usergrantedprovideraccount.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: uuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uuo.mutation.done = true
	return _node, nil
}
