// Code generated by ent, DO NOT EDIT.

package dbrt

import (
	"cocoq/server/database/dbrt/predicate"
	"cocoq/server/database/dbrt/provideraccount"
	"cocoq/server/database/dbrt/user"
	"cocoq/server/database/dbrt/usergrantedprovideraccount"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserGrantedProviderAccountUpdate is the builder for updating UserGrantedProviderAccount entities.
type UserGrantedProviderAccountUpdate struct {
	config
	hooks    []Hook
	mutation *UserGrantedProviderAccountMutation
}

// Where appends a list predicates to the UserGrantedProviderAccountUpdate builder.
func (ugpau *UserGrantedProviderAccountUpdate) Where(ps ...predicate.UserGrantedProviderAccount) *UserGrantedProviderAccountUpdate {
	ugpau.mutation.Where(ps...)
	return ugpau
}

// SetUserID sets the "user_id" field.
func (ugpau *UserGrantedProviderAccountUpdate) SetUserID(i int64) *UserGrantedProviderAccountUpdate {
	ugpau.mutation.SetUserID(i)
	return ugpau
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (ugpau *UserGrantedProviderAccountUpdate) SetNillableUserID(i *int64) *UserGrantedProviderAccountUpdate {
	if i != nil {
		ugpau.SetUserID(*i)
	}
	return ugpau
}

// SetProviderAccountID sets the "provider_account_id" field.
func (ugpau *UserGrantedProviderAccountUpdate) SetProviderAccountID(i int64) *UserGrantedProviderAccountUpdate {
	ugpau.mutation.SetProviderAccountID(i)
	return ugpau
}

// SetNillableProviderAccountID sets the "provider_account_id" field if the given value is not nil.
func (ugpau *UserGrantedProviderAccountUpdate) SetNillableProviderAccountID(i *int64) *UserGrantedProviderAccountUpdate {
	if i != nil {
		ugpau.SetProviderAccountID(*i)
	}
	return ugpau
}

// SetUser sets the "user" edge to the User entity.
func (ugpau *UserGrantedProviderAccountUpdate) SetUser(u *User) *UserGrantedProviderAccountUpdate {
	return ugpau.SetUserID(u.ID)
}

// SetProviderAccount sets the "provider_account" edge to the ProviderAccount entity.
func (ugpau *UserGrantedProviderAccountUpdate) SetProviderAccount(p *ProviderAccount) *UserGrantedProviderAccountUpdate {
	return ugpau.SetProviderAccountID(p.ID)
}

// Mutation returns the UserGrantedProviderAccountMutation object of the builder.
func (ugpau *UserGrantedProviderAccountUpdate) Mutation() *UserGrantedProviderAccountMutation {
	return ugpau.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (ugpau *UserGrantedProviderAccountUpdate) ClearUser() *UserGrantedProviderAccountUpdate {
	ugpau.mutation.ClearUser()
	return ugpau
}

// ClearProviderAccount clears the "provider_account" edge to the ProviderAccount entity.
func (ugpau *UserGrantedProviderAccountUpdate) ClearProviderAccount() *UserGrantedProviderAccountUpdate {
	ugpau.mutation.ClearProviderAccount()
	return ugpau
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ugpau *UserGrantedProviderAccountUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ugpau.sqlSave, ugpau.mutation, ugpau.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ugpau *UserGrantedProviderAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := ugpau.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ugpau *UserGrantedProviderAccountUpdate) Exec(ctx context.Context) error {
	_, err := ugpau.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ugpau *UserGrantedProviderAccountUpdate) ExecX(ctx context.Context) {
	if err := ugpau.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ugpau *UserGrantedProviderAccountUpdate) check() error {
	if ugpau.mutation.UserCleared() && len(ugpau.mutation.UserIDs()) > 0 {
		return errors.New(`dbrt: clearing a required unique edge "UserGrantedProviderAccount.user"`)
	}
	if ugpau.mutation.ProviderAccountCleared() && len(ugpau.mutation.ProviderAccountIDs()) > 0 {
		return errors.New(`dbrt: clearing a required unique edge "UserGrantedProviderAccount.provider_account"`)
	}
	return nil
}

func (ugpau *UserGrantedProviderAccountUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ugpau.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(usergrantedprovideraccount.Table, usergrantedprovideraccount.Columns, sqlgraph.NewFieldSpec(usergrantedprovideraccount.FieldID, field.TypeInt64))
	if ps := ugpau.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if ugpau.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usergrantedprovideraccount.UserTable,
			Columns: []string{usergrantedprovideraccount.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ugpau.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usergrantedprovideraccount.UserTable,
			Columns: []string{usergrantedprovideraccount.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ugpau.mutation.ProviderAccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usergrantedprovideraccount.ProviderAccountTable,
			Columns: []string{usergrantedprovideraccount.ProviderAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provideraccount.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ugpau.mutation.ProviderAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usergrantedprovideraccount.ProviderAccountTable,
			Columns: []string{usergrantedprovideraccount.ProviderAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provideraccount.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ugpau.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usergrantedprovideraccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ugpau.mutation.done = true
	return n, nil
}

// UserGrantedProviderAccountUpdateOne is the builder for updating a single UserGrantedProviderAccount entity.
type UserGrantedProviderAccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserGrantedProviderAccountMutation
}

// SetUserID sets the "user_id" field.
func (ugpauo *UserGrantedProviderAccountUpdateOne) SetUserID(i int64) *UserGrantedProviderAccountUpdateOne {
	ugpauo.mutation.SetUserID(i)
	return ugpauo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (ugpauo *UserGrantedProviderAccountUpdateOne) SetNillableUserID(i *int64) *UserGrantedProviderAccountUpdateOne {
	if i != nil {
		ugpauo.SetUserID(*i)
	}
	return ugpauo
}

// SetProviderAccountID sets the "provider_account_id" field.
func (ugpauo *UserGrantedProviderAccountUpdateOne) SetProviderAccountID(i int64) *UserGrantedProviderAccountUpdateOne {
	ugpauo.mutation.SetProviderAccountID(i)
	return ugpauo
}

// SetNillableProviderAccountID sets the "provider_account_id" field if the given value is not nil.
func (ugpauo *UserGrantedProviderAccountUpdateOne) SetNillableProviderAccountID(i *int64) *UserGrantedProviderAccountUpdateOne {
	if i != nil {
		ugpauo.SetProviderAccountID(*i)
	}
	return ugpauo
}

// SetUser sets the "user" edge to the User entity.
func (ugpauo *UserGrantedProviderAccountUpdateOne) SetUser(u *User) *UserGrantedProviderAccountUpdateOne {
	return ugpauo.SetUserID(u.ID)
}

// SetProviderAccount sets the "provider_account" edge to the ProviderAccount entity.
func (ugpauo *UserGrantedProviderAccountUpdateOne) SetProviderAccount(p *ProviderAccount) *UserGrantedProviderAccountUpdateOne {
	return ugpauo.SetProviderAccountID(p.ID)
}

// Mutation returns the UserGrantedProviderAccountMutation object of the builder.
func (ugpauo *UserGrantedProviderAccountUpdateOne) Mutation() *UserGrantedProviderAccountMutation {
	return ugpauo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (ugpauo *UserGrantedProviderAccountUpdateOne) ClearUser() *UserGrantedProviderAccountUpdateOne {
	ugpauo.mutation.ClearUser()
	return ugpauo
}

// ClearProviderAccount clears the "provider_account" edge to the ProviderAccount entity.
func (ugpauo *UserGrantedProviderAccountUpdateOne) ClearProviderAccount() *UserGrantedProviderAccountUpdateOne {
	ugpauo.mutation.ClearProviderAccount()
	return ugpauo
}

// Where appends a list predicates to the UserGrantedProviderAccountUpdate builder.
func (ugpauo *UserGrantedProviderAccountUpdateOne) Where(ps ...predicate.UserGrantedProviderAccount) *UserGrantedProviderAccountUpdateOne {
	ugpauo.mutation.Where(ps...)
	return ugpauo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ugpauo *UserGrantedProviderAccountUpdateOne) Select(field string, fields ...string) *UserGrantedProviderAccountUpdateOne {
	ugpauo.fields = append([]string{field}, fields...)
	return ugpauo
}

// Save executes the query and returns the updated UserGrantedProviderAccount entity.
func (ugpauo *UserGrantedProviderAccountUpdateOne) Save(ctx context.Context) (*UserGrantedProviderAccount, error) {
	return withHooks(ctx, ugpauo.sqlSave, ugpauo.mutation, ugpauo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ugpauo *UserGrantedProviderAccountUpdateOne) SaveX(ctx context.Context) *UserGrantedProviderAccount {
	node, err := ugpauo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ugpauo *UserGrantedProviderAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := ugpauo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ugpauo *UserGrantedProviderAccountUpdateOne) ExecX(ctx context.Context) {
	if err := ugpauo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ugpauo *UserGrantedProviderAccountUpdateOne) check() error {
	if ugpauo.mutation.UserCleared() && len(ugpauo.mutation.UserIDs()) > 0 {
		return errors.New(`dbrt: clearing a required unique edge "UserGrantedProviderAccount.user"`)
	}
	if ugpauo.mutation.ProviderAccountCleared() && len(ugpauo.mutation.ProviderAccountIDs()) > 0 {
		return errors.New(`dbrt: clearing a required unique edge "UserGrantedProviderAccount.provider_account"`)
	}
	return nil
}

func (ugpauo *UserGrantedProviderAccountUpdateOne) sqlSave(ctx context.Context) (_node *UserGrantedProviderAccount, err error) {
	if err := ugpauo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usergrantedprovideraccount.Table, usergrantedprovideraccount.Columns, sqlgraph.NewFieldSpec(usergrantedprovideraccount.FieldID, field.TypeInt64))
	id, ok := ugpauo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`dbrt: missing "UserGrantedProviderAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ugpauo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usergrantedprovideraccount.FieldID)
		for _, f := range fields {
			if !usergrantedprovideraccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("dbrt: invalid field %q for query", f)}
			}
			if f != usergrantedprovideraccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ugpauo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if ugpauo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usergrantedprovideraccount.UserTable,
			Columns: []string{usergrantedprovideraccount.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ugpauo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usergrantedprovideraccount.UserTable,
			Columns: []string{usergrantedprovideraccount.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ugpauo.mutation.ProviderAccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usergrantedprovideraccount.ProviderAccountTable,
			Columns: []string{usergrantedprovideraccount.ProviderAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provideraccount.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ugpauo.mutation.ProviderAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usergrantedprovideraccount.ProviderAccountTable,
			Columns: []string{usergrantedprovideraccount.ProviderAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provideraccount.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserGrantedProviderAccount{config: ugpauo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ugpauo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usergrantedprovideraccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ugpauo.mutation.done = true
	return _node, nil
}
