// Code generated by ent, DO NOT EDIT.

package dbrt

import (
	"cocoq/server/database/dbrt/predicate"
	"cocoq/server/database/dbrt/provideraccount"
	"cocoq/server/database/dbrt/user"
	"cocoq/server/database/dbrt/usergrantedprovideraccount"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserGrantedProviderAccountQuery is the builder for querying UserGrantedProviderAccount entities.
type UserGrantedProviderAccountQuery struct {
	config
	ctx                 *QueryContext
	order               []usergrantedprovideraccount.OrderOption
	inters              []Interceptor
	predicates          []predicate.UserGrantedProviderAccount
	withUser            *UserQuery
	withProviderAccount *ProviderAccountQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserGrantedProviderAccountQuery builder.
func (ugpaq *UserGrantedProviderAccountQuery) Where(ps ...predicate.UserGrantedProviderAccount) *UserGrantedProviderAccountQuery {
	ugpaq.predicates = append(ugpaq.predicates, ps...)
	return ugpaq
}

// Limit the number of records to be returned by this query.
func (ugpaq *UserGrantedProviderAccountQuery) Limit(limit int) *UserGrantedProviderAccountQuery {
	ugpaq.ctx.Limit = &limit
	return ugpaq
}

// Offset to start from.
func (ugpaq *UserGrantedProviderAccountQuery) Offset(offset int) *UserGrantedProviderAccountQuery {
	ugpaq.ctx.Offset = &offset
	return ugpaq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ugpaq *UserGrantedProviderAccountQuery) Unique(unique bool) *UserGrantedProviderAccountQuery {
	ugpaq.ctx.Unique = &unique
	return ugpaq
}

// Order specifies how the records should be ordered.
func (ugpaq *UserGrantedProviderAccountQuery) Order(o ...usergrantedprovideraccount.OrderOption) *UserGrantedProviderAccountQuery {
	ugpaq.order = append(ugpaq.order, o...)
	return ugpaq
}

// QueryUser chains the current query on the "user" edge.
func (ugpaq *UserGrantedProviderAccountQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: ugpaq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ugpaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ugpaq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(usergrantedprovideraccount.Table, usergrantedprovideraccount.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, usergrantedprovideraccount.UserTable, usergrantedprovideraccount.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(ugpaq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProviderAccount chains the current query on the "provider_account" edge.
func (ugpaq *UserGrantedProviderAccountQuery) QueryProviderAccount() *ProviderAccountQuery {
	query := (&ProviderAccountClient{config: ugpaq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ugpaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ugpaq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(usergrantedprovideraccount.Table, usergrantedprovideraccount.FieldID, selector),
			sqlgraph.To(provideraccount.Table, provideraccount.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, usergrantedprovideraccount.ProviderAccountTable, usergrantedprovideraccount.ProviderAccountColumn),
		)
		fromU = sqlgraph.SetNeighbors(ugpaq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserGrantedProviderAccount entity from the query.
// Returns a *NotFoundError when no UserGrantedProviderAccount was found.
func (ugpaq *UserGrantedProviderAccountQuery) First(ctx context.Context) (*UserGrantedProviderAccount, error) {
	nodes, err := ugpaq.Limit(1).All(setContextOp(ctx, ugpaq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{usergrantedprovideraccount.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ugpaq *UserGrantedProviderAccountQuery) FirstX(ctx context.Context) *UserGrantedProviderAccount {
	node, err := ugpaq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserGrantedProviderAccount ID from the query.
// Returns a *NotFoundError when no UserGrantedProviderAccount ID was found.
func (ugpaq *UserGrantedProviderAccountQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = ugpaq.Limit(1).IDs(setContextOp(ctx, ugpaq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{usergrantedprovideraccount.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ugpaq *UserGrantedProviderAccountQuery) FirstIDX(ctx context.Context) int64 {
	id, err := ugpaq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserGrantedProviderAccount entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserGrantedProviderAccount entity is found.
// Returns a *NotFoundError when no UserGrantedProviderAccount entities are found.
func (ugpaq *UserGrantedProviderAccountQuery) Only(ctx context.Context) (*UserGrantedProviderAccount, error) {
	nodes, err := ugpaq.Limit(2).All(setContextOp(ctx, ugpaq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{usergrantedprovideraccount.Label}
	default:
		return nil, &NotSingularError{usergrantedprovideraccount.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ugpaq *UserGrantedProviderAccountQuery) OnlyX(ctx context.Context) *UserGrantedProviderAccount {
	node, err := ugpaq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserGrantedProviderAccount ID in the query.
// Returns a *NotSingularError when more than one UserGrantedProviderAccount ID is found.
// Returns a *NotFoundError when no entities are found.
func (ugpaq *UserGrantedProviderAccountQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = ugpaq.Limit(2).IDs(setContextOp(ctx, ugpaq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{usergrantedprovideraccount.Label}
	default:
		err = &NotSingularError{usergrantedprovideraccount.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ugpaq *UserGrantedProviderAccountQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := ugpaq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserGrantedProviderAccounts.
func (ugpaq *UserGrantedProviderAccountQuery) All(ctx context.Context) ([]*UserGrantedProviderAccount, error) {
	ctx = setContextOp(ctx, ugpaq.ctx, ent.OpQueryAll)
	if err := ugpaq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserGrantedProviderAccount, *UserGrantedProviderAccountQuery]()
	return withInterceptors[[]*UserGrantedProviderAccount](ctx, ugpaq, qr, ugpaq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ugpaq *UserGrantedProviderAccountQuery) AllX(ctx context.Context) []*UserGrantedProviderAccount {
	nodes, err := ugpaq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserGrantedProviderAccount IDs.
func (ugpaq *UserGrantedProviderAccountQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if ugpaq.ctx.Unique == nil && ugpaq.path != nil {
		ugpaq.Unique(true)
	}
	ctx = setContextOp(ctx, ugpaq.ctx, ent.OpQueryIDs)
	if err = ugpaq.Select(usergrantedprovideraccount.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ugpaq *UserGrantedProviderAccountQuery) IDsX(ctx context.Context) []int64 {
	ids, err := ugpaq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ugpaq *UserGrantedProviderAccountQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ugpaq.ctx, ent.OpQueryCount)
	if err := ugpaq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ugpaq, querierCount[*UserGrantedProviderAccountQuery](), ugpaq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ugpaq *UserGrantedProviderAccountQuery) CountX(ctx context.Context) int {
	count, err := ugpaq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ugpaq *UserGrantedProviderAccountQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ugpaq.ctx, ent.OpQueryExist)
	switch _, err := ugpaq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("dbrt: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ugpaq *UserGrantedProviderAccountQuery) ExistX(ctx context.Context) bool {
	exist, err := ugpaq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserGrantedProviderAccountQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ugpaq *UserGrantedProviderAccountQuery) Clone() *UserGrantedProviderAccountQuery {
	if ugpaq == nil {
		return nil
	}
	return &UserGrantedProviderAccountQuery{
		config:              ugpaq.config,
		ctx:                 ugpaq.ctx.Clone(),
		order:               append([]usergrantedprovideraccount.OrderOption{}, ugpaq.order...),
		inters:              append([]Interceptor{}, ugpaq.inters...),
		predicates:          append([]predicate.UserGrantedProviderAccount{}, ugpaq.predicates...),
		withUser:            ugpaq.withUser.Clone(),
		withProviderAccount: ugpaq.withProviderAccount.Clone(),
		// clone intermediate query.
		sql:  ugpaq.sql.Clone(),
		path: ugpaq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (ugpaq *UserGrantedProviderAccountQuery) WithUser(opts ...func(*UserQuery)) *UserGrantedProviderAccountQuery {
	query := (&UserClient{config: ugpaq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ugpaq.withUser = query
	return ugpaq
}

// WithProviderAccount tells the query-builder to eager-load the nodes that are connected to
// the "provider_account" edge. The optional arguments are used to configure the query builder of the edge.
func (ugpaq *UserGrantedProviderAccountQuery) WithProviderAccount(opts ...func(*ProviderAccountQuery)) *UserGrantedProviderAccountQuery {
	query := (&ProviderAccountClient{config: ugpaq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ugpaq.withProviderAccount = query
	return ugpaq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int64 `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserGrantedProviderAccount.Query().
//		GroupBy(usergrantedprovideraccount.FieldUserID).
//		Aggregate(dbrt.Count()).
//		Scan(ctx, &v)
func (ugpaq *UserGrantedProviderAccountQuery) GroupBy(field string, fields ...string) *UserGrantedProviderAccountGroupBy {
	ugpaq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserGrantedProviderAccountGroupBy{build: ugpaq}
	grbuild.flds = &ugpaq.ctx.Fields
	grbuild.label = usergrantedprovideraccount.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int64 `json:"user_id,omitempty"`
//	}
//
//	client.UserGrantedProviderAccount.Query().
//		Select(usergrantedprovideraccount.FieldUserID).
//		Scan(ctx, &v)
func (ugpaq *UserGrantedProviderAccountQuery) Select(fields ...string) *UserGrantedProviderAccountSelect {
	ugpaq.ctx.Fields = append(ugpaq.ctx.Fields, fields...)
	sbuild := &UserGrantedProviderAccountSelect{UserGrantedProviderAccountQuery: ugpaq}
	sbuild.label = usergrantedprovideraccount.Label
	sbuild.flds, sbuild.scan = &ugpaq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserGrantedProviderAccountSelect configured with the given aggregations.
func (ugpaq *UserGrantedProviderAccountQuery) Aggregate(fns ...AggregateFunc) *UserGrantedProviderAccountSelect {
	return ugpaq.Select().Aggregate(fns...)
}

func (ugpaq *UserGrantedProviderAccountQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ugpaq.inters {
		if inter == nil {
			return fmt.Errorf("dbrt: uninitialized interceptor (forgotten import dbrt/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ugpaq); err != nil {
				return err
			}
		}
	}
	for _, f := range ugpaq.ctx.Fields {
		if !usergrantedprovideraccount.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("dbrt: invalid field %q for query", f)}
		}
	}
	if ugpaq.path != nil {
		prev, err := ugpaq.path(ctx)
		if err != nil {
			return err
		}
		ugpaq.sql = prev
	}
	return nil
}

func (ugpaq *UserGrantedProviderAccountQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserGrantedProviderAccount, error) {
	var (
		nodes       = []*UserGrantedProviderAccount{}
		_spec       = ugpaq.querySpec()
		loadedTypes = [2]bool{
			ugpaq.withUser != nil,
			ugpaq.withProviderAccount != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserGrantedProviderAccount).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserGrantedProviderAccount{config: ugpaq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ugpaq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ugpaq.withUser; query != nil {
		if err := ugpaq.loadUser(ctx, query, nodes, nil,
			func(n *UserGrantedProviderAccount, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := ugpaq.withProviderAccount; query != nil {
		if err := ugpaq.loadProviderAccount(ctx, query, nodes, nil,
			func(n *UserGrantedProviderAccount, e *ProviderAccount) { n.Edges.ProviderAccount = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ugpaq *UserGrantedProviderAccountQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*UserGrantedProviderAccount, init func(*UserGrantedProviderAccount), assign func(*UserGrantedProviderAccount, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*UserGrantedProviderAccount)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (ugpaq *UserGrantedProviderAccountQuery) loadProviderAccount(ctx context.Context, query *ProviderAccountQuery, nodes []*UserGrantedProviderAccount, init func(*UserGrantedProviderAccount), assign func(*UserGrantedProviderAccount, *ProviderAccount)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*UserGrantedProviderAccount)
	for i := range nodes {
		fk := nodes[i].ProviderAccountID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(provideraccount.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "provider_account_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ugpaq *UserGrantedProviderAccountQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ugpaq.querySpec()
	_spec.Node.Columns = ugpaq.ctx.Fields
	if len(ugpaq.ctx.Fields) > 0 {
		_spec.Unique = ugpaq.ctx.Unique != nil && *ugpaq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ugpaq.driver, _spec)
}

func (ugpaq *UserGrantedProviderAccountQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(usergrantedprovideraccount.Table, usergrantedprovideraccount.Columns, sqlgraph.NewFieldSpec(usergrantedprovideraccount.FieldID, field.TypeInt64))
	_spec.From = ugpaq.sql
	if unique := ugpaq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ugpaq.path != nil {
		_spec.Unique = true
	}
	if fields := ugpaq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usergrantedprovideraccount.FieldID)
		for i := range fields {
			if fields[i] != usergrantedprovideraccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if ugpaq.withUser != nil {
			_spec.Node.AddColumnOnce(usergrantedprovideraccount.FieldUserID)
		}
		if ugpaq.withProviderAccount != nil {
			_spec.Node.AddColumnOnce(usergrantedprovideraccount.FieldProviderAccountID)
		}
	}
	if ps := ugpaq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ugpaq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ugpaq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ugpaq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ugpaq *UserGrantedProviderAccountQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ugpaq.driver.Dialect())
	t1 := builder.Table(usergrantedprovideraccount.Table)
	columns := ugpaq.ctx.Fields
	if len(columns) == 0 {
		columns = usergrantedprovideraccount.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ugpaq.sql != nil {
		selector = ugpaq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ugpaq.ctx.Unique != nil && *ugpaq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ugpaq.predicates {
		p(selector)
	}
	for _, p := range ugpaq.order {
		p(selector)
	}
	if offset := ugpaq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ugpaq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserGrantedProviderAccountGroupBy is the group-by builder for UserGrantedProviderAccount entities.
type UserGrantedProviderAccountGroupBy struct {
	selector
	build *UserGrantedProviderAccountQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ugpagb *UserGrantedProviderAccountGroupBy) Aggregate(fns ...AggregateFunc) *UserGrantedProviderAccountGroupBy {
	ugpagb.fns = append(ugpagb.fns, fns...)
	return ugpagb
}

// Scan applies the selector query and scans the result into the given value.
func (ugpagb *UserGrantedProviderAccountGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ugpagb.build.ctx, ent.OpQueryGroupBy)
	if err := ugpagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserGrantedProviderAccountQuery, *UserGrantedProviderAccountGroupBy](ctx, ugpagb.build, ugpagb, ugpagb.build.inters, v)
}

func (ugpagb *UserGrantedProviderAccountGroupBy) sqlScan(ctx context.Context, root *UserGrantedProviderAccountQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ugpagb.fns))
	for _, fn := range ugpagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ugpagb.flds)+len(ugpagb.fns))
		for _, f := range *ugpagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ugpagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ugpagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserGrantedProviderAccountSelect is the builder for selecting fields of UserGrantedProviderAccount entities.
type UserGrantedProviderAccountSelect struct {
	*UserGrantedProviderAccountQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ugpas *UserGrantedProviderAccountSelect) Aggregate(fns ...AggregateFunc) *UserGrantedProviderAccountSelect {
	ugpas.fns = append(ugpas.fns, fns...)
	return ugpas
}

// Scan applies the selector query and scans the result into the given value.
func (ugpas *UserGrantedProviderAccountSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ugpas.ctx, ent.OpQuerySelect)
	if err := ugpas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserGrantedProviderAccountQuery, *UserGrantedProviderAccountSelect](ctx, ugpas.UserGrantedProviderAccountQuery, ugpas, ugpas.inters, v)
}

func (ugpas *UserGrantedProviderAccountSelect) sqlScan(ctx context.Context, root *UserGrantedProviderAccountQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ugpas.fns))
	for _, fn := range ugpas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ugpas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ugpas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
