// Code generated by ent, DO NOT EDIT.

package dbrt

import (
	"cocoq/server/database/dbrt/provideraccount"
	"cocoq/server/database/dbrt/user"
	"cocoq/server/database/dbrt/usergrantedprovideraccount"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserGrantedProviderAccountCreate is the builder for creating a UserGrantedProviderAccount entity.
type UserGrantedProviderAccountCreate struct {
	config
	mutation *UserGrantedProviderAccountMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (ugpac *UserGrantedProviderAccountCreate) SetUserID(i int64) *UserGrantedProviderAccountCreate {
	ugpac.mutation.SetUserID(i)
	return ugpac
}

// SetProviderAccountID sets the "provider_account_id" field.
func (ugpac *UserGrantedProviderAccountCreate) SetProviderAccountID(i int64) *UserGrantedProviderAccountCreate {
	ugpac.mutation.SetProviderAccountID(i)
	return ugpac
}

// SetID sets the "id" field.
func (ugpac *UserGrantedProviderAccountCreate) SetID(i int64) *UserGrantedProviderAccountCreate {
	ugpac.mutation.SetID(i)
	return ugpac
}

// SetUser sets the "user" edge to the User entity.
func (ugpac *UserGrantedProviderAccountCreate) SetUser(u *User) *UserGrantedProviderAccountCreate {
	return ugpac.SetUserID(u.ID)
}

// SetProviderAccount sets the "provider_account" edge to the ProviderAccount entity.
func (ugpac *UserGrantedProviderAccountCreate) SetProviderAccount(p *ProviderAccount) *UserGrantedProviderAccountCreate {
	return ugpac.SetProviderAccountID(p.ID)
}

// Mutation returns the UserGrantedProviderAccountMutation object of the builder.
func (ugpac *UserGrantedProviderAccountCreate) Mutation() *UserGrantedProviderAccountMutation {
	return ugpac.mutation
}

// Save creates the UserGrantedProviderAccount in the database.
func (ugpac *UserGrantedProviderAccountCreate) Save(ctx context.Context) (*UserGrantedProviderAccount, error) {
	return withHooks(ctx, ugpac.sqlSave, ugpac.mutation, ugpac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ugpac *UserGrantedProviderAccountCreate) SaveX(ctx context.Context) *UserGrantedProviderAccount {
	v, err := ugpac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ugpac *UserGrantedProviderAccountCreate) Exec(ctx context.Context) error {
	_, err := ugpac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ugpac *UserGrantedProviderAccountCreate) ExecX(ctx context.Context) {
	if err := ugpac.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ugpac *UserGrantedProviderAccountCreate) check() error {
	if _, ok := ugpac.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`dbrt: missing required field "UserGrantedProviderAccount.user_id"`)}
	}
	if _, ok := ugpac.mutation.ProviderAccountID(); !ok {
		return &ValidationError{Name: "provider_account_id", err: errors.New(`dbrt: missing required field "UserGrantedProviderAccount.provider_account_id"`)}
	}
	if len(ugpac.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`dbrt: missing required edge "UserGrantedProviderAccount.user"`)}
	}
	if len(ugpac.mutation.ProviderAccountIDs()) == 0 {
		return &ValidationError{Name: "provider_account", err: errors.New(`dbrt: missing required edge "UserGrantedProviderAccount.provider_account"`)}
	}
	return nil
}

func (ugpac *UserGrantedProviderAccountCreate) sqlSave(ctx context.Context) (*UserGrantedProviderAccount, error) {
	if err := ugpac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ugpac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ugpac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	ugpac.mutation.id = &_node.ID
	ugpac.mutation.done = true
	return _node, nil
}

func (ugpac *UserGrantedProviderAccountCreate) createSpec() (*UserGrantedProviderAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &UserGrantedProviderAccount{config: ugpac.config}
		_spec = sqlgraph.NewCreateSpec(usergrantedprovideraccount.Table, sqlgraph.NewFieldSpec(usergrantedprovideraccount.FieldID, field.TypeInt64))
	)
	if id, ok := ugpac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if nodes := ugpac.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usergrantedprovideraccount.UserTable,
			Columns: []string{usergrantedprovideraccount.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ugpac.mutation.ProviderAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usergrantedprovideraccount.ProviderAccountTable,
			Columns: []string{usergrantedprovideraccount.ProviderAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provideraccount.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProviderAccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserGrantedProviderAccountCreateBulk is the builder for creating many UserGrantedProviderAccount entities in bulk.
type UserGrantedProviderAccountCreateBulk struct {
	config
	err      error
	builders []*UserGrantedProviderAccountCreate
}

// Save creates the UserGrantedProviderAccount entities in the database.
func (ugpacb *UserGrantedProviderAccountCreateBulk) Save(ctx context.Context) ([]*UserGrantedProviderAccount, error) {
	if ugpacb.err != nil {
		return nil, ugpacb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ugpacb.builders))
	nodes := make([]*UserGrantedProviderAccount, len(ugpacb.builders))
	mutators := make([]Mutator, len(ugpacb.builders))
	for i := range ugpacb.builders {
		func(i int, root context.Context) {
			builder := ugpacb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserGrantedProviderAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ugpacb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ugpacb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ugpacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ugpacb *UserGrantedProviderAccountCreateBulk) SaveX(ctx context.Context) []*UserGrantedProviderAccount {
	v, err := ugpacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ugpacb *UserGrantedProviderAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := ugpacb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ugpacb *UserGrantedProviderAccountCreateBulk) ExecX(ctx context.Context) {
	if err := ugpacb.Exec(ctx); err != nil {
		panic(err)
	}
}
