// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldOauthStateToken holds the string denoting the oauth_state_token field in the database.
	FieldOauthStateToken = "oauth_state_token"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// EdgeFakeTokens holds the string denoting the fake_tokens edge name in mutations.
	EdgeFakeTokens = "fake_tokens"
	// EdgeGrantedProviderAccounts holds the string denoting the granted_provider_accounts edge name in mutations.
	EdgeGrantedProviderAccounts = "granted_provider_accounts"
	// Table holds the table name of the user in the database.
	Table = "user"
	// FakeTokensTable is the table that holds the fake_tokens relation/edge.
	FakeTokensTable = "fake_token"
	// FakeTokensInverseTable is the table name for the FakeToken entity.
	// It exists in this package in order to avoid circular dependency with the "faketoken" package.
	FakeTokensInverseTable = "fake_token"
	// FakeTokensColumn is the table column denoting the fake_tokens relation/edge.
	FakeTokensColumn = "user_id"
	// GrantedProviderAccountsTable is the table that holds the granted_provider_accounts relation/edge.
	GrantedProviderAccountsTable = "user_granted_provider_account"
	// GrantedProviderAccountsInverseTable is the table name for the UserGrantedProviderAccount entity.
	// It exists in this package in order to avoid circular dependency with the "usergrantedprovideraccount" package.
	GrantedProviderAccountsInverseTable = "user_granted_provider_account"
	// GrantedProviderAccountsColumn is the table column denoting the granted_provider_accounts relation/edge.
	GrantedProviderAccountsColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldOauthStateToken,
	FieldState,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByOauthStateToken orders the results by the oauth_state_token field.
func ByOauthStateToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOauthStateToken, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByFakeTokensCount orders the results by fake_tokens count.
func ByFakeTokensCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFakeTokensStep(), opts...)
	}
}

// ByFakeTokens orders the results by fake_tokens terms.
func ByFakeTokens(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFakeTokensStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByGrantedProviderAccountsCount orders the results by granted_provider_accounts count.
func ByGrantedProviderAccountsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGrantedProviderAccountsStep(), opts...)
	}
}

// ByGrantedProviderAccounts orders the results by granted_provider_accounts terms.
func ByGrantedProviderAccounts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGrantedProviderAccountsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newFakeTokensStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FakeTokensInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FakeTokensTable, FakeTokensColumn),
	)
}
func newGrantedProviderAccountsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GrantedProviderAccountsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, GrantedProviderAccountsTable, GrantedProviderAccountsColumn),
	)
}
