// Code generated by ent, DO NOT EDIT.

package user

import (
	"cocoq/server/database/dbrt/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// OauthStateToken applies equality check predicate on the "oauth_state_token" field. It's identical to OauthStateTokenEQ.
func OauthStateToken(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldOauthStateToken, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldState, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUpdatedAt, v))
}

// OauthStateTokenEQ applies the EQ predicate on the "oauth_state_token" field.
func OauthStateTokenEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldOauthStateToken, v))
}

// OauthStateTokenNEQ applies the NEQ predicate on the "oauth_state_token" field.
func OauthStateTokenNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldOauthStateToken, v))
}

// OauthStateTokenIn applies the In predicate on the "oauth_state_token" field.
func OauthStateTokenIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldOauthStateToken, vs...))
}

// OauthStateTokenNotIn applies the NotIn predicate on the "oauth_state_token" field.
func OauthStateTokenNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldOauthStateToken, vs...))
}

// OauthStateTokenGT applies the GT predicate on the "oauth_state_token" field.
func OauthStateTokenGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldOauthStateToken, v))
}

// OauthStateTokenGTE applies the GTE predicate on the "oauth_state_token" field.
func OauthStateTokenGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldOauthStateToken, v))
}

// OauthStateTokenLT applies the LT predicate on the "oauth_state_token" field.
func OauthStateTokenLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldOauthStateToken, v))
}

// OauthStateTokenLTE applies the LTE predicate on the "oauth_state_token" field.
func OauthStateTokenLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldOauthStateToken, v))
}

// OauthStateTokenContains applies the Contains predicate on the "oauth_state_token" field.
func OauthStateTokenContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldOauthStateToken, v))
}

// OauthStateTokenHasPrefix applies the HasPrefix predicate on the "oauth_state_token" field.
func OauthStateTokenHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldOauthStateToken, v))
}

// OauthStateTokenHasSuffix applies the HasSuffix predicate on the "oauth_state_token" field.
func OauthStateTokenHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldOauthStateToken, v))
}

// OauthStateTokenEqualFold applies the EqualFold predicate on the "oauth_state_token" field.
func OauthStateTokenEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldOauthStateToken, v))
}

// OauthStateTokenContainsFold applies the ContainsFold predicate on the "oauth_state_token" field.
func OauthStateTokenContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldOauthStateToken, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldState, v))
}

// HasFakeTokens applies the HasEdge predicate on the "fake_tokens" edge.
func HasFakeTokens() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FakeTokensTable, FakeTokensColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFakeTokensWith applies the HasEdge predicate on the "fake_tokens" edge with a given conditions (other predicates).
func HasFakeTokensWith(preds ...predicate.FakeToken) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newFakeTokensStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGrantedProviderAccounts applies the HasEdge predicate on the "granted_provider_accounts" edge.
func HasGrantedProviderAccounts() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, GrantedProviderAccountsTable, GrantedProviderAccountsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGrantedProviderAccountsWith applies the HasEdge predicate on the "granted_provider_accounts" edge with a given conditions (other predicates).
func HasGrantedProviderAccountsWith(preds ...predicate.UserGrantedProviderAccount) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newGrantedProviderAccountsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
